### ISSUE TITLE
Rename Invoke-Builds (mind "s") to Build-Parallel (v4)

### ISSUE THREAD

**Issue by nightroman** [nightroman/Invoke-Build#100]
Parallel builds are invoked by the provided command `Invoke-Builds`. Long time
ago the name looked good enough. After some years of using it I do not think so:

- Plural noun forms are against the guidelines.
- It does not tell that it is about parallel builds.
- It is difficult to distinguish from `Invoke-Build`.

**TODO**

Rename `Invoke-Builds` to `Build-Parallel`.

**Notes**

`Build` is the standard verb in PowerShell v6. IB is not going to violate rules
in v2-v5 because the verb is for the alias and script names (guidelines are
about functions and cmdlets).

It's a breaking change if you use this command. Not many people do but there
are some. I am sorry for this inconvenience. The migration is simple, just
rename the command. This change is going to be released soon with another
breaking change. This is the right moment for renaming, in a way.

**Comment by KevinMarquette** [comment]
I like this change because it makes it more self-describing. Before looking at the documentation, I assumed that `Invoke-Build` and `Invoke-Builds` were the same command where one was there for backward compatibility.
