### ISSUE TITLE
Alternate DSL Syntax for Task

### ISSUE THREAD

**Issue by KevinMarquette** [nightroman/Invoke-Build#102]
When I am creating complex tasks, I often struggle to create them in a way that is pleasing to the eye. When doing partial builds for example, you may have several script blocks for parameters. Doing this inline feels ugly and I don't find that splatting the parameters feels a whole lot better.

I have created a helper DSL function in my scripts to address this and I would like to propose that `Invoke-Build` adopts something similar. 

Here is an example of a partial build with complex parameters.

    Task CreateHelp -Partial -Inputs {
        Get-ChildItem "$ModuleName\Public\*.ps1"
    } -Outputs {
        process
        {
            Get-ChildItem $_ | % {'{0}\{1}.md' -f $HelpRoot, $_.basename}
        }
    } 'ImportModule', {    
        process
        {
            $null = New-Item -Path $HelpRoot -ItemType Directory -ErrorAction SilentlyContinue        
            $mdHelp = @{
                #Module                = $script:ModuleName
                OutputFolder          = $HelpRoot
                AlphabeticParamsOrder = $true
                Verbose               = $true
                Force                 = $true
                Command               = Get-Item $_ | % basename
            }
            New-MarkdownHelp @mdHelp | % fullname
        }    
    }

I created a `ComplexTask` so that I could write it like this:

    ComplexTask CreateHelp @{
        Partial = $true
        Inputs  = { Get-ChildItem "$ModuleName\Public\*.ps1" }
        Outputs = {
            process
            {
                Get-ChildItem $_ | % {'{0}\{1}.md' -f $HelpRoot, $_.basename}
            }
        }    
        Action  = 'ImportModule', {    
            process
            {
                $null = New-Item -Path $HelpRoot -ItemType Directory -ErrorAction SilentlyContinue        
                $mdHelp = @{
                    #Module                = $script:ModuleName
                    OutputFolder          = $HelpRoot
                    AlphabeticParamsOrder = $true
                    Verbose               = $true
                    Force                 = $true
                    Command               = Get-Item $_ | % basename
                }
                New-MarkdownHelp @mdHelp | % fullname
            }    
        }
    }

I personally find this easier to follow and read. You will notice that I use a hashtable to achieve this. I do this so that I can splat this to your Task command. 

    function ComplexTask
    {
        [CmdletBinding()]
        param(
            [Parameter(Position = 0, Mandatory = 1)]
            [string]
            $Name,
            [Parameter(Position = 1, Mandatory = 1)]
            [hashtable]
            $Options
        )
        try     
        {
            if ( $null -ne $Options.Action )
            {
                $Options.Jobs = $Options.Action
                $Options.Remove('Action')
            }
            Task $Name @Options
        }
        catch 
        {
            Write-Error "Failed to execute taks [$Name]"
            throw
        }    
    }

I know using a hashtable this way has drawbacks like not having help, validation, or even autocomplete. But I do like the way it looks in my build scripts. I think the ideal implementation is that `Task` gains a 2nd parameter set that accepts a hashtable and handles this internally.

**Comment by nightroman** [comment]
I understand your problems very well. Do you know if PowerShell going to address this issue with improved splatting? Ideally, PowerShell should not require an intermediate variable for applying this "operator" to a hashtable.

If PowerShell v6 is not going to improve this then, yes, let's think of making things better at least for Invoke-Build tasks. It's not a promise but I like what you are suggesting. Let me think of pros, cons, and everything related.

**Comment by nightroman** [comment]
Do you think it should be something like this?

```powershell
task MakeDocs @{
    Inputs = {
        Get-ChildItem *.md
    }
    Outputs = {
        Get-ChildItem *.htm
    }
    Jobs = 'PreTask1', {
        'Making...'
    }
}
```

Or something else?

Is it really better than the current?

```powershell
task MakeDocs PreTask, {
    'Making...'
} -Inputs {
    Get-ChildItem *.md
} -Outputs {
    Get-ChildItem *.htm
}

**Comment by nightroman** [comment]
I think `function ComplexTask` is really complex :)
I can be a one-liner:

```powershell
function taskx($Name, $Parameters) {Add-BuildTask $Name @Parameters}

taskx Task2 @{
	Inputs = {Get-Item *.md}
	Outputs = {Get-Item *.htm}
	Jobs = 'Task1', {
		#...
	}
}

task Task1 {
	#...
}
```

**Comment by nightroman** [comment]
And even better:

```powershell
function taskx($Name, $Parameters) {task $Name @Parameters -Source $MyInvocation}

# Synopsis: About Task2
taskx Task2 @{
    Inputs = {Get-Item *.md}
    Outputs = {Get-Item *.htm}
    Jobs = 'Task1', {
        #...
    }
}

# Synopsis: About Task1
task Task1 {
    #...
}
```

Then `Invoke-Build ?` gives proper synopsis (and shows proper info on failures):

```
Name  Jobs        Synopsis
----  ----        --------
Task2 {Task1, {}} About Task2
Task1 {}          About Task1
```

And given that just one helper line makes this possible, I started to have
doubts that this should be in the engine. Simple scripts do not need this.
Complex scripts may just use this one-liner.

**Comment by KevinMarquette** [comment]
That is nice and compact. It would also be easy for someone to drop into their script if they wanted it.

**Comment by nightroman** [comment]
It would be nice if you engage this, for example in your [PSGraph/module.build.ps1](https://github.com/KevinMarquette/PSGraph/blob/master/module.build.ps1) where you use `ComplexTask`, so that we have a real example link in here.

Meanwhile, I am adding this tip to help and wiki. Will be in the coming soon v4.0.0 (very soon).

**Comment by nightroman** [comment]
I included this helper to help, see just released v4.0.0:

```powershell
. Invoke-Build
Get-Help task -Examples
```

[Here is the help source](https://github.com/nightroman/Invoke-Build/blob/master/InvokeBuild-Help.ps1#L549-L570).

I added it to wiki: [Incremental-Tasks#composing-tasks](https://github.com/nightroman/Invoke-Build/wiki/Incremental-Tasks#composing-tasks).

---

Eventually this difficulty should be solved in PowerShell. Sooner or later,
such a feature in the engine would be be obsolete.

I propose to close the issue and not do this or something similar in the
engine, not now at least.

NB: On my current machine I have just found 275 various build scripts for
Invoke-Build. For years somehow I did not need this helper `taskx`. Somehow
splatting was good and clear enough. But I am going to use `taskx`. It turns
out to be simple and handy.

**Comment by KevinMarquette** [comment]
It's one of those things that once you see it, you can't un-see it. I updated my PSGraph build script to use your shorthand method. https://github.com/KevinMarquette/PSGraph/blob/master/module.build.ps1#L13

I'll start working this into my other projects and plaster templates.

**Comment by KevinMarquette** [comment]
I'm also working on a talk about creating DSLs in PowerShell and will use this as one of my examples.

**Comment by nightroman** [comment]
@KevinMarquette The suggested `taskx` syntax will be supported natively by `task`, see the new issue. After v5.0.0 we do not even need a new parameter set for this feature.
