### ISSUE TITLE
Task conditioning

### ISSUE THREAD

**Issue by nsartor** [nightroman/Invoke-Build#108]
Thanks for writing this awesome script, very handy!

I'm seeing something weird when using task conditions in ib. Here's a sample script:

```powershell
function setVars
{
  return "foo value"
}

$foo = $null

Enter-Build {
  $foo = setVars;
}

task one {
  Write-Build white "Foo variable is $foo"
  # this returns true
  return ($foo -ne $null)
}

task two -if (($foo -ne $null)) {
  # never executes with above condition
  return ($foo -ne $null)
}

task . one, two
```
"$foo" is evaluating to $true as we'd expect, however, the task "two" does not run. If you remove the condition on it returns true.

Here's the output:
```
Build . C:\builds\ASIFramework\test.build.ps1
Task /./one
Foo variable is foo value
True
Done /./one 00:00:00.0216476
Task /./two skipped.
Done /. 00:00:00.0216476
Build succeeded. 2 tasks, 0 errors, 0 warnings 00:00:00.0372450
```

Shouldn't task "two" be executed? I've also tried using $script:foo since I thought it was a script issue but I get the same result.
Am I missing something?
Thanks!

**Comment by nightroman** [comment]
Hi @nsartor, thank you!

> Am I missing something?

Yes. Your condition is calculated during the build, not when tasks are added.
Thus, you should use a script block in `-If`

```powershell
task two -if {$foo -ne $null} {
    ...
}
```

AFAIR, the wiki should explain and help, too:

```
. Invoke-Build
help task -Parameter If
```

**Comment by nsartor** [comment]
@nightroman yep that was it! Thanks for the quick response!
