### ISSUE TITLE
Invoke-Build's dynamic parameters are poorly built

### ISSUE THREAD

**Issue by icraftsoftware** [nightroman/Invoke-Build#109]
Hello Roman,

Dynamic parameters injected by invoke-build miss all meta attributes but the ParameterSet one, which is initialized with default values. I figured out that it is not that easy to clone other meta attributes... but I have found a way that works for me. You can have a look at the function [`Convert-ScriptBlockParametersToDynamicParameters`](https://github.com/icraftsoftware/PowerShell.Factory/blob/c47d4ab2f178f7f96332f2e2a4c72c6ac55852fd/modules/Psx/Psx.psm1#L145).

I could not figure an easier way than to go back to the AST of a script block to easily clone all the meta attributes. I know my solution is not perfect; a.o. it does not deal with position property of the ParameterSet, and some strategy should be devised here. But it deals with all other kinds of attributes, i.e. ValidateSet, AllowNull, ValidateNotNull, etc. which are deerly missed by invoke-build.

Somewhere near [line](https://github.com/nightroman/Invoke-Build/blob/52616cf6cf91522d36075f1c8f33e6fe8aff5d8d/Invoke-Build.ps1#L110), you would have to use the following code (or embed the body of the function I am refering to):

```PowerShell
$source = Get-Content -Raw -Path $BuildFile
$sb = [scriptblock]::Create($source)
Convert-ScriptBlockParametersToDynamicParameters -ScriptBlock $sb
```

I really hope you don't mind me trying to help and I am really curious about your feedback!

Thanks

François

**Comment by nightroman** [comment]
Hi Francois,
Could you please explain why is this needed? (I am not trying to say this is not needed.)

NB: AST is not a good way to go, we still support PowerShell v2.

**Comment by nightroman** [comment]
Here is the code that mostly does the trick

```powershell
if ($_.Count) {&{
    $c = 'Verbose', 'Debug', 'ErrorAction', 'WarningAction', 'ErrorVariable', 'WarningVariable', 'OutVariable', 'OutBuffer', 'PipelineVariable', 'InformationAction', 'InformationVariable'
    $r = 'Task', 'File', 'Result', 'Safe', 'Summary', 'WhatIf'
    foreach($p in $_.Values) {
        if ($c -notcontains ($_ = $p.Name)) {
            if ($r -contains $_) {throw "Script uses reserved parameter '$_'."}
            ($a = New-Object System.Collections.ObjectModel.Collection[Attribute]).Add((New-Object System.Management.Automation.ParameterAttribute))
            foreach($x in $p.Attributes) {if ($x -isnot [System.Management.Automation.ParameterAttribute]) {$a.Add($x)}}
            ${*}.DP.Add($_, (New-Object System.Management.Automation.RuntimeDefinedParameter $_, $p.ParameterType, $a))
        }
    }
    ${*}.DP
}}
```

It copies all attributes except `[Parameter()]`. Copying it is tricky
because parameter sets, positions, etc. are not quite supported.
Build scripts are not exactly normal scripts.

But at least validation attributes work. I can see some advantages:

- `ValidateSet` automatically provides values for code completion.
- Validation errors are caught earlier.

This change looks promising. Please try in your scenarios and let me know how it goes.

**Comment by nightroman** [comment]
It looks like we can copy `[Parameter]`, too. Thus, we can use parameter set
names and mandatory values. Positions are dropped, so that script parameters
should be used as named.

```powershell
if ($_.Count) {&{
    $c = 'Verbose', 'Debug', 'ErrorAction', 'WarningAction', 'ErrorVariable', 'WarningVariable', 'OutVariable', 'OutBuffer', 'PipelineVariable', 'InformationAction', 'InformationVariable'
    $r = 'Task', 'File', 'Result', 'Safe', 'Summary', 'WhatIf'
    foreach($p in $_.Values) {
        if ($c -notcontains ($_ = $p.Name)) {
            if ($r -contains $_) {throw "Script uses reserved parameter '$_'."}
            foreach($a in $p.Attributes) {
                if ($a -is [System.Management.Automation.ParameterAttribute]) {$a.Position = [int]::MinValue}
            }
            ${*}.DP.Add($_, (New-Object System.Management.Automation.RuntimeDefinedParameter $_, $p.ParameterType, $p.Attributes))
        }
    }
    ${*}.DP
}}
```

I will test this for a while. Please try it with your cases, too.
If it works then it might be quite useful. Thank you for the idea.

**Comment by icraftsoftware** [comment]
Thanks, exactly what I needed... :)
