### ISSUE TITLE
How to bootstrap a dependency?

### ISSUE THREAD

**Issue by kberridge** [nightroman/Invoke-Build#110]
I have a powershell module that contains helpers I want to use in my invoke-build script.  It is distributed as a nuget, so I have a chicken or egg problem: I want to import that module, but I have to install it first.

Putting this at the top of my invoke-build script works:
```
if (!(test-path ..\packages\buildtools.1.1.1)) { .\nuget.exe install buildtools -Version 1.1.1 }
import-module ..\packages\buildtools.1.1.1\Tools\buildtools.psm1
```

But when run invoke-build prints `WARNING: Unexpected output:` messages which implies that I shouldn't be executing arbitrary code outside of a task block.  Is there a "correct" way to do something like this?

Thanks,
Kevin Berridge

**Comment by nightroman** [comment]
Hi Kevin,

This is simple. Either use `if (!$WhatIf) {...}` or place this code inside `Enter-Build {...}`. In this way, the code is called after loading the script but before invoking tasks.

**Comment by nightroman** [comment]
P.S. You can execute code outside tasks. But it should not output anything or this output should be suppressed/discarded. But this is not recommended for the code like yours. Because a script may be loaded not for building but for other reasons, e.g. for code completion of task names, analysis, etc.

**Comment by kberridge** [comment]
Just what I was hoping for thanks!  And as soon as you told me what it was called I found the docs: https://github.com/nightroman/Invoke-Build/wiki/Build-Scripts-Guidelines.  Sorry my google-fu didn't turn that up before I asked, but thanks for the stunningly quick reply!

**Comment by nightroman** [comment]
No problem, Kevin! I am glad you solved the issue.
