### ISSUE TITLE
Removal of `-Safe` in 5.0

### ISSUE THREAD

**Issue by tylerl0706** [nightroman/Invoke-Build#113]
Hi there!

I started noticing some build failures for the PowerShell VSCode extension as of today:

https://travis-ci.org/PowerShell/vscode-powershell/jobs/324178663

It looks like `-Safe` might not exist in InvokeBuild 5? Any recommendations on what to do instead?

Thanks for such an awesome tool!

**Comment by tylerl0706** [comment]
Here's the error:
```
ERROR: A parameter cannot be found that matches parameter name 'Safe'.
At /home/travis/build/PowerShell/PowerShellEditorServices/PowerShellEditorServices.build.ps1:172 char:23
+ task CITest (job Test -Safe), {
+                       ~~~~~
```

and the code in question:
https://github.com/PowerShell/PowerShellEditorServices/blob/master/PowerShellEditorServices.build.ps1#L172

**Comment by nightroman** [comment]
It is not removed but replaced, see the release notes.

Instead of `(job Test -Safe)` use `?Test`. Sorry for the breaking change. It was announced some time ago before the major release.

**Comment by tylerl0706** [comment]
That did the trick! Thanks for that.
