### ISSUE TITLE
Skipping Tasks?

### ISSUE THREAD

**Issue by JustinGrote** [nightroman/Invoke-Build#121]
I feel like I may have missed it somewhere, but is it possible to skip tasks programatically?

As an example, I have a Deploy Supertask that includes PreCheck and GitHubReleasePublic. I want that if the PreCheck identifies a certain condition (such as not finding the API key), to skip the GitHubReleasePublic task, but don't fail the build.

Is this possible or should I do the check in advance before calling Invoke Build and call it using a different task?

**Comment by nightroman** [comment]
It sounds like you need something like this

```powershell
$doGitHubReleasePublic = $true

task Deploy PreCheck, GitHubReleasePublic

task PreCheck {
    $script:doGitHubReleasePublic = $false
}

task GitHubReleasePublic -If {$doGitHubReleasePublic} {
    "Doing GitHubReleasePublic..."
}
```

If we run the above script we get `GitHubReleasePublic` skipped:

```
    Build Deploy C:\tmp\_180309_032658_ib_121\.build.ps1
    Task /Deploy/PreCheck
    Done /Deploy/PreCheck 00:00:00.0090174
>   Task /Deploy/GitHubReleasePublic skipped.
    Done /Deploy 00:00:00.0330429
    Build succeeded. 2 tasks, 0 errors, 0 warnings 00:00:00.2611698
```

If we comment out the line `$script:doGitHubReleasePublic = $false` in `PreCheck` and run again then:

```
    Build Deploy C:\tmp\_180309_032658_ib_121\.build.ps1
    Task /Deploy/PreCheck
    Done /Deploy/PreCheck 00:00:00.0095672
>   Task /Deploy/GitHubReleasePublic
>   Doing GitHubReleasePublic...
>   Done /Deploy/GitHubReleasePublic 00:00:00.0030305
    Done /Deploy 00:00:00.0356826
    Build succeeded. 3 tasks, 0 errors, 0 warnings 00:00:00.2599215
```

**Comment by JustinGrote** [comment]
Yes, the special $do<task> variables is exactly what I was looking for! Are
these in the wiki or docs? If not I'll add them. Thanks!

**Comment by nightroman** [comment]
A special variable is only one possible way of dealing with conditional tasks.
The concept of conditional tasks is described in help and wiki, I believe.

Wiki: [Conditional tasks](https://github.com/nightroman/Invoke-Build/wiki/Script-Tutorial#conditional-tasks)

Help:

```
. invoke-build
help task -parameter if
```

**Comment by JustinGrote** [comment]
I totally missed the -if parameter part. I have a solution, thank you and closing.
