### ISSUE TITLE
Introduce `remove`, the helper for cleaning temporary build items

### ISSUE THREAD

**Issue by nightroman** [nightroman/Invoke-Build#123]
Build scripts often produce temporary files and folders and require commands like

```powershell
Remove-Item X, Y -Recurse -Force -ErrorAction Ignore
```

What's wrong with the above command? It is verbose. And it has a flaw. If X
cannot be removed (locked files, permissions, etc.) the command ignores it.
If this is not desired, we should remove `-ErrorAction Ignore`. But then
the command also fails on missing items. Thus, we should use `Test-Path`
in addition and the simple frequent task becomes not so simple.

**TODO**

Introduce a straightforward helper `remove`, so that the above frequent
operation can be invoked as

```powershell
remove X, Y
```

UPDATE: Using `Test-Path` is not that simple, too, see https://github.com/PowerShell/PowerShell/issues/6473
Thus, the proposed robust helper dealing with the issues would be really nice.

**Comment by nsartor** [comment]
I like this idea, and often use remove-item in my scripts.
Would this take a collection of objects as an argument? Could we pass a collection from get-childItem for example?

**Comment by nsartor** [comment]
I don't think I'd need the output pipelined, but some way to check success or failure would be great:
Try{
(get-childItem some_path -recurse -filter *.tmp) | IB_Remove
}
Catch {
exit 1
}

**Comment by nightroman** [comment]
For the moment I am not planning this. The command is going to be dumb simple, at least its first version. It removes items with given names in the current directory and subdirectories, normally it is the build root. `remove` is not the replacement for `Remove-Item`. If you feel like `remove` is not enough for something then just use `Remove-Item` as usual.

**Comment by nsartor** [comment]
Ah ok. I won't be able to use it without any sort of logging/output to know of success or failure, but it might be useful to others. :)

**Comment by nightroman** [comment]
You will be able to catch errors, endeed. The command is going to write errors as usual if it cannot remove something. But if it does not find something this is not an error.

**Comment by nightroman** [comment]
Here is the prototype, you may start playing and giving some feedback

```powershell
function Remove-BuildItem([Parameter(Mandatory=1)][string[]]$Name) {
	if ($Name -eq '*') {*Die '* is not allowed.' 5}
	(Get-ChildItem -Include $Name -Force -Recurse) |
	.{process{if (Test-Path $_.FullName) {$_}}} |
	Remove-Item -Force -Recurse
}
```

**Comment by nightroman** [comment]
Here is some tests: https://github.com/nightroman/Invoke-Build/blob/180321-remove/Tests/Remove.test.ps1

The task `ErrorLockedFile` shows terminating and non-terminating errors at your service.

**Comment by nightroman** [comment]
I have several doubts about the first version and I am thinking of the alternative approach

```powershell
foreach($_ in $Path) {
    if (Test-Path $_) {
        Remove-Item $_ -Force -Recurse
    }
}
```

So that `remove ...` is similar to the mouthful `Remove-Item ... -Force -Recurse -ErrorAction Ignore`,
that is it removes existing items and ignores missing items. And at the same time:

- it is short and clear
- it fails if it cannot remove existing items, the important difference

**Comment by nightroman** [comment]
Turns out `Test-Path *\X` when X is hidden gets false. So the original task of removing items is even less simple.

TODO: Investigate further and submit an issue to PowerShell.
DONE: Worked around this issue in `remove`. Added the test `task HiddenInSubdirectory`.

**Comment by nightroman** [comment]
v5.3.0

**Comment by majkinetor** [comment]
It would be good to oput what is done or not done ? Maybe with `-Verbose` ?

**Comment by nightroman** [comment]
Maybe. Like this, perhaps?

```powershell
function Remove-BuildItem([Parameter(Mandatory=1)][string[]]$Path) {
	if ($Path -match '^[.*/\\]*$') {*Die 'Not allowed paths.' 5}
	$v = $PSBoundParameters['Verbose']
	try {
		foreach($_ in $Path) {
			if (Get-Item $_ -Force -ErrorAction 0) {
				if ($v) {Write-Verbose "remove: removing '$_'." -Verbose}
				Remove-Item $_ -Force -Recurse
			}
			elseif ($v) {
				Write-Verbose "remove: skipping '$_'." -Verbose
			}
		}
	}
	catch {
		*Die $_
	}
}
```

**Comment by majkinetor** [comment]
LGTM

**Comment by nightroman** [comment]
I opened a separate issue.
