### ISSUE TITLE
Q: Contribution: how do you build the Module?

### ISSUE THREAD

**Issue by schittli** [nightroman/Invoke-Build#124]
`My PSVersion: 5.1.16299.98`

Good morning
I am thinking about contributing to the project and now, I try to build the InvokeBuild Module to debug & test it. If I start `.build.ps1`, then I get
```
task : The term 'task' is not recognized as the name of a cmdlet, function, script file, 
or operable program. Check the spelling of the name, or if a path
was included, verify that the path is correct and try again.
```
If I start `Invoke-Build.ps1`
```
C:\GitWork\Clones\GitHub\¬Tom\Invoke-Build\Invoke-Build.ps1 : The term '*' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, 
or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ .\Invoke-Build.ps1
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-Build.ps1], Exception
    + FullyQualifiedErrorId : Invoke-Build.ps1
```
Therefore my question:
how do you build the InvokeBuild Module?

Thanks a lot for any help, kind regards,
Thomas

**Comment by nightroman** [comment]
Hi Thomas!

The first error is expected, `.build.ps1` is not supposed to be invoked
directly (unless it is designed for this, see [Direct](https://github.com/nightroman/Invoke-Build/tree/master/Tasks/Direct)).

The second error is not clear, if you are interested in it please give more details.

How to develop. You do not have to build a module. Clone the repo, include its
directory to the path and you are basically done. You have your `Invoke-Build`
command available as the script in the path. Make changes to `Invoke-Build.ps1`,
save, see how changes work immediately.

For some particular operations you may need some tools. Most of them are
mentioned in the comments of the main `.build.ps1`. Please do not hesitate
to ask questions if something is not clear.

I am glad that you are interested in contributing. You are welcome to discuss
your ideas. Please note that the tool is feature complete, and new features are
not necessarily needed (there may be a different way of doing something or a
new feature may be considered redundant, out of the main scope, etc.).

**Comment by nightroman** [comment]
I am closing this question as answered.
