### ISSUE TITLE
 Invoke-Build is verbose by default - is it possible do suppress "Done /…" Messages?

### ISSUE THREAD

**Issue by schittli** [nightroman/Invoke-Build#125]
Good morning

### Thank you very much
for this great and very useful Module! after some training, it makes fun to use invoke-Build. And the fun is useful, too :-)

### For us, the `"Done /…"` Messages are only useful if we try to find slow tasks.
Otherwise, those Messages don't offer any needed information, for example, this information is sufficient for most daily usage (without the `"Done /…"` Messages):
```
Build Gitcommit C:\GitWork\…\…\…\jig.build.ps1         
Task /Gitcommit/LoadModuleManifest                                                               
* Loading the existing module manifest for this module                                           
Task /Gitcommit/VersionCheck                                                                     
* Validating manifest, build, and gallery module versions.                                       
Task /Gitcommit                                                                                  
[master 90ccfb5] Git Release Notes, Test 0140                                                    
 1 file changed, 3 insertions(+)                                                                 
```

### Therefore my question:
is it possible to disable the `"Done /…"` Messages?

### I've already started to implement a 'taciturn' switch, 
but this solution is the wrong way round: there should be a Verbose switch, which displays additional information, which is usually not used in the daily business :-)

Thank you for your feedback!

Kind regards, Thomas

**Comment by nightroman** [comment]
> is it possible to disable the "Done /…" Messages?

Currently, no. There is a way to alter task "headers". I can think of adding the similar support for custom "footers". In your case, you would define an empty one.

The switch solution does not look attractive to me. It pollutes IB parameters and adds a low value, just on/off of footers, no customization.

**Comment by schittli** [comment]
Hi Roman
Thank you very much for your review of my idea, your feedback, and your proposal!

Your proposal to have something similar to `Set-BuildHeader` is a perfect and therefore, I tried to create `Set-BuildFooter`.

I already created a Pull request, `Invoke-Build.ps1` works perfectly and creates the same result as the original :-), but for the other Files, I have asked some questions in the Pull request.

Kind regards,
Thomas

**Comment by nightroman** [comment]
Hi Thomas,

I merged your PR: https://github.com/nightroman/Invoke-Build/pull/126
You have done a great job, thank you!

I changed just a few things, see the branch "180401-footer"

- The default footer should be the same as before, including colors. It worked
  this way for several years and nobody complained. Let's keep it not changed.
- Restored one old message "Done ...". This is not a task footer but a message
  about already done task. There are other special messages (skipped tasks,
  duplicated tasks, incremental messages about out-of-date or up-to-date).
  These special messages are not customizable. Too many options is not good.
  `Set-BuildFooter` is needed and expected as the pair of `Set-BuildHeader`.
- Removed "Tasks/Footer" and "Footer.test.ps1". Instead added new footer stuff to
  existing "Tasks/Header" and "Header.test.ps1". They are a pair and one sample
  and test for both is probably fine. Besides, not many people will use any of
  them, I think.

I will merge this branch after some tests and tweaks and then release this.

**Comment by nightroman** [comment]
v5.4.0

**Comment by schittli** [comment]
Good evening Roman
Thank you very much for your support, explanations, merge, tests and the release!
It was similar to the reading a manual: _After I have understood the software, I also understand the manual._
As I can see your corrections, I understand the concepts of Invoke-Build :-)

By the way: I would have bet that you are a C++ programmer: The PowerShell Module Invoke-Build has so many `*` that the heart of every C++ developer would beat faster ;-)

Thanks for all,
kind regards,
Thomas

**Comment by nightroman** [comment]
> I would have bet that you are a C++ programmer: The PowerShell Module Invoke-Build has so many * that the heart of every C++ developer would beat faster ;-)

Ha-ha, now I see this, too. I use C++ occasionally. Currently, I mostly program in F#.
The reason for choosing `*` in names is to avoid potential clashes with user-defined names.
