### ISSUE TITLE
Parallel builds fail, when others don't

### ISSUE THREAD

**Issue by nsartor** [nightroman/Invoke-Build#128]
(Note: this might be an issue with npm and not invoke-build.)

I have a zip attached that includes 3 build files, and 2 package.json files. You'll need to install node.js to test this.

The main build (fail.build.ps1) has 2 tasks in it; default and parallel.

If you call `invoke-build default` it runs each of the child builds with no issues. However, if you call` invoke-build parallel`, the build fails.

The failure happens on an npm warning:
`ERROR: npm WARN TESTING@1.0.0 No description`
Whereas when doing a build not in parallel, the warning is not treated as an error.

Is this an issue in npm, or invoke-build? 

Thank you for looking!

[build.zip](https://github.com/nightroman/Invoke-Build/files/1907450/build.zip)

**Comment by nightroman** [comment]
I am not familiar with `npm`. Maybe it is not supposed to work in parallel *in the same console*. For example, on `npm install` I can see some sort of progress info written to the console. Maybe it's the reason. I do not think Invoke-Build is responsible for this unfortunate limitation or we can change something.

**Comment by nightroman** [comment]
But it's a hint. If you know how to tell `npm` to suppress this info written to the console then try to engage this and see if it helps.

**Comment by nsartor** [comment]
Thanks @nightroman There is a way to have npm log errors only `npm --loglevel error` and I believe that's going to work.
It was just a bit strange that ib outputs the "WARN" as an error, but I think it's an npm thing. There's a few conversations on stackoverflow about npm logging all output to stderr. I'm not sure why they would do that.

Thanks for responding!

**Comment by nightroman** [comment]
@nsartor 
It's very good that you mentioned stderr because then I know a workaround. On `exec` use error preference ignore, e.g:

```powershell
exec { npm install } -ea 0
```

**Comment by nsartor** [comment]
thank you! I'll keep that in mind. npm is certainly doing weird stuff with its output. The --loglevel error fixed it for npm, but I may need it in the future. Thanks again!

**Comment by nightroman** [comment]
Yes, the trick is relevant for all apps with stderr when used in PowerShell.
