### ISSUE TITLE
Vs2017 and MS Build compliance

### ISSUE THREAD

**Issue by okproject** [nightroman/Invoke-Build#129]
Hi
I remember that Pake has problems with VS2017 and MSBuild versions.
One day I updated my visual studio from 2015 to 2017; then boom. Pake build is not work ...
I am researching a new solution because of that.

Is invoke-build has any problem with any ms build or visual studio version ? Will I need change something in windows registry to use Invoke-Build ?

Thanks.

**Comment by okproject** [comment]
Thanks for quick answer.

**Comment by nightroman** [comment]
No problem. I hope you will find the tool useful. Happy building!
