### ISSUE TITLE
New-VSCodeTask on PS Core. If tasks.json is already there it is not replaced.

### ISSUE THREAD

**Issue by larssb** [nightroman/Invoke-Build#130]
So I tried to use New-VSCodeTask to generate a tasks.json task file for VS Code. However, if there is already a tasks.json file in the .vscode folder the file is not replaced.

**System**

- MacOS v10.13.5 beta
- PowerShell Core:

```
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.2
PSEdition                      Core
GitCommitId                    v6.1.0-preview.2
OS                             Darwin 17.6.0 Darwin Kernel Version 17.6.0: Fri Apr 13 19:57:44 PDT 2018; root:xnu-4570.60.17.0.1~3/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

InvokeBuild v. 5.4.1

***Troubleshooting***

- Updated to the latest ver. of InvokeBuild. **No improvement.**
- Tried as root. **No improvement.**
- Deleted the 'old' tasks.json file. **That works, now New-VSCodeTask successfully creates a new tasks.json file.**

-----

Seems like a something is rotten.

Thank you.

**Comment by nightroman** [comment]
What is the version of `New-VSCodeTask`?

It is supposed to delete the file and ask for confirmation. Maybe this part is not working on PS.Core...

**Comment by nightroman** [comment]
It works as expected (asks to delete the existing *non-generated* file) on PS Core on Windows.
Something is wrong with PS Core on MacOS v10.13.5 beta perhaps.

**Comment by nightroman** [comment]
I only work on Windows and cannot investigate further. If it is a bug there, an issue should be opened. If it is confirmed then we may think of a workaround for a particular case (or wait for a fix).

**Comment by nightroman** [comment]
Another idea. Can you try to add `-Force` after `-Confirm`?

    	if ($line1 -ne $Header) {Remove-Item ./.vscode/tasks.json -Confirm}

**Comment by nightroman** [comment]
Sorry, I was a little bit mislead by Core and MacOS. The bug was simpler and hopefully fixed in v1.1.7 of the script. Pushed to the repo and PSGallery.

**Comment by larssb** [comment]
Hi @nightroman,

Thank you very much for looking at this. It works now. I had a look at the code. Allow me to run you through my findings.

From what I can conclude, and please correct me if I'm wrong, it now works in the case of an existing tasks.json file because this line of code: `Set-Content ./.vscode/tasks.json $out.ToString() -Encoding UTF8` **IS** reached. The reason why it is reached, to me, seems to be, because this line of code: `if (Test-Path ./.vscode/tasks.json) {return}` is **NOT** reached.
Because this conditional control `if ($line1 -ne $Header) {`, as long as one has **NOT** mangled with the file will always resolve to `$false`. This "protects" us from reaching `if (Test-Path ./.vscode/tasks.json) {return}` where the `return` statement will result in an exit from the function and thereby us **NOT** reaching the `Set-Content.....` line.
I tested the above theory by just copying the "old" 1.1.6 from the InvokeBuild repo, from an earlier commit. Executed it, in the case of having a tasks.json file already. Things did not work....as expected. Then I removed the `return` statement in the line: `if (Test-Path ./.vscode/tasks.json) {return}` and just had a `write-host "fine fine"` line there, instead of the return statement.

1. To confirm that the line is reached.
2. Two to see it it now works. _It did_. So by removing the return statement in the the `if (Test-Path ./.vscode/tasks.json) {return}` line, which in v1.1.6 is outside the `if ($line1 -ne $Header) {` conditional block. The `Set-Content....` line is reached.

**_Based on the above finding, allow me to suggest:_** 

Simply removing the below lines from the Script. Using the Set-Content cmdlet allows that. As it will replace the contents of the file if it exists, if it does not, a new tasks.json file will be written. Everybody is happy 👍.

```
elseif (Test-Path ./.vscode/tasks.json) {
	$line1 = switch -file ./.vscode/tasks.json {default {$_; break}}
	if ($line1 -ne $Header) {Remove-Item ./.vscode/tasks.json -Confirm}
	if (Test-Path ./.vscode/tasks.json) { write-host "fine fine" }
}
```
I will happily do a pull request if you find the above suggestion positive. Thank you.

**Comment by nightroman** [comment]
Your understanding is correct.

If we remove that lines we will get the old code (before 1.1.6) which overrides any file. It will work indeed. But I want to have a confirmation on overriding a file which was not *generated* before by this tool.

**Comment by nightroman** [comment]
Just to be clear. If something is still wrong please tell what.

**Comment by larssb** [comment]
Hi @nightroman,

Ah yes, of course. I didn't think of scenarios where InvokeBuild's New-VSCodeTask cmdlet had not been used. Of course those scenarios exists.
My bad. Everything works as expected now, in v1.1.7. Thank you very much.
:+1:
