### ISSUE TITLE
Parameter for a task

### ISSUE THREAD

**Issue by artkpv** [nightroman/Invoke-Build#131]
Hi and thanks for the cool tool (imho better than psake)!

How can I pass a parameter to some one task? I'd pass name of xunit test method but putting it in `param` in main script looks too extensive as only this task needs this. Would `property` work here?

In my `.\run.ps1`:
``` powershell
	Invoke-Build @args -File .\scripts\build.ps1 
```

In `.\scripts\build.ps1`:
``` powershell
param ($test = $null)   # works but need to put arguments of a task for a whole script
Task Test {
	$xunit = (resolve-path ".\tools\xunit.runner.console.*\tools\net452\xunit.console.exe")
	$assemblies = (ls ..\src\**\bin\$configuration\*.Tests.dll)
	$xunitArgs = "-xml", "$artifactsDir\UnitTestResults.xml" , `
			"-html", "$artifactsDir\UnitTestResults.html"
	$test = (property test "")                # <-----------       A try to make it. Doesn't work.
	if ($test){ $xunitArgs += "-namespace", "`"$test`"" }
	exec { & $xunit $assemblies $xunitArgs } 
}
```

**Comment by nightroman** [comment]
>  `# <-----------       A try to make it. Doesn't work.`

Probably because you still use `$test` as a parameter and it is the default `$null`.

In order to use `property`, you should:

- choose a name which does not conflict with anything else, e.g. `MyTaskProperty`
- before calling the build, set it: `$MyTaskProperty = ...; Invoke-Build ...`
- in a task, get it: `... = property MyTaskProperty`

**Comment by artkpv** [comment]
I've changed it actually to use this structure: https://github.com/nightroman/Invoke-Build/blob/master/Tasks/Direct/build.ps1 . But nevertheless params should be defined for a whole script even if I want it only for one task:
```
> .\run.ps1 buildcore -asdfsd asdfsdf
run.ps1 : A parameter cannot be found that matches parameter name 'asdfsd'.
```
Looks like no simple way. Tasks are not separable from the script.

**Comment by nightroman** [comment]
*Parameters* for tasks are not planned and probably will not be. Compare with MSBuild, there is not a parameter for a target. Parameters are for the whole script.

But you can use *properties* specific for tasks, as I described. If you call from PS just set them as extra variables before invoking. If you call from CMD, use environment variables instead.

**Comment by nightroman** [comment]
And after all, I do not think if it is a big problem if a script has a parameter used by a single task.
