### ISSUE TITLE
Dot sourcing in a build fails until it is done manually, then works?

### ISSUE THREAD

**Issue by NReilingh** [nightroman/Invoke-Build#133]
I am working on a project to create a PowerShell DSC configuration, and am using Invoke-Build to automate a couple of processes for testing this configuration locally.

The relevant part of my build script is:

```powershell
# Synopsis: Dot-sources the DSC configuration
task SourceConfiguration {
    . .\Tessitura.ps1
}

# Synopsis: Generates MOS files in the Build directory.
task GenerateMOF Clean, SourceConfiguration, {
    Tessitura -ConfigurationData .\LocalhostIIS.psd1 -OutputPath $Build
}
```

The basic idea is that `Tessitura.ps1` contains a DSC Configuration named `Tessitura`, and by dot-sourcing this file, the `Tessitura` configuration should then be available in the current session to be called as it is in `GenerateMOF`.

When I run the GenerateMOF task in a new PowerShell session, it fails on GenerateMOF with the standard "The term 'Tessitura' is not recognized as the name of a cmdlet..." It appears to complete the SourceConfiguration task dependency successfully.

However, the weird thing is that if I manually dot-source  the `Tessitura.ps1` file in the same terminal session before running Invoke-Build, everything thereafter works fine. Even changes made to `Tessitura.ps1` between consecutive runs will take effect for the GenerateMOF task.

So, it seems like the SourceConfiguration task isn't allowed to create a configuration in the scope that GenerateMOF is run in, but if the configuration already exists, it is allowed to overwrite it. Is there anything I can do to avoid this issue?

**Comment by nightroman** [comment]
> So, it seems like the SourceConfiguration task isn't allowed

Yes, I afraid it is not "allowed" to dot-source to the scope of another task.
Dot-sourcing imports stuff to the current scope, that's how PowerShell works.
It's not about Invoke-Build as such.

What you can do.

(1) Remove the task `SourceConfiguration` and dot-source your script right in `GenerateMOF`.
If there are more tasks like `GenerateMOF` then dot-source in each.

(2) If you do not like dot-sourcing in many tasks then dot-source right in the script scope,
anywhere in the script, e.g. before the first task. Ideally inside `EnterBuild {...}` block.

**Comment by nightroman** [comment]
> Even changes made to Tessitura.ps1 between consecutive runs will take effect for the GenerateMOF task.

It's the details of the implementation. But this requirement might require the scenario (2). I do not know all the details, just guessing.

**Comment by NReilingh** [comment]
Thanks for the clarification! Useful to know that Enter-Build executes in the script scope. I moved my dot-sourcing there and things appear to be working as desired.
