### ISSUE TITLE
Command-line parameter to skip dependent tasks

### ISSUE THREAD

**Issue by nikoudel** [nightroman/Invoke-Build#138]
I've just started using Invoke-Build and it looks really nice!

One of the first things I found missing is an easy way to skip task dependencies with a command-line parameter. Is it really so or should I have searched better?

The typical scenario is running a build and having one task failed. Now I want to adjust the system and re-run the failed task. I can't just run it though because the dependent tasks have already run and modified their part of the system so I just want to continue from the same point of the build by manually running tasks one by one. That's an ordinary debugging process which is common to pretty much any kind of development.

So is there some equivalent of FAKEs `--single-target` [parameter](https://fake.build/core-targets.html)? If there isn't yet, maybe it would be a good thing to implement?

**Comment by nightroman** [comment]
Hi @nikoudel

Thank you for the well explained suggestion. There is no such a parameter and
for the moment I am not sure it is needed. It is reasonable and useful in some
cases, yes. But "every new feature comes with a bonus -100". It's good to know
that FAKE has such a parameter. But MSBuild does not. And Invoke-Build follows
MSBuild's design in many ways.

What you can do.

(1) There is something developed exactly for your case, the persistent build.
See [wiki/Persistent-Builds](https://github.com/nightroman/Invoke-Build/wiki/Persistent-Builds).

Not every build may be persistent right away. But in most such cases your
suggested feature would not help, too. Some tasks really depend on others,
and cannot be invoked on their own, e.g. when referenced tasks set some
intermediate build variables and the task in question uses them.

NB You see, the suggested feature even not going to be useful in *all* cases.

(2) Temporarily (just for troubleshooting) or not (you think you may need this
again), redesign your troublesome task, for example, replace this:

```
task Troublesome Task1, Task2, {<code>}
```

with this

```
task DoTroublesome {<code>}

task Troublesome Task1, Task2, DoTroublesome
```

Now you can invoke/debug just `DoTroublesome`, exactly what you need.

**Comment by nightroman** [comment]
In fact, (2) is a very good and self documenting design. Even without comments
explaining why the task `DoTroublesome` is added, it's kind of clear that in
some cases it is supposed to and *can* be called on its own.

**Comment by nikoudel** [comment]
I'm doing some sort of (2), just commenting out the dependencies:

```
task Task3 {#Task1, Task2 {
  <code>
}
```

which works but is not that elegant because I have to go and edit the code twice. That's also not a good option for other groups of people who are not developers and don't want to touch the code - they'd just like to re-run that one task.

The actual problem with (2) is that usually I'm not anticipating any particular task to fail, that happens randomly. Especially during initial development.

I'll take a look at (1), thanks.

**Comment by nightroman** [comment]
Please try the script and let me know how it works. I think it does the trick
and therefore IB itself does not need the suggested feature.

I think the feature and the script are useful and at the same time a little bit
controversial because they violate integrity of builds. For the moment I am not
going to add this script to the package. But I can publish it as a sample tool
in the repository demo directory *Tasks* and/or mention it somewhere in wiki.

**Comment by nikoudel** [comment]
It works great, thanks!

**Comment by nightroman** [comment]
Very well, let me publish this script (one way or another, not yet sure) and then I will close the issue.

**Comment by nightroman** [comment]
The script [Build-JustTask.ps1](https://github.com/nightroman/Invoke-Build/blob/master/Build-JustTask.ps1) is simply added to the repository and mentioned in README.

**Comment by nikoudel** [comment]
Thanks for implementing it! Makes development process smoother.
