### ISSUE TITLE
Warning summary refers to dependent task instead of actual task

### ISSUE THREAD

**Issue by zzzz4** [nightroman/Invoke-Build#142]
task PreWarn { }
task Warn PreWarn, {
  Write-Warning "Warning from Warn task"
}

The build summary contains this:
WARNING: Warning from Warn task Task: **PreWarn**. File: (…)

**Comment by nightroman** [comment]
Thank you for the report, I can repro and I see why this happens. Will fix this soon.

**Comment by nightroman** [comment]
Fixed in 5.4.4
