### ISSUE TITLE
Write-Build -Color parameter isn't actually optional

### ISSUE THREAD

**Issue by NReilingh** [nightroman/Invoke-Build#144]
According to the help for `Write-Build`, `-Color` is not required. But if you attempt to call Write-Build without it, you get an exception: `Cannot convert null to type "System.ConsoleColor"`

```powershell
Write-Build -Text "Write output with default color"
```

Should it also be possible to omit the `-Text` label and infer the Text parameter from being a string type instead of a ConsoleColor enum value?

**Comment by nightroman** [comment]
`Write-Build` is designed for colored output, so color is mandatory (well, de facto). The help and signature should be probably amended, yes.

> Should it also be possible to omit the -Text label and infer the Text parameter from being a string type instead of a ConsoleColor enum value?

No... The color is mandatory. If you do not need the color then you do not need `Write-Build` in the first place. Just out text directly or by `Write-Output`, as some people prefer.

**Comment by NReilingh** [comment]
Aha, gotcha. I was trying to use it within an -Input {} block for debugging and it was being treated as paths, exactly as Write-Output would do. I think I did end up using Write-Host for that purpose, which was only temporary.

**Comment by nightroman** [comment]
Ah yes, and of course `Write-Build` is rather for tasks. It must not be used in functions and script blocks with other output. `Write-Host` may or may not work (its usual caveats).

**Comment by nightroman** [comment]
"Fixed" in 5.4.5. I amended the help, both parameters are documented as required. For the moment I am not changing the code (e.g. making parameters formally mandatory), for various reasons.
