### ISSUE TITLE
Continue Task on error

### ISSUE THREAD

**Issue by stefanstranger** [nightroman/Invoke-Build#145]
I create a Task which Updates a version number.

First it retrieves the version number from JSON file locally. 
Next it tries to retrieve the version number remotely (which should have the latest version)
Finally it updates the version number to a new version number.

But it fails on the initial run because there is no remote version number yet. But now my task fails and does not continue to the next command in the task.

Example:
```Powershell
task UpdateVersion {
$LocalVersion =  ((Get-Content -path c:\temp\foo.json) | ConvertFrom-JSON).Version
$RemoteVersion = exec {external command to retrieve version} #fails on initial call (is expected)

if ($RemoteVersion)
{
#Code to update Remote version
}
else {
#code to update Local version
}
}
```
How do I make sure the task commands continue when the Remote version retrieve step fails?

/Stefan

**Comment by gaelcolas** [comment]
You just need to make sure the exec does not throw a terminating error.
Whether that requires you to wrap it in a different process or something...

Also I'd probably use version as a parameter.

And most likely you'd benefit from using gitversion and semver as it's meaningful & deterministic.

**Comment by gaelcolas** [comment]
Here's what I use with ModuleBuilder: https://github.com/gaelcolas/SampleModule/blob/modulebuilder/.build/tasks/Build-Module.ModuleBuilder.build.ps1

**Comment by stefanstranger** [comment]
Hi @gaelcolas,

I solved it using try catch in the task. If the exec fails in the try I continue in the catch. 

Thanks for helping out here.

/Stefan

**Comment by nightroman** [comment]
Yes, try/catch does the trick in all such cases. In this particular case you may just do not use `exec` and after the command check for `$LastExitCode`, might be simpler.

**Comment by dueringa** [comment]
I have a bunch of tasks I want to execute, independent of each other (say make targets). I want the other tasks to continue building if one fails, but still I'd like to get the number of failed tasks in the end.

I implemented this using the (I guess) internal API, using `*Err`:

```powershell
# ... foreach($tar in $targets) task $tar { ...
try { exec { make CONFIG=$tar } }
catch { *Err $Task }
# ...
```

It doesn't feel quite right to use `*Err`, is there another way I don't see?

**Comment by nightroman** [comment]
Use "?" prefix on referencing tasks that allowed to fail.
Example:

```powershell
task do-not-care ?bad, {
	'in do-not-care'
}

task bad {
	throw 'oops'
}
```

```
Build do-not-care C:\tmp\.build.ps1
Task /do-not-care/?bad
ERROR: oops
At C:\tmp\.build.ps1:7 char:2
+     throw 'oops'
+     ~~~~~~~~~~~~
At C:\tmp\.build.ps1:6 char:1
+ task bad {
+ ~~~~~~~~~~
Task /do-not-care
in do-not-care
Done /do-not-care 00:00:00.0669999
Build completed with errors. 2 tasks, 1 errors, 0 warnings 00:00:00.3403203
```
