### ISSUE TITLE
Support `remove -Verbose`

### ISSUE THREAD

**Issue by nightroman** [nightroman/Invoke-Build#147]
It would be useful if `remove` supports `-Verbose` in order in order to print
messages about removing existing and skipping missing items specified by `Path`.

Suggested here: https://github.com/nightroman/Invoke-Build/issues/123#issuecomment-476188945

**Comment by majkinetor** [comment]
Maybe also add some protections there while you are at it ?

```ps1
$protected = $Env:WinDir, $Env:ProgramFiles, $Env:SystemDrive, ${Env:ProgramFiles(x86)}, $Env:USERPROFILE
$path = Normalize-Path....
if ($path -in $protected) { throw "Protected directory not cleaned: $path"}
```

Its very easy to clean wrong things if you add variables in paths...

**Comment by nightroman** [comment]
Hmm... I think it's too much and not a common practice (`Remove-Item` is happy to kill whatever). The most typical scenario is using relative paths, I added some sanity checks for it (bare dots, asterisks, slashes).

**Comment by nightroman** [comment]
v5.4.6
