### ISSUE TITLE
Resolve-MSBuild no longer locates '15.0 x86'

### ISSUE THREAD

**Issue by paddyclark** [nightroman/Invoke-Build#148]
In previous versions MSBuild 15.0 x86 was located at 

C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe

The current version of Resolve-MSBuild (1.4.0)  reports "The specified version is not found."

**Comment by nightroman** [comment]
Hmm. I cannot reproduce. Let's try to figure out what wrong is. (1) Does `MSBuild.exe` exist where expected?

**Comment by paddyclark** [comment]
1. Yes
2. I don't believe so
3. Working (1.3.0): 
```
.\Resolve-MSBuild.ps1 "15.0 x86"

C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe
```
4. Not Working (1.4.0)
```
.\Resolve-MSBuild.ps1 "15.0 x86"

Resolve-MSBuild.ps1 : Cannot resolve MSBuild 15.0  : The specified version is not found.
At line:1 char:1
+ .\Resolve-MSBuild.ps1 "15.0 x86"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException    
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Resolve-MSBuild.ps1
```

**Comment by nightroman** [comment]
.\Resolve-MSBuild.ps1 "15.0 x86"

The version is not quite right, there must be no space in it, i.e. just use `15.0 x86`
I wounder why it worked before, maybe I should perform better validation.

**Comment by paddyclark** [comment]
You're right.  Using 15.0x86 works for both versions.

**Comment by nightroman** [comment]
Good! Please keep this issue open for now. I'll think of some better version validation.

**Comment by nightroman** [comment]
Invoke-Build v5.5.1
Resolve-MSBuild 1.4.1
FWIW, spaces like in the problem case are allowed.
