### ISSUE TITLE
Determine if & which MSBuild has been previously defined

### ISSUE THREAD

**Issue by nsartor** [nightroman/Invoke-Build#149]
Hello, is there a way to determine if "use 15.0 MSBuild" has been defined previously? I have some build files that need to use a specific version of msbuild, but in my "common code" i have a default value set.

So is there a way to do something like this in my common code:
```
if (!$msbuild) {
  use 15.0 MSBuild
}
```
Thanks in advance!

**Comment by nightroman** [comment]
This may be done in several ways. I would use `Resolve-MSBuild` instead of `use` (`use` is not deprecated but kind of legacy).

The shortest way. In the build script scope, do:

```powershell
Set-Alias MSBuild (Resolve-MSBuild *)
Set-Alias MSBuild15 (Resolve-MSBuild 15.0)
```

Then use `MSBuild15` instead of `MSBuild` where exactly v15 is needed.

For version checks, having set `Set-Alias MSBuild (Resolve-MSBuild *)`, you can get its version as

```powershell
(Get-Item (Get-Alias MSBuild).Definition).VersionInfo.FileVersionRaw.Major
```

**Comment by nightroman** [comment]
Alternatively, you can just use `use 15.0 MSBuild` right in a task which requires v15.
The alias is created locally for this task only, the parent alias, if any, stays.

```powershell
# Latest
use * MSBuild

# Use 15.0
task build15 {
    use 15.0 MSBuild
    Write-Build Yellow (MSBuild /version /nologo)
}

# Use Latest
task buildLatest {
    Write-Build Yellow (MSBuild /version /nologo)
}

task . build15, buildLatest
```

**Comment by nightroman** [comment]
And finally here is the version with variables

```powershell
# latest
$MSBuild = Resolve-MSBuild

# define if not yet
if (!$MSBuild) {
	$MSBuild = Resolve-MSBuild
}

# use latest
Write-Host (& $MSBuild /version /nologo)

# redefine with specific version
if (!$MSBuild -or ((Get-Item $MSBuild).VersionInfo.FileVersionRaw.Major -ne 15)) {
	$MSBuild = Resolve-MSBuild 15.0
}

# use 15.0
Write-Host (& $MSBuild /version /nologo)
```

**Comment by nsartor** [comment]
@nightroman That is perfect,
`(Get-Item (Get-Alias MSBuild).Definition).VersionInfo.FileVersionRaw.Major`
Is just what I need. 

Thank you!
