### ISSUE TITLE
Exception Missing default script thrown when no task is specified 

### ISSUE THREAD

**Issue by DaveSenn** [nightroman/Invoke-Build#15]
Calling Invoke-Build without specifying a task throws the following exception:
*‘Missing default script.’*
I expected Invoke-Build would run the default task if no task is specified.

This is my build script:
```powershell
task Build {
	Write-Host "Build..."
}

task Clean {
	Write-Host "Clean..."
}

task . Build, Clean
```

And this is how I start the script:
```powershell
.\packages\Invoke-Build\tools\Invoke-Build .\.build\Build.ps1
```

Why does Invoke-Build not run the default task?

**Comment by nightroman** [comment]
Take a look at the Invoke-Build syntax (help Invoke-Build):

> `Invoke-Build.ps1 [[-Task] <String[]>] [[-File] <String>] ...`

Note that `Task` is the first positional parameter and `File` is the second.

```powershell
.\packages\Invoke-Build\tools\Invoke-Build .\.build\Build.ps1
```

The above command specifies the task ".\.build\Build.ps1" and no build script. As a result, Invoke-Build looks for the default script in the current location and then in its parent directories. It is not found, hence the error. But even if it is found it would not work with the task ".\.build\Build.ps1".

You should either specify the parameter name `-File`:

```powershell
.\packages\Invoke-Build\tools\Invoke-Build -File .\.build\Build.ps1
```

or specify the default task explicitly as the first positional parameter, as the syntax requires:

```powershell
.\packages\Invoke-Build\tools\Invoke-Build . .\.build\Build.ps1
```

**Comment by nightroman** [comment]
By the way, your script *Build.ps1* will not be recognized as the default even if it is in the current directory. By the convention it should be either named `.build.ps1` or `something.build.ps1`. In the latter case it also should be the only like `*.build.ps1` in its directory.

**Comment by nightroman** [comment]
If there are no more questions or related issues please close the issue.

**Comment by DaveSenn** [comment]
Sorry had no time to check you answer until now.
Thank you very much for your answer. 
Specifying the name of the parameter works perfectly.
