### ISSUE TITLE
Build-Checkpoint file should not be deleted

### ISSUE THREAD

**Issue by lzybkr** [nightroman/Invoke-Build#150]
Sometimes my build doesn't go as expected, but it appears to succeed and the checkpoint file is deleted.

The file format isn't friendly to recreate, maybe impossible for some builds.

It would be nice, maybe as an option, to not delete the file so I can at least manually edit the tasks and force a more minimal rebuild.

**Comment by nightroman** [comment]
Let me think about this. Meantime, may [Build-JustTask.ps1](https://github.com/nightroman/Invoke-Build/blob/master/Build-JustTask.ps1) help? It was created for solving similar issues after discussing https://github.com/nightroman/Invoke-Build/issues/138

**Comment by nightroman** [comment]
I have added the switch `Preserve`, see the above branch if you want to try.
I'll release this change after some more testing.
