### ISSUE TITLE
Suggestion: -After * / -Before *

### ISSUE THREAD

**Issue by fdcastel** [nightroman/Invoke-Build#151]
There is a way to make a task run before/after each ANY task ?

If not, what about?

```powershell
task TestInitialize -Before * {
    Write-Host '@TestInitialize '
}

task TestCleanup -After * {
    Write-Host '@TestCleanup '
}
```

It would be useful in tests, for example.

**Comment by nsartor** [comment]
I'm not the project maintainer, but I know tasks can only be ran once.
In this case, you'd want to use a function, and call it from the dependent task 

You could also use enter-BuildTask,but that, as far as I know, won't filter.

**Comment by fdcastel** [comment]
> (...) but I know tasks can only be ran once.

Uh... **VERY** good point, @nsartor. Well noted. 

My suggestion as it is would break a basic tenet from Invoke-Build. Not good.

Yet, any test framework out there and its dog have a Setup/Teardown method. It would be a nice feature for Invoke-Build.



> you'd want to use a function, and call it from the dependent task

Sure. I'm already doing this. But I have a lot of test cases and I'm looking for a way to avoid the code repetition (DRY is calling).

**Comment by nsartor** [comment]
No problem. I can see where this might be useful.

Here's what I do:
For setup I use the "enter-build" task in my build scripts. For teardown there is of course "exit-build", however, a try catch is what I ended up with. I would try my task, catch the failure and call a function. That function does some cleaning up and then throws the original error.

Hope this helps!

**Comment by fdcastel** [comment]
Sorry, @nsartor. Somehow I completely failed to see your `Enter-BuildTask` comment on first reply. 🤦‍♂ 

Actually this is *exactly* what I need! 🙌 

Sample usage:
https://github.com/nightroman/Invoke-Build/blob/master/Tests/Events.test.ps1#L35

Thank you very much!

**Comment by nightroman** [comment]
@fdcastel I think `Enter-BuildTask` does the trick as such. I am not sure about your example though. You change the location but IB is designed to set it to `$BuildRoot` anyway. Or not?

**Comment by nightroman** [comment]
LOL, it's my test script! Yes, it's a good example of Enter/Exit scripts.
So, is the problem solved? Closing?

**Comment by fdcastel** [comment]
The sincerest form of flattery! 👍 😄 

Yes. Problem solved. I was just waiting other opinions, if any.

Thank you very much @nsartor for the and guidance @nightroman for the fantastic work!
