### ISSUE TITLE
There is no migration flow documented or installed for psake users

### ISSUE THREAD

**Issue by ssg** [nightroman/Invoke-Build#155]
I understand that `Convert-psake` helps in converting files but it's completely unknown for a user how they should approach installing it. It's probably "just clone the repository and run it from there" as it is a one time thing but I find carrying along a whole repository for supportive tooling not ideal. 

I instinctively tried `Install-Module Invoke-Build` and assumed it would install support tools too, it didn't.

Regardless, I wish it was at least documented.

**Comment by nightroman** [comment]
You do not have to clone the repository. Just download the script and run it locally.
Documentation is in the script. How/where/what else should be documented, in your opinion?

**Comment by ssg** [comment]
"Just download the script" is ambiguous but much better than not knowing what to do at all. I didn't even know if I was supposed to download it myself or if it came with the installed module (that's why I tried it with the module). I had to guess how to access the script. It's in the same folder with many other scripts, does it depend on any of them? I have to guess that it doesn't. There is no download link at https://github.com/nightroman/Invoke-Build/blob/master/Convert-psake.ps1 . There is the "Raw" link but it opens in the browser. Do I copy paste it to a text editor? What about encoding differences or errors when applying it? I need to guess the answers to these too. I know the target user base is power users (developers) but I feel like a guide with simple instructions would have made tremendous difference, rather than trying to guess everything.

I'd expect something along the lines of:

# Migration for psake users
- Download the conversion script at https://raw.githubusercontent.com/nightroman/Invoke-Build/master/Convert-psake.ps1
(I know you already document the rest, just for the completeness' sake)
- Run the conversion script on your build file: 
  ```powershell
  \scriptfolder\Convert-psake mypsakescript.ps1 | Set-Content .build.ps1
  ```
- Open the `.build.ps1` file in a text editor.
- Edit out the TODO sections.
- Voila!

**Comment by nightroman** [comment]
@ssg Thank you. Fair complain, good suggestions. I'll think about this and probably create a wiki page and add links to README and the script.

**Comment by nightroman** [comment]
I've done this:

- added wiki page https://github.com/nightroman/Invoke-Build/wiki/Convert~psake
- added links to README and the script

Let me know if it looks good or anything else is needed.
Feel free to reopen with new suggestions. Thank you for your report.

**Comment by ssg** [comment]
Awesome, thanks!
