### ISSUE TITLE
Unexpected Output for Write-Build

### ISSUE THREAD

**Issue by sheldonhull** [nightroman/Invoke-Build#157]
I'm getting a lot of this type of message in my log when using `Write-Build`. 

```
WARNING: Unexpected output: BuildRoot: C:\Users\me\git\projname.
```

I've looked at the source code, but it's not very clear to me what might be triggering this. 

This is the first two lines of the build file, as I have the `build.tasks.ps1` nested in a `build` folder. This just moves the `$BuildRoot` back to the project directory to keep things straightforward for my portable build folder. 

```
$BuildRoot = $BuildRoot | Split-Path -Parent
Write-Build DarkGray "BuildRoot: $BuildRoot"
```

Any ideas? I can try a breakpoint and enter debugging on this, but figured I'd reach out first in case there's a clear reason why this might be happening. It's occurring in many of my build scripts right now.

**Comment by nightroman** [comment]
Your script contains some code at the top level (outside the tasks) with output.
Example:

```powershell
'some code with output'

task task1 {
}
```

```
WARNING: Unexpected output: some code with output.
Build task1 ...\.build.ps1
Task /task1
Done /task1 00:00:00.0179740
WARNING: Unexpected output: some code with output. File: ...\.build.ps1.
Build succeeded with warnings. 1 tasks, 0 errors, 1 warnings 00:00:00.2959980
```

Suppress this output using the usual techniques like `.. | out-null`, `$null = ...`
Or, if the output is required, wrap your top level code with `Enter-Build`:

```powershell
Enter-Build {
    'some code with output'
}

task task1 {
}
```

```
Build task1 ...\.build.ps1
some code with output
Task /task1
Done /task1 00:00:00.0170014
Build succeeded. 1 tasks, 0 errors, 0 warnings 00:00:00.2859720
```

**Comment by sheldonhull** [comment]
Thanks for this! I guess I had some set of environment variables at top as when I set them in `Enter-Build` they weren't ready for the tasks that depended on them. 

If I want to use "-requires` for a task, and I load those task files from directory, `Enter-Build` isn't going to recognize them i think?

I'm going to try and reorder and see what difference this makes and update this issue in case someone else needs this in the future

**Comment by sheldonhull** [comment]
I just moved all that into `Enter-Build` and it fails with: 
```
ERROR: Task 'StartBuild': Missing task 'powershell_load_required_modules'.
```
The job definitions seem to validate before they enter-build. Going to try moving the tasks loading outside `Enter-Build` and will just have to remove any `-Requires` for environment variables I think for it to pass that

**Comment by sheldonhull** [comment]
Ok, that resolves the output issue. So, if you want to have modular common tasks folder and certain one's require environment variable, on import those get checked it seems. This means if you are setting values dynamically in the `Enter-Build` you can't use that `-Requires`. 

Thanks for the help. This sure is making life much easier to coordinate locally and on my azuredevops agent 👍
