### ISSUE TITLE
Version of portable setup

### ISSUE THREAD

**Issue by majkinetor** [nightroman/Invoke-Build#159]
If I [copy](https://github.com/nightroman/Invoke-Build/wiki/Portable-Build-Scripts) Invoke-Build.ps1 to my repo and don't record the version, I will have to spend some time on it later by manually comparing it with historic versions.

I suggest to automate version update of the release in `Invoke-Build.ps1` script header comment.

**Comment by nightroman** [comment]
Yes, this makes sense.
Out of curiosity, what set of files do you usually copy?

**Comment by majkinetor** [comment]
I do it first time now, I only copied `invoke-build.ps1` as this is mostly intended for build server.

**Comment by nightroman** [comment]
So, just to be sure, the script in the package will start with something like:

```
<# Invoke-Build 5.5.7
Copyright (c) ...
```

Correct?

Note that I am going to update this line on packaging, not in the source script in the repository.

**Comment by majkinetor** [comment]
Great.

**Comment by nightroman** [comment]
OK then, will do this later today. Thank you for the suggestion.

**Comment by ChadMcCaffery** [comment]
@nightroman FYI.
I believe `New-ScriptFileInfo` and `Update-ScriptFileInfo` exist for versioning scripts, which would also make them compatible with `Install-Script` and `Update-Script` should someone want to publish to a common repository of sorts. (Granted, the comment format is a bit heavy-handed...)

**Comment by nightroman** [comment]
@ChadMcCaffery Thank you. Yes... The package already contains the whole *InvokeBuild.psd1* with standard `ModuleVersion`, just in case if one needs the version. The comment format is for the special scenario described by OP.

All in all, if users need something else and explain their needs, I will follow.
