### ISSUE TITLE
Package is not marked as a development dependency

### ISSUE THREAD

**Issue by shaynevanasperen** [nightroman/Invoke-Build#16]
When installing Invoke-Build into a .NET project using NuGet 3.1, it places the package entry into the project level packages.config file (because solution level packages are no longer supported). This causes NuGet to think that this is a runtime dependency of the package being built with Invoke-Build. This can be fixed by adding &lt;developmentDependency&gt;true&lt;/developmentDependency&gt; to the nuspec file.

Additionally, when I tried to do this myself I was unable to build a new package dues to missing files (Markdown.tasks.ps1, Helps.ps1 etc.). Please fix this so that others can also build a new package, or update the readme to explain how to build the package.

**Comment by nightroman** [comment]
Just to be sure, should I just add `<developmentDependency>true</developmentDependency>` to the nuspec and that's all?

**Comment by shaynevanasperen** [comment]
Yes, in the &lt;metadata&gt; secion, that's all.

**Comment by nightroman** [comment]
As for the second part of the request, here is [Helps](https://github.com/nightroman/Helps) and [Markdown.tasks.ps1](https://gist.github.com/nightroman/1303971). The latter also requires *MarkdownDeep*. This is not smooth and easy for everybody so the task of packaging is on me with not much details explained yet.

**Comment by nightroman** [comment]
> Yes, in the <metadata> secion, that's all.

No problem, will do shortly. The question though: could this be a regression in some other scenarious? You are more familiar with NuGet and package dependencies than me. What do you think?

**Comment by shaynevanasperen** [comment]
This is very unlikely to cause any regression.

**Comment by nightroman** [comment]
Done. The updated package v2.12.3 has been uploaded to the NuGet gallery.
