### ISSUE TITLE
How to redirect standard error?

### ISSUE THREAD

**Issue by benmishkanian** [nightroman/Invoke-Build#161]
I have a Python script that writes errors to stderr when run directly in Powershell on Windows. I put the script invocation in an exec call in an Invoke-Build task, and called Invoke-Build from Powershell. I can see the errors are correctly written to the console, but if I try to redirect the stderr of the Invoke-Build to a file, the errors stop writing to the console but the file is also blank. 

Example invocation:
`Invoke-Build -File buildScript.build.ps1 -Task myPythonTask 2> out.txt`

Am I doing something wrong? Where is the stderr going?

**Comment by nightroman** [comment]
Do you see the same issue without Invoke-Build, i.e. with normal PowerShell script calling Python? I am not trying to say Invoke-Build is not responsible and it's not "my issue". I am trying to understand the problem better. I'd like to help even if this is a generic PowerShell issue.

**Comment by nightroman** [comment]
I have played with this (or similar) scenario. Yes, there are some issues.

**My ideas.** The root problem is in the way PowerShell handles stderr output
from apps. For some unknown reason it converts it to non-terminating PowerShell
errors (presumably). Invoke-Build cannot change this but it contributes to the
issues by `$ErrorActionPreference = 'Stop'`, i.e. making all errors terminating.

This is all not good. And the best solution may depend on a case. But this well
known work around may help in most cases. In a task before calling your Python
script, set

```powershell
$ErrorActionPreference = 'Continue'
```

Or, to make this change even more local:

```powershell
    &{
        $ErrorActionPreference = 'Continue'
        <call your app>
    }
```

This worked for me with `Invoke-Build ... 2> z.log`. Note that *z.log* contains
some sort of PowerShell errors, not plain text, as you may expect.

**Comment by nightroman** [comment]
Another "simpler" workaround is using IB `exec` like this

```powershell
task Test {
    exec { <call your app> } -ErrorAction Continue
}
```

**Comment by benmishkanian** [comment]
Thank you very much for your help! At first I was worried that `-ErrorAction Continue` would make the task continue to execute after the Python invocation fails, but it seems like it still properly errors out while also making the stderr redirectable. So this solution works for me. Thanks again!

**Comment by nightroman** [comment]
In `exec`, it fails if the app exit code is not 0, no matter what `-ErrorAction` is.
If this workaround (yes, unfortunately) works then we may close the issue.

**Comment by nightroman** [comment]
But I think I should mention this in `exec` help. Nobody reads help, I know... yet some people do, at least when they have some issues.

**Comment by benmishkanian** [comment]
A documentation update would be great, but I'm not sure this particular message would have helped me. I actually wanted the task to fail, but my confusion was about why the stderr could not be redirected. To be honest I don't completely understand even now why `-ErrorAction Continue` fixes my problem; I just see that it does.

**Comment by nightroman** [comment]
**I think** because it used to fail just at the moment of this error output. Which is wrong, app may write whatever it wants to stderr but exist with success 0.  `-ErrorAction Continue` avoid this premature and potentially wrong failure.

What information would help you in the help or wiki in such cases?

**Comment by benmishkanian** [comment]
Hmm, I am not sure that explanation fully explains what is happening, because the stderr is correctly written to the console if I don't redirect it. But if I try to redirect stderr, it seems to get lost completely.

So the reason is still unclear to me, but maybe the documentation could mention that `-ErrorAction Continue` makes stderr redirectable? But it seems like we don't really know why that is the case, so maybe it really is a bug?

**Comment by nightroman** [comment]
I am also not sure what is happening. It also depend on environment, host, and how exactly it is all invoked. Maybe I should should rephrase it as "if you have any issues with std err then try...".

**Comment by nightroman** [comment]
```
	If you have any issues with standard error output of the invoked app, try
	using `exec` with -ErrorAction Continue, SilentlyContinue, or Ignore. This
	does not affect failures of `exec`, they still depend on the app exit code.
	But this may work around some known PowerShell issues with standard errors.
```

**Comment by nightroman** [comment]
Closing. I pushed the package with the updated help and also created this demo case https://github.com/nightroman/Invoke-Build/tree/master/Tasks/StdErr with details and tests.
