### ISSUE TITLE
Add default value to property

### ISSUE THREAD

**Issue by majkinetor** [nightroman/Invoke-Build#163]
I.e.

```ps1
param ( 
    $aEnvironment = (property ENVIRONMENT 'Development')
)
```

**Comment by nightroman** [comment]
Hi @majkinetor . Is this a question or suggestion? It's not clear, sorry. Especially because `property` already supports default values, exactly as you show in the sample.

**Comment by majkinetor** [comment]
Really ? OK sorry then :) Perhaps I had a typo or something ...

**Comment by majkinetor** [comment]
I also looked into tests and there wasn't any :)

**Comment by nightroman** [comment]
No problem at alll! Tests are here https://github.com/nightroman/Invoke-Build/blob/master/Tests/Property.test.ps1
