### ISSUE TITLE
.Synopsis support in invoke-build ?

### ISSUE THREAD

**Issue by Vaevictus** [nightroman/Invoke-Build#165]
The format for adding a synopsis to a build task such as
<#
Synopsis: Empty the various build output directories
#>

is not in line with how you would add synopsis support for functions elsewhere in powershell.

Could invokebuild also support synopsis decorations such as in this format:
<#
.Synopsis
Empty the various build output directories
#>

**Comment by nightroman** [comment]
I think we can do this. To be in line with PS doc comments is a good argument.

**Comment by nightroman** [comment]
This is doable indeed but with a somewhat unwanted effect.

Given the script:

```powershell
<#
.Synopsis
    Script synopsis.
#>

# Task with no synopsis.
task T1 {}
```

The task T1 currently has no synopsis. With the suggested change, the script synopsis is found and used as the task synopsis.

**Comment by majkinetor** [comment]
I would still like to keep the prev one as that version is more noisy,

**Comment by nightroman** [comment]
Of course I will keep the old one in any case.

I have some doubts about adding the new style. Kind of waiting for more comments and thoughts about pros and cons.

**Comment by nightroman** [comment]
v5.5.11
