### ISSUE TITLE
Why does importing of other tasks not work in Enter-Build block?

### ISSUE THREAD

**Issue by GreatTeacherBasshead** [nightroman/Invoke-Build#171]
As mentioned [here](https://github.com/nightroman/Invoke-Build/wiki/Build-Scripts-Guidelines#use-enter-build-or-check-whatif-for-initialization), I try to use `Enter-Build` for initialization:
```
Enter-Build {
. '..\Common.tasks.ps1' # this contains some_task
. '..\Other.tasks.ps1'

$var1 = $param1
...
}
```
When I run it, I get an error:
`ERROR: Task 'Main': Missing task 'some_task'.`

When I place dot-sourcing statement just in the script, not using `Enter-Build` block, then it works.

**Comment by nightroman** [comment]
`Enter-Build` is called after adding all tasks and before invoking these added tasks. Thus, tasks cannot be added in `Enter-Build`. In other words, "adding tasks" is not "initialization".

> When I place dot-sourcing statement just in the script, not using Enter-Build block, then it works.

This is the correct way of adding tasks.

**Comment by nightroman** [comment]
TODO: Think about failing on adding tasks after loading build scripts.

**Comment by nightroman** [comment]
v5.6.2 fails on adding tasks after loading build scripts.
