### ISSUE TITLE
Make Invoke-BuildExec/exec display the command.

### ISSUE THREAD

**Issue by wekempf** [nightroman/Invoke-Build#176]
It would be helpful to make `exec` display the command it will execute, even if that's controlled with a switch. It would also be useful if the command text (even in the exception handler) were expanded. Here's an implementation illustrating the idea.

```powershell
function Invoke-BuildExec([Parameter(Mandatory=1)][scriptblock]$Command, [int[]]$ExitCode=0) {
    ${private:*c} = $Command
    ${private:*x} = $ExitCode
    ${private:*cs} = $ExecutionContext.InvokeCommand.ExpandString(($Command.ToString().Split() | Where-Object { $_ }))
    Remove-Variable Command, ExitCode
    Write-Build DarkCyan "CMD: ${*cs}"
    & ${*c}
    if (${*x} -notcontains $global:LastExitCode) {
        *Die "Command {${*cs}} exited with code $global:LastExitCode." 8
    }
}
```

Same thing but with a switch.

```powershell
function Invoke-BuildExec([Parameter(Mandatory=1)][scriptblock]$Command, [int[]]$ExitCode=0, [switch]$ShowCommand) {
    ${private:*c} = $Command
    ${private:*x} = $ExitCode
    ${private:*cs} = $ExecutionContext.InvokeCommand.ExpandString(($Command.ToString().Split() | Where-Object { $_ }))
    Remove-Variable Command, ExitCode
    if ($ShowCommand) { Write-Build DarkCyan "CMD: ${*cs}" }
    & ${*c}
    if (${*x} -notcontains $global:LastExitCode) {
        *Die "Command {${*cs}} exited with code $global:LastExitCode." 8
    }
}
```

I prefer without a switch, but I don't know if you want to have the default behavior to show the command.

**Comment by nightroman** [comment]
@wekempf It looks like a reasonable idea, thank you. It should be a switch (sorry about your preferred default), some simpler name like `-Echo` may be used. Or maybe an IB option or a script level option, this needs some thinking.

**Comment by wekempf** [comment]
Both a switch and a more global option maybe? I can see wanting to show it selectively as well as just changing the behavior for a whole script.

**Comment by wekempf** [comment]
I'm already doing this in some of my scripts by simply overwriting the function with my own. That might be a worthwhile example to add (not everyone will be aware that you can redefine anything in PowerShell).

**Comment by nightroman** [comment]
With the switch, the script level option will be kind of available. Modern PowerShell has a way to specify the default for a command parameter, IIRC.

**Comment by wekempf** [comment]
I'd vote for just the switch then.

**Comment by mwallner** [comment]
I like this, maybe just think about adding a note in the cmdlet help that people should use `-Echo` (or whatever) with care, b/c it could easily lead to leaking sensitive information/credentials...

**Comment by wekempf** [comment]
@mwallner  Good point. Wonder if there's a way to specify variables not to expand here. Definitely a reason to put this behind a switch, though.

**Comment by nightroman** [comment]
Oh... I missed the whole variable expansion in the code, I thought about just the script block printing. I am not sure I like this, yet. This needs even more thinking, does not look safe...

**Comment by wekempf** [comment]
The variable expansion is quite important in my scenarios, as figuring out what the build did on failures is crucial. I understand the security concerns, however, so something like an -ExcludeExpansion list maybe?

**Comment by nightroman** [comment]
>so something like an -ExcludeExpansion list maybe

Or rather `-EchoExpandVariables`, to be secure by default.
I wonder if this expansion works in older PS versions, too.

**Comment by nightroman** [comment]
Side question. Why `.Split() | Where-Object { $_ }`? I.e. why not to expand on the whole string?

**Comment by wekempf** [comment]
I'll be honest, that was borrowed code. I think the split is an odd way to deal with spacing concerns, rather than just trimming the string, but that's purely a guess on my part.

Selectively expanding will be interesting, given variables can be represented multiple ways. With and without scopes, with and without curly braces, some other way I'm not familiar with?

**Comment by nightroman** [comment]
How about this approach which avoids and solves issues 

```powershell
	Get-Variable x, y | Format-Table
	exec {something -with $x $y} -echo
```

**Comment by nightroman** [comment]
I do not think we should use `ExpandString`, it is supposed to invoke code, too, not just expand variables:

```powershell
function boom {
	throw 'boom'
}

$text = '$(boom)'
$ExecutionContext.InvokeCommand.ExpandString($text)
```

**Comment by nightroman** [comment]
As a result, I am thinking of just this simple change:

```powershell
function Invoke-BuildExec([Parameter(Mandatory=1)][scriptblock]$Command, [int[]]$ExitCode=0, [switch]$Echo) {
	if ($Echo) {
		Write-Build 3 "exec {$Command}"
	}
	${private:*c} = $Command
	${private:*x} = $ExitCode
	Remove-Variable Command, ExitCode, Echo
	& ${*c}
	if (${*x} -notcontains $global:LastExitCode) {
		*Die "Command {${*c}} exited with code $global:LastExitCode." 8
	}
}
```

Is it still needed in this form without string expansion? I do not want to engage string expansion for safety reasons.

By the way, how to enable `-Echo` for the whole script or task (depends on the place):

```powershell
$PSDefaultParameterValues=@{'Invoke-BuildExec:echo'=$true}
```

**Comment by nightroman** [comment]
So, do we proceed with this simple change or it's not worth it?

**Comment by nightroman** [comment]
OK, some development, see the created branch and maybe try (use the new `Show-ExecEcho.ps1` and updated `Invoke-Build.ps1`). Unlike `ExpandString` which may accidentally (or worse) invoke code, `Show-ExecEcho.ps1` only evaluates variables. This is safer. But the code is more complex, so I decided to use a separate helper script.

**Example** This script

```powershell
$foo = 'foo'
$env:SOME_VAR = 'SOME_VAR'

task t1 {
	$bar = 'bar'

	exec -echo {  cmd /c echo $script:foo $env:SOME_VAR  }

	exec -echo {
		# bar
		cmd /c echo $bar $env:SOME_VAR
	}
}
```

outputs

![image](https://user-images.githubusercontent.com/927533/108464485-23f78c80-7278-11eb-8a3b-61ff4c44350a.png)

**Comment by nightroman** [comment]
After playing with this I started to like the idea with this implementation. Also, after some tweaks the code is simple enough for the main script, the helper script is not needed.

**Comment by nightroman** [comment]
Done in v5.7.0
