### ISSUE TITLE
exec with a error message

### ISSUE THREAD

**Issue by dsbenghe** [nightroman/Invoke-Build#178]
It will be helpful if we can pass an argument to the exec "helper" for executing commands with a custom error message to be used in case of failure.

**Comment by nightroman** [comment]
Hmm, maybe but this is easily done as `try { exec {...} } catch { throw "My custom message" } }`.
New features should add some more significant values, ideally.

**Comment by dsbenghe** [comment]
Sure we can do that, but because exec doesn't have the error message param there is no benefit for us in using it when we want a custom error message and we just go with the basics: 
```
& cmd
if() { throw "blah"}
```
which is simpler and more readable than try/exec/catch

**Comment by nightroman** [comment]
>which is simpler and more readable than try/exec/catch

Yes, this is also a good way and again a reason that the suggested feature is not that "must have".

**Comment by nightroman** [comment]
In fact, one of the main purposes of `exec` (IMHO) is to make the error messages uniform. So custom messages reduce necessity of `exec` even further.

**Comment by nightroman** [comment]
Then, what is custom message exactly? Literal text on errors? Or should it include the exit code or the command or both?
How do you see this?
What if others would see this differently?

(I am just thinking out loud)

**Comment by dsbenghe** [comment]
Maybe I wasn't clear but I was not suggesting to replace existing default message; just to be able to add additional information - no matter what is that: just a string sounds fine to me.

**Comment by nightroman** [comment]
Can you give an example command and the result, how see this?

**Comment by dsbenghe** [comment]
Plenty of times we are just using exec, but also plenty of times we want to add additional informative messages in case of failure to be easier to identify what failed. At that moment it is just easier/nicer to move back to if()  which is annoying: some code is using exec, other code if().

I would think that an additional custom error message complements very naturally the current exec making it more useful.

exec {
 &cmd ...
} -ErrorMessage 'Failed to execute blah ..... whatever string"

Result;
<SomePrefixMaybe>: Failed to execute blah ..... whatever string
<Whatever is displayed now>

**Comment by nightroman** [comment]
@dsbenghe I work on this, do not worry. This week is busy (work on inherited custom headers and footers in IB).

Then I plan something like this:

```powershell
function Invoke-BuildExec([Parameter(Mandatory=1)][scriptblock]$Command, [int[]]$ExitCode=0, [string]$ErrorMessage, [switch]$Echo) {
	${private:*c} = $Command
	${private:*x} = $ExitCode
	${private:*m} = $ErrorMessage
	${private:*e} = $Echo
	Remove-Variable Command, ExitCode, ErrorMessage, Echo
	if (${*e}) {
		Write-Build 3 (Show-BuildExec ${*c})
	}
	& ${*c}
	if (${*x} -notcontains $global:LastExitCode) {
		*Die "$(if (${*m}) {"${*m} "})Command exited with code $global:LastExitCode : ${*c}" 8
	}
}
```

**Comment by nightroman** [comment]
Invoke-Build 5.7.2 - new parameter `exec -ErrorMessage ...`

**Comment by dsbenghe** [comment]
thanks.
