### ISSUE TITLE
Watch command?

### ISSUE THREAD

**Issue by deevus** [nightroman/Invoke-Build#18]
I'm hoping to replace `gulp` and I think the only thing missing that I need is a "watch" command. I want to be able to give a list of files to watch, and a command to run with the intention of running `webpack` when scripts are updated.

Thoughts?

**Comment by nightroman** [comment]
I am not familiar with `gulp` and its `watch` command. I will google but it would be useful if you describe some specs it terms of `Invoke-Build`.

**Comment by nightroman** [comment]
A naive approach from the top of my head. A working example of `FileSystemWatcher` in PowerShell
is [here](https://gallery.technet.microsoft.com/scriptcenter/Powershell-FileSystemWatche-dfd7084b). We configure it for required files and events and start it in a console which is kept running.
From the appropriate event handler we call `Invoke-Build` with specified tasks and parameters, as usual.

**Comment by nightroman** [comment]
Just to be clear, the above does not need anything extra in `Invoke-Build`. It is just a PowerShell script which uses `Invoke-Build` as it is.

**Comment by nightroman** [comment]
The script uses the `Action` parameter. Yet another approach is possible and
may be simpler because processing is done not by PowerShell jobs. We just
subscribe to events without actions

```
Register-ObjectEvent $fsw Created -SourceIdentifier FileCreated
Register-ObjectEvent $fsw Deleted -SourceIdentifier FileDeleted
Register-ObjectEvent $fsw Changed -SourceIdentifier FileChanged
```

Then in the main script we use `Wait-Event` or check for events periodically by
`Get-Event`, process them and remove by `Remove-Event`.

**Comment by nightroman** [comment]
And I created the tool [Watch-Directory.ps1]( https://github.com/nightroman/PowerShelf/blob/master/Watch-Directory.ps1). It is designed for any commands processing changes. In your case this command may call Invoke-Build. The tool is not final and not fully tested but it seems to be working.
