### ISSUE TITLE
Publishing the "Tasks" folder with the Powershell Gallery Module exported as aliases?

### ISSUE THREAD

**Issue by JustinGrote** [nightroman/Invoke-Build#181]
Out of curiosity, the tasks folder contains some extremely useful tasks I was not aware of at all. Is there a reason these aren't shipped with the PSGallery module as aliases? e.g. `ibTaskCheck` so that as long as I have the module loaded, my build scripts can call `. ibTaskCheck` to load it rather than having to source it from the repo?

**Comment by nightroman** [comment]
There are reasons, kind of, and lots of doubts... This folder is the demo of techniques and extensibility features. While many of them are useful (and used!), they are all opinionated. Also, I (and some users) really want to keep the package as small as possible. So if a tool/feature is likely not needed by the majority then it should stay outside.
