### ISSUE TITLE
Accessing the original working directory

### ISSUE THREAD

**Issue by brantb** [nightroman/Invoke-Build#183]
I would like to use the current directory to infer the value of an (optional) parameter. The only way I could figure out how to do this was by accessing the "private" `${*}` variable like this:

```powershell
param([string]$WorkDir)

Task Demo {
  # If -WorkDir was not provided, infer it from cwd
  if (-not $WorkDir) {
    $WorkDir = ${*}.CD
  }
  # ... do stuff with $WorkDir
}
```

Assuming I haven't missed a non-hacky way of getting this, could `${*}.CD` be exposed via a built-in variable? Maybe `$OriginalLocation`?

**Comment by nightroman** [comment]
You are right, `${*}.CD` is currently the only way. The request for the official built-in variable looks reasonable. Let me think about this.

**Comment by nightroman** [comment]
v5.8.1 introduces `$OriginalLocation`.

**Comment by GreatTeacherBasshead** [comment]
Hi,
so `$BuildRoot` variable points to a directory where the scripts is located;
and `$OriginalLocation` points to my current working directory.

Did I get it right?

Maybe it also could be added to [Special Variables](https://github.com/nightroman/Invoke-Build/wiki/Special-Variables)?

**Comment by nightroman** [comment]
@GreatTeacherBasshead 

> so $BuildRoot variable points to a directory where the scripts is located;

Where the current build script is located, unless this variable is changed by the script itself in special (rare) cases.

> and $OriginalLocation points to my current working directory.

Yes, your current before and after the build. But during the build the current is $BuildRoot.

> Maybe it also could be added to Special Variables?

Thank you, of course! It's done. Also `Job` was missing there.

**Comment by fdcastel** [comment]
@nightroman Sorry for necroing on this issue, but could this `$OriginalLocation` be added to the docs?

Let's just say that it took me a significant chunk of time to find it. 😉

Probably, [here](https://github.com/nightroman/Invoke-Build/wiki/Build-Scripts-Guidelines#buildroot-and-psscriptroot)?

**Comment by nightroman** [comment]
@fdcastel Sure, I'll take care in the place you suggested and think of other suitable. Thank you.

**Comment by nightroman** [comment]
Done at the wiki as you suggested. It also mentioned in `help Invoke-Build`, see `PUBLIC VARIABLES`.
I'll think of where else it is useful to be mentioned.
