### ISSUE TITLE
Getting Task name from another task.

### ISSUE THREAD

**Issue by jdispiritoae** [nightroman/Invoke-Build#186]
Is it possible to get the name of the task that called a task?

Take this code for example:

task BuildAll Step1 Step2 Step3

When running Step1, is it possible to get the name "BuildAll"  from a predefined variable?
I would like to be able to retrieve a value in a hash table with the key name of a task.

**Comment by nightroman** [comment]
Have you closed the issue by mistake or because you found an answer?

Anyway, every task has the automatic variable `$Task` defined by the build engine.
The current task may access its variable directly as `$Task`.
To get the parent task variable use `Get-Variable Task -Scope 2 -ErrorAction 0`.

`-ErrorAction 0` is used to avoid an error when the parent task does not exist.
And you have to check the result for `$null` ~ the parent task does not exist.

Example script.
Tasks `step1` and `step2` print their own name and the parent task name

```powershell
task buildAll step1, step2

task step1 step2, {
    # this task
    $Task.Name

    # parent task
    $taskParent = Get-Variable Task -Scope 2 -ErrorAction 0
    if ($taskParent) {
        $taskParent.Value.Name
    }
}

task step2 {
    $Task.Name

    # parent task
    $taskParent = Get-Variable Task -Scope 2 -ErrorAction 0
    if ($taskParent) {
        $taskParent.Value.Name
    }
}
```

Output on `Invoke-Build buildAll`

```
Build buildAll C:\ROM\z\_210831_7h-ib\.build.ps1
Task /buildAll/step1/step2
step2
step1
Done /buildAll/step1/step2 00:00:00.0156265
Task /buildAll/step1
step1
buildAll
Done /buildAll/step1 00:00:00.0468917
Done /buildAll 00:00:00.0468917
Build succeeded. 3 tasks, 0 errors, 0 warnings 00:00:00.2812519
```

**Comment by jdispiritoae** [comment]
Thanks for the detailed explanation.   I had closed the ticket because in my testing I found the variable $BuildTask, and that contained the task information I needed to use for my hash table lookup.  

Invoke-Build is a powerful tool!  Thanks for writing it!

**Comment by nightroman** [comment]
Good and thank you!

A word of caution. See my example. The command is `Invoke-Build buildAll` so `$BuildTask` contains just `buildAll`. And the task `step2` "does not know" that it is actually called by `step1`. This may or may not be important in your scenario, indeed.

A side thought/question - why do you need to know a parent/calling task? In theory, idiomatically, etc. tasks are things on their own. They may depend on script parameters. But depending on a caller is rather unusual (I am not saying "wrong").

**Comment by jdispiritoae** [comment]
We use Invoke-Build to launch our image building processes, which consist of three tasks.  The first task prepares the build environment.  The build process can fail due to any number of circumstances.  Depending on the failure, cleanup inside of our provisioning system may or may not occur.   If we don’t properly clean up the node, the next time we run that build, it will error out because the node exists.  Without hardcoding the cleanup into each image build task, I wanted to create a way to easily test if that cleanup has occurred.  Since the first task ran in our process sets up our provisioning environment (thus allowing me to use $BuildTask),  I added a lookup table there where the key is the build task name, and the value is the name of the node inside our provisioning system.   If it sees the node is still there, it will delete it.

Thanks for getting back to me, and the detailed information your provided!
John.
