### ISSUE TITLE
Ib.cmd no longer included in \tools folder 

### ISSUE THREAD

**Issue by pmarflee** [nightroman/Invoke-Build#187]
While upgrading a project to the latest version of Invoke-Build (v5.8.4), I noticed that ib.cmd is no longer present in the \tools folder of the installed NuGet package. Is this an oversight, or was it a deliberate decision to remove it?

**Comment by nightroman** [comment]
It's deliberate, see https://github.com/nightroman/Invoke-Build/blob/master/Release-Notes.md#v580
