### ISSUE TITLE
Is it possible to change the name of the build in Build-Parallel?

### ISSUE THREAD

**Issue by max-ieremenko** [nightroman/Invoke-Build#189]
I am using the following script to run builds in parallel (simplified):

```powershell
Build-Parallel @(
    @{ File="build.ps1"; name="foo" }
    @{ File="build.ps1"; name="bar" }
)
```

the log output is

```txt
Start (1/2) build.ps1
Start (2/2) build.ps1
...
```

is it possible to have the log like

```txt
Start (1/2) build.ps1 "foo"
Start (2/2) build.ps1 "bar"
...
```

**Comment by nightroman** [comment]
This is not possible as such. The script has no customization like this.

I am not sure about "name" for such header info. For IB it is just a particular
parameter name and IB does not know it. Other authors may prefer "Title" or
"BuildName", etc.

But IB knows about "File" (and shows it) and "Task". In theory IB may also show
task names in headers in addition to files.

Then, for example, you may add/have tasks `foo` and `bar` to your scripts.

Then call:

```powershell
Build-Parallel @(
    @{ File="build.ps1"; Task="foo" }
    @{ File="build.ps1"; Task="bar" }
    @{ File="build.ps1"; Task="task1", "task2" }
)
```

outputs something like:

```
Start (1/3) build.ps1 foo
Start (2/3) build.ps1 bar
Start (3/3) build.ps1 task1, task2
...
```

This kind of change is possible and probably useful out of box.
What do you think?

**Comment by max-ieremenko** [comment]
Unfortunately, your version won't help me. In my case all parallels have the same file and task, but different parameters.

Thank you for the clarification.

**Comment by nightroman** [comment]
You can can create artificial / bespoke  tasks designed for exactly this purpose.

**Comment by nightroman** [comment]
Sorry, closed by mistake. What about showing all parameters then?

**Comment by nightroman** [comment]
We can add the parameter `ShowParameter` (`[string[]]` for one or more).

Example:

```powershell
Build-Parallel -ShowParameter Name @(
    @{ File="build.ps1"; Name="foo" }
    @{ File="build.ps1"; Name="bar" }
)
```

outputs something like:

```
Start (1/3) build.ps1 Name: foo
Start (2/3) build.ps1 Name: bar
...
```

I think this solves your issue.
And it is "secure", it's up to an author to use or not.

**Comment by nightroman** [comment]
done
https://github.com/nightroman/Invoke-Build/blob/master/Release-Notes.md#v587

**Comment by max-ieremenko** [comment]
This is exactly what i'm looking for.
Many thanks!
