### ISSUE TITLE
Invoke-Build VSTS build task

### ISSUE THREAD

**Issue by qetza** [nightroman/Invoke-Build#19]
Hi,
This is not an issue but i didn't know how to contact the invoke-build team :(

I've published a build task for VSTS that allow people to easily use invoke-build scripts, you can find the extension here:
https://marketplace.visualstudio.com/items?itemName=qetza.invokebuild

As a side question, do you have the logo in 128x128 size?

Guillaume

**Comment by nightroman** [comment]
@Guillaume, I noticed your projects a few days ago. I am interested.
Unfortunately, I do not use VSTS and do not know how to try it.

I have a remark, if you do not mind. You use `Invoke-Expression` for invoking
`Invoke-Build`. `Invoke-Expression` is not a perfect way to run something in
PowerShell. It often makes things more difficult than they should be. More
difficult to diagnose issues, for example. Note that in you another similar
`psake` based project you do not use `Invoke-Expression` and invoke `psake`
directly. This is much better.

> As a side question, do you have the logo in 128x128 size?

No. You can easily make one. It's just the text `>ib` with the font Magneto.

**Comment by qetza** [comment]
@nightroman. You can create a free account on VSTS here if you want: https://www.visualstudio.com/products/visual-studio-team-services-vs

As for `Invoke-Expression`, i've used it for `Invoke-Build` because of the following constraints:

- The parameters specified by the users in the build task UI are passed as string to the build task script
- `Invoke-Build` supports dynamic parameters

So the only way i found to enable users to specify dynamic parameters in the UI and use them with those constraints was to create the PowerShell command as a string and then use `Invoke-Expression` on it. I didn't have this issue with `psake` because the do not support dynamic parameters but uses hashtable so i was able to parse the input strings and convert them to hashtables.

Of course if you know a better way (i'm not a PowerShell expert) i'm glade to have your advices :)

**Comment by nightroman** [comment]
Invoke-Build also supports passing parameters as a hashtable, see its parameter `Parameters`:

````
    -Parameters
        A hashtable of parameters passed in the build script. It is needed only
        in special cases. Normally build script parameters may be specified for
        Invoke-Build itself, thanks to PowerShell dynamic parameters.

        Dynamic parameters and the hashtable Parameters are not used together.
        If build script parameters conflict with Invoke-Build parameters then
        the hashtable Parameters is the only way to pass them in the script.
````

Your case is probably special, i.e. it makes sense to use `Parameters` hashtable instead of dynamic parameters because it avoids `Invoke-Expression`. On the other hand, if you see that `Invoke-Expression` works fine in practice then why not.

**Comment by nightroman** [comment]
Nice icon, by the way. May I borrow when I need one?

**Comment by qetza** [comment]
As Invoke-Expression seems to be working (and is also used by Microsoft in their own tasks) i will keep it like this but keep in mind if any issue happens to switch to the Parameters argument (which i didn't see :( )
For the icon you can use, it was just 5 minutes of work in paint.net as soon as i had the font name :)

**Comment by nightroman** [comment]
I have created the wiki page [Related Projects](https://github.com/nightroman/Invoke-Build/wiki/Related-Projects). It includes this VSTS extension.
