### ISSUE TITLE
vscode outline view: no symbols found in document

### ISSUE THREAD

**Issue by pwm1234-sri** [nightroman/Invoke-Build#197]
Let me first say thank you for your work on Invoke-Build. I recently discovered Invoke-Build, and I have found it quite helpful. One question I have: is there a way to get the vscode outline view to work for a build task file? 

Here is an example of what I see for a normal ps1 file:
![image](https://user-images.githubusercontent.com/73309596/159046766-9b0b3022-ca7b-4f8e-8b24-c39e09b113c7.png)

But for a build file with tasks it says "No symbols found":
![image](https://user-images.githubusercontent.com/73309596/159047024-c9705a92-6181-4b0e-a3b6-05424d0be144.png)

This may sound trivial, but as a newcomer to both Invoke-Build and powershell, a working outline view would be a big help to me for understanding and developing a build script.

**Comment by nightroman** [comment]
PowerShell does not know IB tasks. It is what it is. As a work around, you
may go to any task and use "find references" to see all available tasks.

**Comment by pwm1234-sri** [comment]
Thanks - "find references" is a great tip!
