### ISSUE TITLE
Please consider adding -Computername and -Session parameter to Task

### ISSUE THREAD

**Issue by yangxinyun** [nightroman/Invoke-Build#201]
So far, all the tasks will only be able to execute on the host machine itself.

It would be nicer if we can have a parameter like -Computername or -Session that allows the task to run on a different machine.
This is very handy in an enterprise environment where network traffic is not allowed from a single machine but split into different ones.
In other toolings, like azure DevOps pipeline and ansible, they have already supported this.

**Comment by nightroman** [comment]
Hi @yangxinyun . I afraid what you ask (even if doable) does not fit well to the tool which was designed with different architecture in mind.

> In other toolings, like azure DevOps pipeline and ansible, they have already supported this.

Maybe. But this is not exactly an argument. These tools are not like `Invoke-Build` or `psake`. Compare: `Invoke-Build` can probably do what these tools cannot. This is not a "fault" of these tools, they were not designed like `Invoke-Build`.

Having said that... What if what you actually want is doable but in a different way, maybe even better?

If you need to run some code remotely then there is the built-in `Invoke-Command` for this. `Invoke-Build` tasks does not have to run remotely as such but part of their code can.

`Invoke-Command` has `-ComputerName` and `-Session`. But it has a lot more, really a lot more. `task` with the subset of parameters would be a very simplified ("nicer" you say) version of `Invoke-Command` with less abilities and control. Really, why?..

Please try to give some more arguments why `task -ComputerName {...}` is nicer than `task { Invoke-Command -ComputerName {...}}`.

**Comment by yangxinyun** [comment]
> Hi @yangxinyun . I afraid what you ask (even if doable) does not fit well to the tool which was designed with different architecture in mind.
> 
> 
> 
> > In other toolings, like azure DevOps pipeline and ansible, they have already supported this.
> 
> 
> 
> Maybe. But this is not exactly an argument. These tools are not like `Invoke-Build` or `psake`. Compare: `Invoke-Build` can probably do what these tools cannot. This is not a "fault" of these tools, they were not designed like `Invoke-Build`.
> 
> 
> 
> Having said that... What if what you actually want is doable but in a different way, maybe even better?
> 
> 
> 
> If you need to run some code remotely then there is the built-in `Invoke-Command` for this. And `Invoke-Build` task does not have to run remotely as such but a part of its code can.
> 
> 
> 
> `Invoke-Command` has `-ComputerName` and `-Session`. But it has a lot more, really a lot more. `task` with the subset of parameters would be a very simplified ("nicer" you say) version of `Invoke-Command` with less abilities and control. Really, why?..
> 
> 
> 
> Please try to give some more arguments why `task -ComputerName {...}` is nicer than `task { Invoke-Command -ComputerName {...}}`.
> 
> 
> 
> 

Hi @nightroman 

Thanks for getting back. Indeed, invoke-command has already provided full-fledged remote execution support. Adding those parameters to task can at its best provide syntax sugar to users like  me who are used to having it out of box. If only powershell supports function overload, adding remote support might be as easy as delegating to invoke-command.

**Comment by nightroman** [comment]
Syntax sugar would make some sense if we see a lot of remove tasks in build scripts. I'd consider it even with drawbacks I mentioned (reduced options and control of input, output, and errors). But this is not the case, most of build scripts I have myself and I see on GitHub are totally local.

**Comment by yangxinyun** [comment]
> Syntax sugar would make some sense if we see a lot of remote code in build scripts. I'd consider it even with drawbacks I mentioned (reduced options and control of input, output, and errors). But this is not the case, most of build scripts I have myself and I see on GitHub are totally local.

Indeed, only enterprise environment with lots of etra security will need it😂 it is useless feature for open source project

**Comment by nightroman** [comment]
Fair point :) But my point stays, I believe that remote code in build scripts is minority. Bad luck to be in this minority, indeed. But it's not the end of the world as we hopefully agree. `Invoke-Command`!

**Comment by yangxinyun** [comment]
Agreed🫡

**Comment by nightroman** [comment]
@yangxinyun 

Please take a look at custom tasks how-to demos:
https://github.com/nightroman/Invoke-Build/tree/master/Tasks

If in your enterprise environment remove tasks are frequent and you need some syntax sugar then Invoke-Build custom task(s) may help. Namely you may define your own, say, `ComputerTask` or `SessionTask` with extra parameters (all up to you) and use it across you projects/build scripts.

**Comment by yangxinyun** [comment]
> @yangxinyun
> 
> Please take a look at custom task how-to demos ("Custom tasks"): https://github.com/nightroman/Invoke-Build/tree/master/Tasks
> 
> If in your enterprise environment remote tasks are frequent and you need some syntax sugar then Invoke-Build custom task(s) may help. Namely you may define your own, say, `ComputerTask` or `SessionTask` with extra parameters (all up to you) and use it across your projects/build scripts. You may even share the result :) so that we add it to the sample demos for others.

Thanks a lot! Looks like a plan
