### ISSUE TITLE
Exec doesn't work well with forward slash arguments

### ISSUE THREAD

**Issue by CoenraadS** [nightroman/Invoke-Build#209]
Hello, first of all, really nice project :)

I am trying to run InnoSetup, which uses forward slash arguments, e.g.

```
    exec { $installerPath /verysilent /allusers /dir=$innoSetupDir } -Echo
```

This doesn't work very well, as powershell complains `You must provide a value expression following the '/' operator.`

So then I try to workaround by using `&`

```
    exec { & $installerPath /verysilent /allusers /dir=$innoSetupDir } -Echo
```

But now it returns immediately, and doesn't behave correctly on errors.

I understand this is limitation of using `[scriptblock]` to pass the arguments.

I was wondering if perhaps it's an idea to make something like `exec-process ($Command, $ArgumentList)`, which would just call `Start-Process` under the hood to handle these situations.

Then I could use e.g. `exec-process $installerPath "/verysilent /allusers /dir=$innoSetupDir"`

**Comment by nightroman** [comment]
@CoenraadS I am not yet sure it's about `exec` or `Invoke-Build`. Can you run your command in plain PowerShell console?

```
& $installerPath /verysilent /allusers /dir=$innoSetupDir
```

The first command is not correct, indeed. The second looks correct. What is in your `$installerPath` exactly? What errors do you  get? What version of PowerShell and Invoke-Build do you use?

**Comment by CoenraadS** [comment]
The full command is:

`C:\Users\asdf\innosetup-6.2.2.exe /verysilent /allusers /dir=C:\Users\asdf\Projects\InnoSetup\nuget-tools-innosetup\InnoSetup`

If I run it directly in powershell, it also returns immediately, unless I add `| Wait-Process` to the end. But if I try to that to the exec block, I get ` Dangling scriptblock at...` errors.

e.g. `exec { & $installerPath /verysilent /allusers /dir=$innoSetupDir | Wait-Process }`

**Comment by nightroman** [comment]
I do not think you use use `Wait-Process` how it is supposed to be used, see [Wait-Process](https://learn.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Management/Wait-Process?view=powershell-7.3&viewFallbackFrom=powershell-7)

**Comment by CoenraadS** [comment]
Hmm I got it from this answer and it works for me: https://stackoverflow.com/a/24439202/4503491

Powershell version: 5.1.19041.2364

**Comment by nightroman** [comment]
Like I said, it is not about `exec` or `Invoke-Build`. It is about how innosetup works and you handle it. If it starts and returns returns immediately then you should not use `exec` at all. Start it by `Start-Process` and use `-PassThru` in order to get the process instance. Then use this instance as input for `Wait-Process` in order to wait for its exit and then get and check its exit code.

Disclaimer. I do not use innosetup, the above just common sense.

**Comment by CoenraadS** [comment]
Yes, but I use this nice framework so I could avoid having to write my own helper scripts. Would be nice to support this out of the box, since I don't think it's so unusual, that was all.

**Comment by nightroman** [comment]
`Start-Process -Wait -PassThru` is your friend for not standard cases like innosetup.
In your case something like

```powershell
$process = Start-Process $installerPath "/verysilent /allusers /dir=$innoSetupDir" -Wait -PassThru
# check $process exit code here
```

I do not think any support from `Invoke-Build` is needed for such cases.
(1) PowerShell out of the box tools do the job well.
(2) Commands like innosetup are not typical.
