### ISSUE TITLE
Error when running within Azure deployment

### ISSUE THREAD

**Issue by deevus** [nightroman/Invoke-Build#21]
I'm trying to use `Invoke-Build` during an Azure deployment, however I get the following error:

```D:\home\site\repository\Invoke-Build.2.14.2\tools\Invoke-Build.ps1 : Exception 
setting "ForegroundColor": "The Win32 internal error "The handle is invalid"```

I'm assuming that because it's not a regular environment you can't set the `ForegroundColor`.

**Comment by nightroman** [comment]
> it's not a regular environment
What kind of environment is it? I.e. how can you recognize it and avoid setting ForegroundColor (for now)? I.e. try to check `$Host.Name` (suppose "AzureHost") and add it to

````
if (!$Host.UI -or !$Host.UI.RawUI -or $Host.Name -eq 'Default Host' -or $Host.Name -eq 'AzureHost') {
	function Write-Build($Color, [string]$Text) {$Text}
}
````

or just use `if ($true)` for now.

Meantime I will think of some better solution.

**Comment by nightroman** [comment]
An elegant solution, if any is possible, is not that simple and it will take time. For now, I am going to add the host's name to the list of known "no color" hosts (one known is 'Default Host'). But I need the name.

Could you please get it? You can do the following trick. In your build script define

````
function Write-Build($Color, [string]$Text) {$Text}
````

It will ensure output with no colors and no related problems. Then, in one of invoked tasks output `$Host.Name` and tell me what the output is.

**Comment by deevus** [comment]
I'll get it for you sometime in the next couple of days.

**Comment by nightroman** [comment]
I found a universal solution, elegant or not. If a host does not support colors IB quietly recognize this fact and ignores colors on further calls. Please try the current script from the repository. I think it should work fine now. But I am still testing and not publishing a new version.

I am still interested in the name of Azure host.

**Comment by nightroman** [comment]
v2.14.3 should work fine.

**Comment by deevus** [comment]
@nightroman Thanks for this. I haven't had a chance to retry this as I had a busy weekend. Will let you know if I have any issues.

**Comment by nightroman** [comment]
Yes, please, and try to find out the name of Azure host, it may be useful to know.
