### ISSUE TITLE
Use `[System.Management.Automation.Cmdlet]::CommonParameters` to get the names of all common parameters

### ISSUE THREAD

**Issue by daxian-dbw** [nightroman/Invoke-Build#210]
`Invoke-Build` stops working with the latest PowerShell daily build after a new common parameter `ProgressAction` is introduced, see https://github.com/PowerShell/PowerShell/issues/18976 for details.

The root cause turns out to be in the following code, where a hard-coded list of common parameter names are used.
Instead, it should use `[System.Management.Automation.Cmdlet]::CommonParameters`, which is a `Hashset<string>` containing the names of all common parameters.

https://github.com/nightroman/Invoke-Build/blob/3188f22c54cd9b7d4ec7db795bab29ef71e8d557/Invoke-Build.ps1#L115-L117

**Comment by nightroman** [comment]
@daxian-dbw Thank you for the report and the reasonable suggested fix.
Where can I get the latest daily pwsh for playing with this?

**Comment by daxian-dbw** [comment]
I think you can install the daily build by https://github.com/PowerShell/PowerShell/blob/master/tools/install-powershell.ps1. The example shown there is `.\install-powershell.ps1 -Daily`.

**Comment by nightroman** [comment]
Fixed in just released 5.10.3. For now I keep these parameter names hardcoded for a few reasons, so I simply added `ProgressAction`. But I will keep `[System.Management.Automation.Cmdlet]::CommonParameters` in mind for the future.
