### ISSUE TITLE
Invoke-BuildExec should pass the original stderr error to the thrown terminating error

### ISSUE THREAD

**Issue by hanshardmeier** [nightroman/Invoke-Build#218]
Currently Invoke-BuildExec does not forward the original error of the native call as internal error in the terminating error. It forwards the original native call only.  There is also no possibility to configure this:

https://github.com/nightroman/Invoke-Build/blob/10c1f71a1790a7b9eac49cf0aa514743b0377857/Invoke-Build.ps1#L254

Would it make sense to extend the terminating error message with the original native command stderr to allow easier debugging similar to the concept of internal exceptions?

**Comment by hanshardmeier** [comment]
The terminating exception is pretty minimal and useless without the stderr output:

`C:\dev> Invoke-Exec { & test} 2>$null`
`Invoke-Exec: Command exited with code 1. { & test}`

**Comment by nightroman** [comment]
Quick and dirty, something like this

```powershell
function Invoke-BuildExec([Parameter(Mandatory=1)][scriptblock]$Command, [int[]]$ExitCode=0, [string]$ErrorMessage, [string]$StdErr, [switch]$Echo) {
	${private:*c} = $Command
	${private:*x} = $ExitCode
	${private:*m} = $ErrorMessage
	${private:*s} = $StdErr
	${private:*e} = $Echo
	Remove-Variable Command, ExitCode, ErrorMessage, StdErr, Echo
	if (${*e}) {
		*Echo ${*c}
	}

	if (${*s}) {
		& ${*c} 2> ${*s}
	}
	else {
		& ${*c}
	}
	if (${*x} -contains $global:LastExitCode) {return}

	$m = "$(if (${*m}) {"${*m} "})Command exited with code $global:LastExitCode. {${*c}}"
	if (${*s}) {
		$m = $($m; Get-Content ${*s}) | Out-String
	}
	*Die $m 8
}
```

**Comment by nightroman** [comment]
Example
```powershell
task ExacWithStdErr {
	exec { git bar } -StdErr tmp.stderr
}
```

**Comment by nightroman** [comment]
A caller is / will be responsible for choosing the proper and ready file suitable for both `> file` and `Get-Content file`. Caveats:
- it's not literal path, so special chars need escaping
- IB is not going to remove this file
- file must not exist and be hidden or read only
- I'm not sure we should do the same/similar for StdOut (?) (errors may be their, too, it's all up to an app)

I believe it's not IB caprices but the quirks of redirection.

**Comment by nightroman** [comment]
Overall, I am not totally happy with adding all this. But I agree that some straightforward cases may benefit from this. In some others, this may lead to new issues with files, locks, permissions, etc.

**Comment by hanshardmeier** [comment]
There is no direct need to write a file and read it. AFAIK you can separate streams with something like:

	if (${*s}) {
		${*s} = $( $stdout = & ${*c} ) 2>&1
		$stdout
	}

or

	if (${*s}) {
		$stdall= & ${*c} 2>&1
		# Filter stderr
		${*s} = $stdall | ?{$_.gettype().Name -eq "ErrorRecord"}
		# Filter and print stdout
                $stdall | ?{$_.gettype().Name -ne "ErrorRecord"}
	}



Cons:
- You are caching all the stdout output
- `$ErrorPreference` would need to be set to Continue

**Comment by nightroman** [comment]
Thank you, I'll play with this, too.

Q: why do you redirect errors? To avoid terminating errors?
```
Invoke-Exec { & test } 2>$null
```

**Comment by hanshardmeier** [comment]
My biggest use case currently is debugging automatic test scripts. I am not really redirecting errors, but running multiple tests which use native calls throw exceptions to the test process which can be caught, but do not help understand what went wrong. Currently I need to manually read the stderr in the console of the test process (which might be out of order due to parallel tests being executed) to understand what error actually happened.

**Comment by nightroman** [comment]
Capturing all
```powershell
function Invoke-BuildExec([Parameter(Mandatory=1)][scriptblock]$Command, [int[]]$ExitCode=0, [string]$ErrorMessage, [switch]$Echo, [switch]$StdErr) {
	${private:*c} = $Command
	${private:*x} = $ExitCode
	${private:*m} = $ErrorMessage
	${private:*e} = $Echo
	${private:*s} = $StdErr
	Remove-Variable Command, ExitCode, ErrorMessage, Echo, StdErr
	if (${*e}) {
		*Echo ${*c}
	}

	if (${*s}) {
		$ErrorActionPreference = 2
		$o = & ${*c} 2>&1
		$o | Out-String
	}
	else {
		& ${*c}
	}
	if (${*x} -contains $global:LastExitCode) {return}

	$m = "$(if (${*m}) {"${*m} "})Command exited with code $global:LastExitCode. {${*c}}"
	if (${*s}) {
		$m = $($m; foreach($_ in $o) {if ($_ -is [System.Management.Automation.ErrorRecord]) {$_}}) | Out-String
	}
	*Die $m 8
}
```

**Comment by nightroman** [comment]
Example
```powershell
task StdErr2 {
	exec { git bar } -StdErr
}
```

It looks nice in PS Core. In PS Desktop it outputs errors records as formatted errors (it's PS, not IB :)). Not sure how to deal with this or if something should be done.

**Comment by hanshardmeier** [comment]
Thank you, this looks promising. 

We might want to return `$ErrorActionPreference` to its old value after the native call to avoid changing the global state.

Additionally, what do you think of removing the first `if (${*s})` to ensure the console output remains consistent (no stderr) in both cases (with and without the switch)?

**Comment by hanshardmeier** [comment]
Regarding the PS Core vs PS Desktop, you could:

      if (${*s}) {
         $m = $($m; $o | %{if ($_ -is [System.Management.Automation.ErrorRecord]) {$_.Exception.Message}}) 
      }
      
 Should return the same in both cases.

**Comment by nightroman** [comment]
> We might want to return `$ErrorActionPreference` to its old value after the native call to avoid changing the global state.

Setting it changes / creates the local variable and state.

> Additionally, what do you think of

Can you give the example code? To be sure what you suggest.
But I afraid this might be a potentially breaking change even if cases are rare.

> Regarding the PS Core vs PS Desktop, you could:

I believed `Exception` might be null. But the documentation says it's never null. We may try this, yes.

**Comment by nightroman** [comment]
The new parameter help. Is the name all right? Other suggestions?

```
		StdErr = @'
		Tells to capture output and, if the call fails, add the error output to
		the error message. It also sets the $ErrorActionPreference to Continue.
```

**Comment by hanshardmeier** [comment]
Apologies for the delay. I was playing around with this too.

> Setting it changes / creates the local variable and state. We do not have to restore it.

True. My bad.

> Can you give the example code?  

The idea is exactly to avoid making the code semi-breaking. The current solution returns differently depending on the flag. Note that we are not piping stderr but its content is returned via stdout:

Current last proposal:
```pwsh
C:\dev\test> try{ $output = Invoke-BuildExec -Command { & gito bla}}catch{}
C:\dev\test> $output

C:\dev\test> try{ $output = Invoke-BuildExec -Command { & gito bla} -StdErr }catch{}
C:\dev\test> $output
The term 'gito' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

With the proposal below, we would not polute stdout and keep the streams separated while adding the stderr content to the terminating exception:

```pwsh
function Invoke-BuildExec([Parameter(Mandatory=1)][scriptblock]$Command, [int[]]$ExitCode=0, [string]$ErrorMessage, [switch]$Echo, [switch]$StdErr) {
	${private:*c} = $Command
	${private:*x} = $ExitCode
	${private:*m} = $ErrorMessage
	${private:*e} = $Echo
	${private:*s} = $StdErr
	Remove-Variable Command, ExitCode, ErrorMessage, Echo, StdErr
	if (${*e}) {
		*Echo ${*c}
	}

    if(${*s}){
        $ErrorActionPreference = 'Continue'
        $o = & ${*c} 2>&1

        # This is important to keep the order of the logs
        $errors = [System.Collections.ArrayList]@()
        foreach($_ in $o) {
            if ($_ -is [System.Management.Automation.ErrorRecord]) {
                Write-Error $_
                $_ = $errors.Add($_)
            } else {
                $_
            }
        }    
    }else{
        & ${*c}
    }
    if (${*x} -contains $global:LastExitCode) {return}

	$m = "$(if (${*m}) {"${*m} "})Command exited with code $global:LastExitCode. {${*c}}"
	if (${*s}) {
		$m = @($m; foreach($_ in $errors) {$_.Exception.Message}) -join "`n"
	}
	*Die $m 8
}
```


In theory we could also remove the first ` if(${*s})` as we are returning the same in both cases. The only difference is how the error messages are displayed in stderr:

```pwsh
C:\dev\test> Invoke-BuildExec -Command { & git bla}
git: 'bla' is not a git command. See 'git --help'.

The most similar command is
        blame
Invoke-BuildExec: Command exited with code 1. { & git bla}

C:\dev\test> Invoke-BuildExec -Command { & git bla} -StdErr
Invoke-BuildExec: git: 'bla' is not a git command. See 'git --help'.
Invoke-BuildExec:
Invoke-BuildExec: The most similar command is
Invoke-BuildExec:       blame
Invoke-BuildExec: Command exited with code 1. { & git bla}
git: 'bla' is not a git command. See 'git --help'.

The most similar command is
        blame
```
We might leave it though (as in my proposal) to avoid unexpected breaking changes. 

What do you think'

**Comment by nightroman** [comment]
It looks reasonable, let me try and think.

**Comment by nightroman** [comment]
Have you tried? It seems `Write-Error $_` produces not very nice output in both Desktop and Core.

**Comment by hanshardmeier** [comment]
My last snippet in the last comment is the output that I got with the proposed solution (pwsh 7.3.11). Is there another way to write to stderr?

**Comment by hanshardmeier** [comment]
Alternatively, we can simply avoid printing the errors to the console via Write-Error as they will be duplicated either way in the exception.

**Comment by hanshardmeier** [comment]
Fair enough. Might be important to document that the exit code is important in those cases too.

Without the Write-Error it intuitively feels like the stderr output moves to the exception:

```pwsh
C:\dev\test> try { Invoke-BuildExec -Command { & git bla} -StdErr -ErrorMessage "Custom Message" } catch{$_}
Invoke-BuildExec: Custom Message Command exited with code 1. { & git bla}
git: 'bla' is not a git command. See 'git --help'.

The most similar command is
        blame
C:\dev\test> try { Invoke-BuildExec -Command { & git bla} -ErrorMessage "Custom Message" } catch{$_}
git: 'bla' is not a git command. See 'git --help'.

The most similar command is
        blame
Invoke-BuildExec: Custom Message Command exited with code 1. { & git bla}
```

**Comment by nightroman** [comment]
I see a problem. With `$ErrorActionPreference` set to Continue, invalid commands (like gito) do not fail in PS and they do not set `$LastExitCode` to 1 either. How do we know it's a failure then?

**Comment by nightroman** [comment]
Here is the latest, note the added try/catch around the call, this catch "Command is not found" (and other non-native-app-call errors). Other errors (native-app-errors) are printed as usual output and, if `LastExitCode` is failure, added to the error message.

```pwsh
function Invoke-BuildExec([Parameter(Mandatory=1)][scriptblock]$Command, [int[]]$ExitCode=0, [string]$ErrorMessage, [switch]$Echo, [switch]$StdErr) {
	${private:*c} = $Command
	${private:*x} = $ExitCode
	${private:*m} = $ErrorMessage
	${private:*e} = $Echo
	${private:*s} = $StdErr
	Remove-Variable Command, ExitCode, ErrorMessage, Echo, StdErr
	if (${*e}) {
		*Echo ${*c}
	}

	$global:LastExitCode = 0
	if (${*s}) {
		$ErrorActionPreference = 2
		$o = try {& ${*c} 2>&1} catch {throw}
		$e = @()
		foreach($_ in $o) {
			if ($_ -is [System.Management.Automation.ErrorRecord]) {
				$_ = $_.Exception.Message
				$e += $_
			}
			$_
		}
	}
	else {
		& ${*c}
	}
	if (${*x} -contains $global:LastExitCode) {return}

	$m = "$(if (${*m}) {"${*m} "})Command exited with code $global:LastExitCode. {${*c}}"
	if (${*s}) {
		$m = @($m; $e) -join "`n"
	}
	*Die $m 8
}
```

**Comment by hanshardmeier** [comment]
With `$_ = $_.Exception.Message` we are still poluting stdout with stderr messages. 

Do we want to go into that direction to still have some kind of error logs outside the exception?

Also here we still have the error formatting issue in PS Desktop in the exception, isn't it?

**Comment by nightroman** [comment]
If you run the same "bad command" in the console directly you will see both output and errors. Same as in `exec`. It's rather a good thing, IMHO.

**Comment by nightroman** [comment]
So you suggest moving stderr to the exec error completely, right?
But what if an app has stderr (verbose info, etc) but does not fail (non zero code). This output will be missed then.

**Comment by nightroman** [comment]
In my opinion, `exec` should preserve the visual appearance of console output, stdout and stderr, with proper order, while helping to get errors to the `exec` error message. That's all.

Preserving actual stdout and stderr of a particular task in a build, and trying doing this in PowerShell (with all its quirks and different versions), it's out of the scope of `exec`.

**Comment by nightroman** [comment]
But my way of using IB may be not same as yours and you may know and want something that I do not. We may replace the switch `StdErr` with a parameter with value explaining how it should be handled.

**Comment by nightroman** [comment]
One at a time.

>We are not manipulating the verbose or info streams.

I am not talking about PS verbose stream. I am talking about a native app using stderr for some "verbose"/extra output.

**Comment by nightroman** [comment]
> Isn't the exception automatically thrown? Why catch it and throw it?

Note that we set `$ErrorActionPreference = 'Continue'`

Compare
```pwsh
$ErrorActionPreference = 'Continue'
foobar
'this should not happen!'
```
-- 'this should not happen!' happens
and

```pwsh
$ErrorActionPreference = 'Continue'
try {foobar} catch {throw}
'this should not happen!'
```
-- 'this should not happen!' does not happen

**Comment by nightroman** [comment]
> I like the switch and its simplicity. No need to make it more complicated IMHO

I agree the switch should be enough and documented properly. So far it is
```
		StdErr = @'
		Tells to set $ErrorActionPreference to Continue, capture all output and
		write as strings. Then, if the exit code is failure, add the standard
		error output text to the error message.
```

**Comment by hanshardmeier** [comment]
Thank you very much for the responsiveness and great collaboration. This is a great tool and I am glad you see the usefulness of this feature request.

**Comment by nightroman** [comment]
@hanshardmeier Thank you for the useful feature suggestion and your patience on discussing this.
Please let me sleep on this a little bit and test more before releasing. It's a tricky area with dragons.

**Comment by hanshardmeier** [comment]
Let me know if you need help discussing this further. Glad if I can help.

**Comment by nightroman** [comment]
v5.11.0 is out there, please let me know how it goes.
The final changes in `exec`:
- simplified error message building
- process output and pass through immediately
