### ISSUE TITLE
echo output of exec {} block prints out entire parent object of a parameter when property of an object passed as parameter

### ISSUE THREAD

**Issue by jaccus** [nightroman/Invoke-Build#221]
IB supports enabling a printout of all parameters passed to the native command when wrapped in an exec {} block.

E.g. invoking this code:
```
$PSDefaultParameterValues = @{'Invoke-BuildExec:Echo' = $true }
$p1 = "valuep1"
$p2 = "valuep2"
exec {
   & tool.exe $p1 $p2
}
```
will print out something like this:
```
exec {
    & tool.exe $p1 $p2
}
cd C:\path
$p1: valuep1
$p2: valuep2
```

In a scenario where nested object is passed as a parameter, e.g.:
```
$PSDefaultParameterValues = @{'Invoke-BuildExec:Echo' = $true }
$p1 = [PSCustomObject]@{ Subitem = "valuep1" }
$p2 = "valuep2"
exec {
   & tool.exe $p1.Subitem $p2
}
```

prints out entire p1 object:

```
exec {
   & tool.exe $p1.Subitem $p2
}
cd C:\path
$p1: @{Subitem=valuep1}
$p2: valuep2
```

I would expect to see only `$p1.Subitem` printed out, however entire $p1 object is (which may be huge). In this example, only value of `$p1.Subitem` is relevant to the invoked command, therefore would think that current behavior is not optimal. 

Proposing to change this behavior to only print content of parameter passed to the command, not entire object of which the parameter is a property of.

**Comment by nightroman** [comment]
@jaccus I hear you. For what's it wort, the current behaviour is by design and actually thought through. `-echo` discovers and prints used **variables**, not **expressions**,  and avoids dynamic evaluation of expressions, for performance or side effect reasons.

Let me think if we can "easily and safely" make exception for properties and echo expressions like `$var.property`.

**Comment by nightroman** [comment]
After some experiments, perhaps we may support (evaluate / print) member expressions with variables, as suggested.
I'll think and test some more and get back.

**Comment by nightroman** [comment]
Done in v5.11.3, thank you for the good idea.
