### ISSUE TITLE
Incorrect sequence of tasks in the summary

### ISSUE THREAD

**Issue by pkudrel** [nightroman/Invoke-Build#25]
IB version: 2.14.6
After executing the build script with task parameter "-After", summary has incorrect order.

Example
```powershell
# run.ps1

try {
    # Invoke the build and keep results in the variable Result
    Invoke-Build .  -Result Result
}
finally {
    # Show task summary information after the build
    $Result.Tasks | Format-Table Elapsed, Name, Error -AutoSize
}
```

```powershell
# test.build.ps1

task Clean {
	Write-Host "Clean"
}
task Build {
	Write-Host "Build"
}

task Build-After -After Build {
	Write-Host "Build-After"
}

task . Clean, Build
```

```
# result

> .\run.ps1
Build . test.build.ps1
Task /./Clean
Clean
Done /./Clean 00:00:00.0040157
Task /./Build
Build
Task /./Build/Build-After
Build-After
Done /./Build/Build-After 00:00:00.0035095
Done /./Build 00:00:00.0075210
Done /. 00:00:00.0155475
Build succeeded. 4 tasks, 0 errors, 0 warnings 00:00:00.0260102

Elapsed          Name        Error
-------          ----        -----
00:00:00.0040157 Clean
00:00:00.0035095 Build-After
00:00:00.0075210 Build
00:00:00.0155475 .
```

**Comment by nightroman** [comment]
It may look confusing at first but all is correct. By design, a task is added to the list when it is done. The task `Build-After` is invoked *after* all jobs of `Build`. But it is done *before* the task `Build` is done.

The task
```
task Build-After -After Build ...
```

transforms the original `Build` into this:
```
task Build {
    Write-Host "Build"
},
Build-After
```

When you invoke `Build` things are processed in this order:
- Begin `Build`
    - Invoke 1st job, it is the script block
    - Invoke 2nd job, it is the task `After-Build`
        - Begin `After-Build`
        - End `After-Build`, now it is added to the list
- End `Build`, now it is added to the list

**Comment by pkudrel** [comment]
Thank you for clarification. That make sense. I'm closing the issue. 

PS: Great job with this project.
