### ISSUE TITLE
Another IB-Based Project for your list

### ISSUE THREAD

**Issue by zloeber** [nightroman/Invoke-Build#30]
I've taken a module build script I created for one of my projects and turned it into a more generic scaffolding for PowerShell module builds. It's capable of setting up the initial module framework, building/combining the module into a single source psm1, running PSScriptAnalyzer, publishing to the powershell gallery, and other such fun. Hopefully I didn't totally bastardize the intended purpose of IB too much :) Anyway, it is fairly [usable and reasonably documented at this point](https://github.com/zloeber/PSModuleBuild). Thanks again for such a useful build engine!

**Comment by nightroman** [comment]
I am aware of this project and looking forward to its development.

> Hopefully I didn't totally bastardize the intended purpose of IB too much

Not at all. It is exactly one of the purposes. Users can use it as it is or build whatever they want on top of it. There are several known tools built on top of IB.

As far as PSModuleBuild is ready, I will add it to the list shortly. If you prefer a particular annotation, please let me know. Or I will copy/paste from README.

**Comment by nightroman** [comment]
Added to [Related-Projects](https://github.com/nightroman/Invoke-Build/wiki/Related-Projects).
