### ISSUE TITLE
OSS Posh: ConsoleColor Assembly Issues

### ISSUE THREAD

**Issue by zloeber** [nightroman/Invoke-Build#31]
In answer to a comment you left on my blog here is the error I get when I try to run Invoke-Build.ps1 on Powershell 6.0 on my linux test server. I cannot dig into this just right now to find the equivalent .Net Core namespaces but I'll try to take a peek a bit later.

> Add-Type : (9) : The type or namespace name 'ConsoleColor' could not be found (are you missing a using directive or an assembly reference?)
(8) :   static public void RC() {if (_u != null) {try {_u.ForegroundColor = _c;} catch {}}}
(9) : >>>       static public void SC(ConsoleColor c) {if (_u != null) {try {_c = _u.ForegroundColor; _u.ForegroundColor = c;} catch {_u = null;}}}
(10) :  static public object List() {return new List<object>();}
At /vagrant/Invoke-Build/Invoke-Build.ps1:204 char:1
+ Add-Type @'
+ ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Power...peCompilerError:AddTypeCompilerError) [Add-Type], Exception
    + FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand

Add-Type : (5) : The type or namespace name 'ConsoleColor' could not be found (are you missing a using directive or an assembly reference?)
(4) : public class IB {
(5) : >>>       [ThreadStatic] static ConsoleColor _c;
(6) :   [ThreadStatic] static PSHostRawUserInterface _u;
At /vagrant/Invoke-Build/Invoke-Build.ps1:204 char:1
+ Add-Type @'
+ ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Power...peCompilerError:AddTypeCompilerError) [Add-Type], Exception
    + FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand

Add-Type : (8) : The type 'ConsoleColor' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Console, Version=4.0.0.0, Culture=neutral,
PublicKeyToken=b03f5f7f11d50a3a'.
(7) :   static public void Init(PSHost h) {if (h.UI != null) _u = h.UI.RawUI;}
(8) : >>>       static public void RC() {if (_u != null) {try {_u.ForegroundColor = _c;} catch {}}}
(9) :   static public void SC(ConsoleColor c) {if (_u != null) {try {_c = _u.ForegroundColor; _u.ForegroundColor = c;} catch {_u = null;}}}
At /vagrant/Invoke-Build/Invoke-Build.ps1:204 char:1
+ Add-Type @'
+ ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Power...peCompilerError:AddTypeCompilerError) [Add-Type], Exception
    + FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand

Add-Type : (9) : The type 'ConsoleColor' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Console, Version=4.0.0.0, Culture=neutral,
PublicKeyToken=b03f5f7f11d50a3a'.
(8) :   static public void RC() {if (_u != null) {try {_u.ForegroundColor = _c;} catch {}}}
(9) : >>>       static public void SC(ConsoleColor c) {if (_u != null) {try {_c = _u.ForegroundColor; _u.ForegroundColor = c;} catch {_u = null;}}}
(10) :  static public object List() {return new List<object>();}
At /vagrant/Invoke-Build/Invoke-Build.ps1:204 char:1
+ Add-Type @'
+ ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Power...peCompilerError:AddTypeCompilerError) [Add-Type], Exception
    + FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand

Add-Type : (9) : The type 'ConsoleColor' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Console, Version=4.0.0.0, Culture=neutral,
PublicKeyToken=b03f5f7f11d50a3a'.
(8) :   static public void RC() {if (_u != null) {try {_u.ForegroundColor = _c;} catch {}}}
(9) : >>>       static public void SC(ConsoleColor c) {if (_u != null) {try {_c = _u.ForegroundColor; _u.ForegroundColor = c;} catch {_u = null;}}}
(10) :  static public object List() {return new List<object>();}
At /vagrant/Invoke-Build/Invoke-Build.ps1:204 char:1
+ Add-Type @'
+ ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Power...peCompilerError:AddTypeCompilerError) [Add-Type], Exception
    + FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand

Add-Type : Cannot add type. Compilation errors occurred.
At /vagrant/Invoke-Build/Invoke-Build.ps1:204 char:1
+ Add-Type @'
+ ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-Type], InvalidOperationException
    + FullyQualifiedErrorId : COMPILER_ERRORS,Microsoft.PowerShell.Commands.AddTypeCommand

Unable to find type [IB].
At /vagrant/Invoke-Build/Invoke-Build.ps1:217 char:1
+ [IB]::Init($Host)
+ ~~~~
    + CategoryInfo          : InvalidOperation: (IB:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

/vagrant/Invoke-Build/Invoke-Build.ps1 : Unable to find type [IB].
At line:1 char:1
+ ./Invoke-Build.ps1
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (IB:TypeName) [Invoke-Build.ps1], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound,Invoke-Build.ps1

**Comment by nightroman** [comment]
I suspected as much. What do you get with this command:

    $Host.UI.RawUI | gm

**Comment by zloeber** [comment]
Hello,

```
PS /home/ubuntu> $Host.UI.RawUI | gm


   TypeName: System.Management.Automation.Internal.Host.InternalHostRawUserInterface

Name                  MemberType Definition
----                  ---------- ----------
Equals                Method     bool Equals(System.Object obj)
FlushInputBuffer      Method     void FlushInputBuffer()
GetBufferContents     Method     System.Management.Automation.Host.BufferCell[,] GetBufferContents(System.Management.Automation.Host.Rectangle r)
GetHashCode           Method     int GetHashCode()
GetType               Method     type GetType()
LengthInBufferCells   Method     int LengthInBufferCells(string str), int LengthInBufferCells(string str, int offset), int LengthInBufferCells(char character)
NewBufferCellArray    Method     System.Management.Automation.Host.BufferCell[,] NewBufferCellArray(string[] contents, System.ConsoleColor foregroundColor, System.ConsoleColor backgroundColor), Sy... ReadKey               Method     System.Management.Automation.Host.KeyInfo ReadKey(System.Management.Automation.Host.ReadKeyOptions options), System.Management.Automation.Host.KeyInfo ReadKey()
ScrollBufferContents  Method     void ScrollBufferContents(System.Management.Automation.Host.Rectangle source, System.Management.Automation.Host.Coordinates destination, System.Management.Automati... SetBufferContents     Method     void SetBufferContents(System.Management.Automation.Host.Coordinates origin, System.Management.Automation.Host.BufferCell[,] contents), void SetBufferContents(Syst... ToString              Method     string ToString()
BackgroundColor       Property   System.ConsoleColor BackgroundColor {get;set;}
BufferSize            Property   System.Management.Automation.Host.Size BufferSize {get;set;}
CursorPosition        Property   System.Management.Automation.Host.Coordinates CursorPosition {get;set;}
CursorSize            Property   int CursorSize {get;set;}
ForegroundColor       Property   System.ConsoleColor ForegroundColor {get;set;}
KeyAvailable          Property   bool KeyAvailable {get;}
MaxPhysicalWindowSize Property   System.Management.Automation.Host.Size MaxPhysicalWindowSize {get;}
MaxWindowSize         Property   System.Management.Automation.Host.Size MaxWindowSize {get;}
WindowPosition        Property   System.Management.Automation.Host.Coordinates WindowPosition {get;set;}
WindowSize            Property   System.Management.Automation.Host.Size WindowSize {get;set;}
WindowTitle           Property   string WindowTitle {get;set;}

PS /home/ubuntu> $Host.UI.RawUI


ForegroundColor       : -1
BackgroundColor       : -1
CursorPosition        : 0,48
WindowPosition        : 0,0
CursorSize            : 100
BufferSize            : 200,49
WindowSize            : 200,49
MaxWindowSize         : 200,49
MaxPhysicalWindowSize : 200,49
KeyAvailable          : False
WindowTitle           :
```

**Comment by zloeber** [comment]
I reduced some of the errors but got to an impasse with the PSHost requirement.

Code changes:
```
Add-Type -referencedAssemblies 'System.Console' -TypeDefinition @'
using System;
using System.Collections.Generic;

public class IB {
	[ThreadStatic] static ConsoleColor _c;
	[ThreadStatic] static PSHostRawUserInterface _u;
	static public void Init(PSHost h) {if (h.UI != null) _u = h.UI.RawUI;}
	static public void RC() {if (_u != null) {try {_u.ForegroundColor = _c;} catch {}}}
	static public void SC(ConsoleColor c) {if (_u != null) {try {_c = _u.ForegroundColor; _u.ForegroundColor = c;} catch {_u = null;}}}
	static public object List() {return new List<object>();}
}
'@
[IB]::Init($Host)
```
Resulting error on a test build with a few small tasks:
```
PS /vagrant> ./Invoke-Build.ps1
Add-Type : (7) : The type or namespace name 'PSHost' could not be found (are you missing a using directive or an assembly reference?)
(6) :   [ThreadStatic] static PSHostRawUserInterface _u;
(7) : >>>       static public void Init(PSHost h) {if (h.UI != null) _u = h.UI.RawUI;}
(8) :   static public void RC() {if (_u != null) {try {_u.ForegroundColor = _c;} catch {}}}
At /vagrant/Invoke-Build.ps1:203 char:1
+ Add-Type -referencedAssemblies 'System.Console' -TypeDefinition @'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Power...peCompilerError:AddTypeCompilerError) [Add-Type], Exception
    + FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand

Add-Type : (6) : The type or namespace name 'PSHostRawUserInterface' could not be found (are you missing a using directive or an assembly reference?)
(5) :   [ThreadStatic] static ConsoleColor _c;
(6) : >>>       [ThreadStatic] static PSHostRawUserInterface _u;
(7) :   static public void Init(PSHost h) {if (h.UI != null) _u = h.UI.RawUI;}
At /vagrant/Invoke-Build.ps1:203 char:1
+ Add-Type -referencedAssemblies 'System.Console' -TypeDefinition @'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Power...peCompilerError:AddTypeCompilerError) [Add-Type], Exception
    + FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand

Add-Type : Cannot add type. Compilation errors occurred.
At /vagrant/Invoke-Build.ps1:203 char:1
+ Add-Type -referencedAssemblies 'System.Console' -TypeDefinition @'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-Type], InvalidOperationException
    + FullyQualifiedErrorId : COMPILER_ERRORS,Microsoft.PowerShell.Commands.AddTypeCommand

Unable to find type [IB].
At /vagrant/Invoke-Build.ps1:216 char:1
+ [IB]::Init($Host)
+ ~~~~
    + CategoryInfo          : InvalidOperation: (IB:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

/vagrant/Invoke-Build.ps1 : Unable to find type [IB].
At line:1 char:1
+ ./Invoke-Build.ps1
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (IB:TypeName) [Invoke-Build.ps1], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound,Invoke-Build.ps1
```

**Comment by nightroman** [comment]
We have to find the assembly of `$Host.UI.RawUI` and also add it to the
referenced assemblies. And so on with other troublesome types.

Please take a look at

````powershell
    $Host.UI.RawUI.GetType().Assembly | Format-List *
````

and/or

````powershell
    function Get-AssemblyPath($obj) {$obj.GetType().Assembly.Location}
    Get-AssemblyPath $Host
    Get-AssemblyPath $Host.UI
    Get-AssemblyPath $Host.UI.RawUI
````

It looks like using `Add-Type` is fragile, at least at this point. It makes
sense to think of removing it from `Invoke-Build`. If you cannot resolve the
errors by adding missing referenced assemblies then try the older
`Invoke-Build.ps1` (v2.14.2) which does not use `Add-Type` yet:

https://github.com/nightroman/Invoke-Build/blob/v2.14.2/Invoke-Build.ps1

It would be very useful to know what the next problem is.
It might be something related to used wrong slashes in paths.

**Comment by nightroman** [comment]
On the other hand, `Add-Type` has many opened issues and hopefully many of they will be resolved. For example, this one also mentions `ConsoleColor`: https://github.com/PowerShell/PowerShell/issues/1616

I believe `Add-Type` should add more assemblies to default referenced.
At least types used in public PowerShell API should be covered.

So it makes sense to concentrate on potential issues other than `Add-Type` and try the older Invoke-Build v2.14.2.

**Comment by nightroman** [comment]
@zloeber, in a few hours I will commit fixes for known and potential issues. I hope you can help me with testing it.

**Comment by zloeber** [comment]
I'll try to test today. I've dug into the .Net core libraries and am fairly certain that PSHost is not part of them. I'm not as fluent with custom powershell hosts as I probably should be at this point but is there any way to code our way around this requirement? 

Add-Type has many interesting issues and is powerful but painful at the same time :)

**Comment by nightroman** [comment]
Please try the current script and let me know the result. I removed Add-Type and fixed a few slashes.

**Comment by zloeber** [comment]
And a successful build!
```
PS /vagrant> ./Invoke-Build.ps1
Build . /vagrant/.build.ps1
Task /.
 Are we configured here?...Yup!
Task /.
 Are we configured here?...Yup!
Done /. 00:00:00.0427840
Build succeeded. 1 tasks, 0 errors, 0 warnings 00:00:00.1943410
```

Congrats, this is probably the first useful posh project to get cross platform :).

**Comment by nightroman** [comment]
Thank you! This would take much longer without your report and help. I think the story is not over yet and there will be issues. But the first working build is a great step forward.
