### ISSUE TITLE
ArgumentCompleters not working on Task argument

### ISSUE THREAD

**Issue by kuulemart** [nightroman/Invoke-Build#33]
Hi!

Invoke-Build.ArgumentCompleters seems to have problem with completing Task argument values. 
Invoke-Build and was installed under CurrentUser with Install-Module. Tried using Invoke-Build.ArgumentCompleters both with Install-Script and Save-Script but didn't work either way.

Quick fix is to modify Invoke-Build.ArgumentCompleters.ps1 and change first call to Register-ArgumentCompleter to use Invoke-Build instead of $commandName to find completions:

Register-ArgumentCompleter -CommandName Invoke-Build.ps1 -ParameterName Task -ScriptBlock {
    param($commandName, $parameterName, $wordToComplete, $commandAst, $boundParameters)
    $commandName = "Invoke-Build"
    (& $commandName ?? -File ($boundParameters['File'])).Keys -like "$wordToComplete*" | .{process{
        New-Object System.Management.Automation.CompletionResult $_, $_, 'ParameterValue', $_
    }}
}

Best regards and keep up good work!

Egon

**Comment by nightroman** [comment]
Hi Egon,

Thank you for the reported issue and the proposed fix. I will investigate and correct soon.

I have to admit that IB installed as a module is relatively new and less tested. I am using it as a script in the path, the original and still preferred scenario. That is why I missed the issue.

**Comment by nightroman** [comment]
The proposed fix works in both configurations (module/script). I applied it.

Some side thoughts. It would be nice if the code completion engine provided the resolved command as `$commandName` for completers. The fix would not be needed and the completer would work for a standalone script not in the path, too (presumably it is not working now).
