### ISSUE TITLE
Invoke-BuildExec propagates exit code

### ISSUE THREAD

**Issue by lsgroi** [nightroman/Invoke-Build#34]
Explicitly define valid exit codes does not stop the overall script to fail.

```
Task . {
	# Arrange
	if (Test-Path src) { Remove-Item -Path src -Recurse -Force }
	if (Test-Path dest) { Remove-Item -Path dest -Recurse -Force }
	$src = New-Item -Name src -ItemType Directory
	$dest = New-Item -Name dest -ItemType Directory
	Set-Content -Path (Join-Path $src "foo.txt") -Value "foo content"
	
	# Act
	Exec { Robocopy src dest foo.txt /256 /XO /NP /NFL /NDL /NJH /NJS } (0..7)
	
	# Assert
	"LASTEXITCODE is $LASTEXITCODE"
}
```

In this case, Invoke-Build succeed but the global exit code is 1 due to Robocopy, therefore the overall script fails. This is the case on my CI server which expect the PowerShell script executed to exit 0

Perhaps Invoke-BuildExec should return 0 if the exit code is within the valid range?

The workaround is having ``$global:LastExitCode = $null`` after each ``Exec { Robocopy ... }`` which is not ideal

**Comment by nightroman** [comment]
`$LASTEXITCODE` is not supposed to be used with Invoke-Build for detecting errors. Invoke-Build is a PowerShell tool, not CMD. Please take a look at [wiki/Build-Failures](https://github.com/nightroman/Invoke-Build/wiki/Build-Failures).

Could you please describe how you call Invoke-Build and detect errors? Why do you use `$LASTEXITCODE`? If the recommended ways are not suitable, explain why, and let's see how we can improve this.

**Comment by lsgroi** [comment]
I am using Visual Studio Team Services build pipeline, in which I use the PowerShell task to invoke the build

```
.\Invoke-Build.ps1 MyBuildTask
```

The overall task will rely solely on $LASTEXITCODE and the exit code to determine failure, which is 1 in case of a successful Robocopy and therefore the task fails.

I could add something like 
```
if (-not $Result.Error) { $global:LastExitCode = $null }
```

Perhaps VSTS is detecting PowerShell errors incorrectly.

**Comment by nightroman** [comment]
Try to add `exit 0` after the line 667,  as shown:
````powershell
	finally {
		${*}.Task = $null
		. *UC Exit-Build
	}
	${*r} = 1
	exit 0
}
catch {
	${*r} = 2
	*AE ${*}.Task
````
Please let me know if it helps.

**Comment by nightroman** [comment]
Alternatively, you can use `ib.cmd` from the package. It is designed for exactly this scenario.

Anyway, if `exit 0` helps then I will add it to the script.

**Comment by lsgroi** [comment]
Adding ``exit 0`` does fix the issue.

I broadly tested against assertions and ``Invoke-BuildExec`` and it seems to keep the original behaviours but fix the problem I am facing.

It would be great if you could add it to the next release.

**Comment by nightroman** [comment]
It's done. Thank you for reporting this issue.
