### ISSUE TITLE
Support mstest

### ISSUE THREAD

**Issue by lzybkr** [nightroman/Invoke-Build#39]
The `use 4.0 msbuild` syntax is very nice.

It might be useful to support `mstest` similarly.

**Comment by nightroman** [comment]
It is a good idea. I think it should be support for all Visual Studio tools
with `mstest` included, as a result. Yet another potentially useful is `tf`,
for example.

I am thinking of this syntax:

````powershell
    use VisualStudio\14.0 mstest
    use VisualStudio\14.0 tf
    use VisualStudio\14.0 mstest, tf
````

So that the conventional path `VisualStudio\<version>` is resolved via the registry:

````powershell
    function Use-BuildAlias([Parameter(Mandatory=1)][string]$Path, [string[]]$Name) {
        ....
        $d = switch -regex ($Path) {
            ...
            '^VisualStudio\\' {[Microsoft.Win32.Registry]::GetValue("HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\$_", 'InstallDir', '')}
            ...
        }
        ...
    }
````

This is Visual Studio and Windows specific, of course. But Visual Studio
tools are important enough for this special build engine convention.

Thoughts, other suggestions?

**Comment by nightroman** [comment]
Done in v3.2.0
https://github.com/nightroman/Invoke-Build/commit/c7c629e13af75d54a37ff155c20a8dbc6b9d1c36

**Comment by nightroman** [comment]
@lzybkr 

I am thinking of removing this feature. So far it is declared:
https://github.com/nightroman/Invoke-Build/blob/master/Release-Notes.md

- It is not used, per build scripts on GitHub watched for a long time.
- It does not work with VS 2017 (as you know, they changed the rules).

I would not mind to support it for VS 2017+ (something like `Resolve-MSBuild`). But I am not sure if this really needed for this *task runner*. I have doubts even about `Resolve-MSBuild` but at least it is actively used by many.

What are your thoughts if you have any?

**Comment by lzybkr** [comment]
I never ended up using it, my tests failed for unknown reasons when run outside of Visual Studio and debugging was quite difficult, so I lived with manual testing.

I should move to xunit anyway so the tests run cross platform.

**Comment by nightroman** [comment]
Yeah, and not cross platform is another shortcoming, indeed.
Anyway, I will keep it deprecated but available for quite a long time. Things/thoughts may change.
