### ISSUE TITLE
EXIT in ib.cmd should use /B

### ISSUE THREAD

**Issue by fdcastel** [nightroman/Invoke-Build#52]
All `EXIT` commands from `ib.cmd` wrapper should use `/B` option to avoid quitting the current `CMD.EXE`.

**Problem:**

1) Open a `cmd.exe` session in a folder containing `Invoke-Build` and `ib.cmd`.

2) Run `ib /?`

The current console will close.

**Solution:**

Replace `exit` with `exit /B 0` in `:list` and `:help` sections.

**Environment:**

```
Microsoft Windows [Version 10.0.14393]
PSVersion 5.1.14393.693
```

**Comment by nightroman** [comment]
@fdcastel Thank you for the reasonable suggestion. Will do shortly.
