### ISSUE TITLE
Error "the type name 'IB' already exists" when running back-to-back builds

### ISSUE THREAD

**Issue by gregmajor** [nightroman/Invoke-Build#53]
Hello! I've got several projects that use `Invoke-Build` and I'd like to run them back-to-back from my own Powershell script. However, when I attempt to do so I get the error:

`Cannot add type. The type name 'IB' already exists.`

My script looks basically like this:

```Powershell
cd 'C:\BuildA'
& .\Invoke-Build.ps1
cd 'C:\BuildB'
& .\Invoke-Build.ps1
```

I'm a bit of a Powershell neophyte so the solution is probably quite obvious. What would you recommend to avoid this error?

Greg

**Comment by nightroman** [comment]
Hi Greg,

You are probably using the older version of the script. The type `IB` was
removed for another reason, #31. It's good to know this also resolved
problems like yours.

In other words, use the latest `Invoke-Build.ps1`.

**Comment by gregmajor** [comment]
That did the trick. Thanks!

Greg
