### ISSUE TITLE
Unhelpful "Invalid script syntax? [1,1]"

### ISSUE THREAD

**Issue by vorou** [nightroman/Invoke-Build#56]
If I have a task:

```
task Restore {
  aba
}
```

I will get a typical `aba : The term 'aba' is not recognized as the name of a cmdlet...`.
But if have it like this:

```
task Restore {
  'aba' aba
}
```

IB will give me a mysterious `Invalid script syntax? At line:1 char:1`. Is it possible to be more clear in that case?

Got it when was trying to invoke NuGet like this: `exec { $NuGet restore $Sln}`, had to comment-uncomment all the lines one by one to find the problem.

**Comment by nightroman** [comment]
I am aware of this unpleasant "feature". It is not that simple. As far as I now have the report, I'll think again and try to improve something.

Meantime, when you see such an error next time, do not guess anything, just invoke your script directly in PowerShell, i.e. without IB. This will tell where the *syntax* error is.

**Comment by nightroman** [comment]
The fix is being tested and will be released in the coming days if all is fine.

**Comment by vorou** [comment]
Wow, it was fast. Thank you.
