### ISSUE TITLE
Error Action Pt2 :)

### ISSUE THREAD

**Issue by lanrongwen** [nightroman/Invoke-Build#61]
Sorry for the late reply - long weekend. :)

I have tried doing all of those before I opened the issue.  Let me add some more context to see if I can clarify the question:
I have a Jenkins job that kicks Invoke-Build.  In the build script it queries another system (that I don't control).  If the system can't find the items, rather than return null it throws an error of No Items Found.  I have attempted to do the following:

- Change the Error Action Preference before running the command.
- Try Catch Blocks
- Trap the Error
- Use the Commandlet -ErrorAction property

In each case it still sees the error and stops the script reporting there was an error in the build task.

```powershell
    task traperroraction {
        $olderrorpref = $ErrorActionPreference
        $ErrorActionPrefrence = "Ignore"
        try{
            $updatestatus = -ErrorAction Ignore
        }
        catch{
            $updatestatus = $Null
        }
        $ErrorActionPrefrence = $olderrorpref
    }
```

Maybe the issue is Jenkins, but it appears to be Invoke-Build:

```
<task stack trace>
Build FAILED. 7 tasks, 1 errors, 0 warnings 00:00:29.1796869
You cannot call a method on a null-valued expression.
```

**Comment by nightroman** [comment]
I cannot help without more details. Some thoughts:

(1) In your code there is a typo in the variable name `$ErrorActionPrefrence`.
If this is copied/pasted from your real code then this may be the reason.
Replace *Prefrence* with *Preference*.

(2) What is the full error message? It should normally point to the place of failure.
Try also to examine all errors in the global `$Error`. It may contain some hints
not shown in the "final" error message that technically stops the build.

(3) "You cannot call a method on a null-valued expression." - I have no idea where
it comes from. The provided code does not have any method calls. Examine your
code for potential $null values (including typos in variable names).

**Comment by lanrongwen** [comment]
Hmm...  Let me dig a little more and see what I can find.  I wish I could share the raw code, but that is the bulk of the code in question (outside the actual command). The main point is that setting either -ErrorAction parameter or $ErrorActionPrefrence should do the trick for Invoke-Build, correct?

**Comment by nightroman** [comment]
> The main point is that setting either -ErrorAction parameter or $ErrorActionPrefrence should do the trick for Invoke-Build, correct?

I afraid, no.

Does your scenario work outside Invoke-Build?

**Comment by lanrongwen** [comment]
It does if I use "SilentlyContinue" and not Ignore...

**Comment by lanrongwen** [comment]
Ok, this can close.  Turns out that it was working correctly, and the try/catch or erroraction was working.  There was an error later on, but the logging in Jenkins made it confusing as to where the error was...  Sorry for the hassle. :)

**Comment by nightroman** [comment]
@lanrongwen No problem at all. You may let the Jenkins team know about the confusing error if it can be improved.
