### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by majkinetor** [nightroman/Invoke-Build#62]
FYI, I created a chocolatey package that is mirroring PowershellGallery module. Module is available via `cinst invoke-build`

Package: https://chocolatey.org/packages/invoke-build
Source: https://github.com/majkinetor/au-packages/tree/master/invoke-build

(will be approved in few hours)

Module is automatic and will follow Gallery releases within a single day:
https://gist.github.com/majkinetor/a700c70b8847b29ebb1c918d47ee4eb1#invoke-build

**Comment by nightroman** [comment]
@majkinetor Thank you very much for taking care of this. Please let me know what is needed from me. From your description, it looks like not much, if anything at all.

**Comment by majkinetor** [comment]
When it is approved I can only PR readme change if you want, to mention it as installation method. Other then that, nothing is needed.

**Comment by nightroman** [comment]
Ah, of course, readme. It's up to you. If you PR, this would be great. Otherwise, I will update it.

**Comment by majkinetor** [comment]
Package is approved and live now

**Comment by nightroman** [comment]
Thank you. I updated README as soon as I saw this and some downloads.
