### ISSUE TITLE
RFC: Invoke-Build engine coding style

### ISSUE THREAD

**Issue by nightroman** [nightroman/Invoke-Build#63]
Let me explain why the code is difficult and let's discuss how to make it easier for potential contributors.

**Why the code is difficult**

Such is the design choice. The choice is questionable from various points of view but it is deliberate. It has its reasons, advantages, and disadvantages. The author and contributors normally deal with disadvantages. Advantages are for users even if they are not fully aware. The good news is that the author and contributors are users, too.

There are build scenarios with hundreds of tasks. The typical example is testing using tasks: Invoke-Build itself, PowerShellTraps, there are others. In the long and especially repetitive runs even shaved milliseconds on each task matter. Thus, faster engine code is preferable and we use an unusual and even cryptic code if it is proven to be faster.

The engine code is supposed to work with user code in the same session and even in same scopes. We should minimize the number of variables exposed to user code. The main reason is not performance. We minimize potential conflicts -> we use unusual names starting with "*". And we would like to reduce engine variable noise on tasks debugging -> we reuse variables when possible -> internal variable names often become somewhat meaningless -> we just keep them short.

There are build scenarios with hundreds of nested build scripts when Invoke-Build is called for each (e.g. PowerShellTraps). Thus, we would like to keep the engine code somewhat compact because reading and parsing takes time for each build script. This is the main drawback of Invoke-Build being a script, not a module function. But the availability of the natural script scope for build scripts overweights all the drawbacks. That is why the engine is a script, not a module (even though it is packaged as a module).

**How to make the code easier for potential contributors**

Overall, for user's sake, i.e. better performance and minimized noise/conflicts, the design choices and inevitable unusual style will probably stay. What the author can do in this case:

- Use less cryptic names for internal functions. Names starting with "*" are officially reserved, so conflicts are unlikely.
- Document internal functions, their parameters, even some variables.

**What else can be done?**

**Comment by michaeltlombardi** [comment]
What you've identified here is a fantastic start to addressing adoption problems via [concept documentation](http://michaeltlombardi.gitlab.io/needful-docs/2-guides/1-what.html). You _definitely_ made intentional design decisions but without clear and cogent explanations of those decisions and the specific implications and implementations, contributors are very likely to be turned away.

Using the example of the [`Get-BuildFile` function](https://github.com/nightroman/Invoke-Build/blob/master/Invoke-Build.ps1#L30), I _know_ this is doing useful things that are probably faster than other methods but it's a _non-obvious_ implementation to most mid-level practitioners and thus relatively intimidating and confusing.

**Comment by adbertram** [comment]
I've only casually browsed the code and cannot speak to it's efficacy but not coming from a Dev background the way you've written PowerShell seems a lot more "devvy" that PowerShellers are used to. For someone that knows a lot about PowerShell but with no traditional dev background, the way in which you've chosen to write PowerShell will off put a lot of people like me into contributing.

I'm sure I could pull out dozens of specific examples but I'm also positive that you have your reasons for them. It's like arguing about code formatting styles. :). Personally, if the code were more easily understood by the IT pro, for example, it would get a lot more contributions.

**Comment by nightroman** [comment]
Let's take a look at practical areas of contribution

**The engine**

- Invoke-Build.ps1 (20 KB)

The engine is feature complete, mostly bugs free, extensively covered by tests.
The code was optimized for better performance when the time was right for this.
This is the least likely area of contribution. Do not get me wrong,
contributions are welcome, I just cannot foresee much of them.

Please find and report issues if you can. This will be a really useful contribution.

**Satellite tools**

- Invoke-Builds.ps1
- Resolve-MSBuild.ps1
- Convert-psake.ps1
- Invoke-Build.ArgumentCompleters.ps1
- Invoke-TaskFromISE.ps1
- Invoke-TaskFromVSCode.ps1
- New-VSCodeTask.ps1
- Show-BuildGraph.ps1
- Show-BuildTree.ps1
- ib.cmd

(41 KB)

This is the most likely area of contributions. The work is in progress and will
continue, especially integration with VS Code. Please improve these tools, add
new, etc.

The code is normal PowerShell code, i.e. not difficult at all, at least
comparing to the engine.

**Documentation**

- Help, Invoke-Build-Help.ps1 (28 KB)
- Wiki (114 KB) https://github.com/nightroman/Invoke-Build/wiki

Contributions are welcome and even wanted. Invoke-Build is very well documented
but the language is probably lame.

BTW, if you want to know how Invoke-Build works then look at the documentation,
not the source code. If something is not clear, please complain, suggest how to
improve.

**Tests and tricks**

- Tests (100 KB) https://github.com/nightroman/Invoke-Build/tree/master/Tests
- Samples, patterns, and various techniques (21 KB) https://github.com/nightroman/Invoke-Build/tree/master/Tasks

All tests work on my machines. But some of them more likely fail on other
machines, especially with non-English PowerShell versions. Please report
or fix such failures.

**Conclusion**

If you want to take part and contribute then it is not that difficult at all.

It is difficult for the very small piece of code, in fact. But difficult is not
impossible and some conceptual documentation for developers is coming soon, too.

In reality it is difficult to contribute to a project with poor support from
maintainers, no matter how simple its source code is.

**Comment by nightroman** [comment]
Here is the prototype https://github.com/nightroman/Invoke-Build/wiki/DEV-Internal-Functions
Work is still in progress. The names are new, still short, but hopefully less cryptic than before.

**Comment by nightroman** [comment]
- Updated [Design-Notes](https://github.com/nightroman/Invoke-Build/wiki/Design-Notes)
- Added [DEV-Public-Functions](https://github.com/nightroman/Invoke-Build/wiki/DEV-Public-Functions)

**Comment by nightroman** [comment]
- v3.3.5 uses less cryptic names for internal functions
- README mentions Design Notes for contributors
- [Design Notes](https://github.com/nightroman/Invoke-Build/wiki/Design-Notes) explain the basics and refer to other pages
    - [DEV Internal Functions](https://github.com/nightroman/Invoke-Build/wiki/DEV-Internal-Functions) - documentation of internal functions
    - [DEV Public Functions](https://github.com/nightroman/Invoke-Build/wiki/DEV-Public-Functions) - design notes on public functions

I will close this issue after a while when it becomes apparently inactive.
My job is not over though, the design and developer notes will be updated
as the work continues.

P.S. To be honest, difficulties of contributing to Invoke-Build are either
exaggerated or just look intimidating. Many people contributed to the engine,
tools, and documentation, as soon as they needed this in practice.

P.P.S. (@michaeltlombardi) `Get-BuildFile` is well explained in *DEV Public
Functions*. `Unsafe` is well explained, too, there was a Twitter request.
If something is not clear for contributions or usage then just ask.

**Comment by gaelcolas** [comment]
This is taking an awesome direction.
@nightroman I would not say the difficulties are exaggerated (difficulty is subjective), but yeah, as @adbertram pointed out it's very intimidating for the non-devvy PowerShellers!

I think the main criteria for maintainability and for contributors is to make sure the impact of a change is in a well-contained scope/area. That's why, I think, the community favours the 1 function per file approach to PowerShell modules.

Potentially, the Build process could re-merge the functions in one unique file, and why not minify (and rename functions & use aliases) it if it improves performance? Do you think that's a viable option?

Given that the gallery supports publishing module AND Scripts, both artefacts could also be uploaded.

Keep up the good work @nightroman, I love using it!

**Comment by nightroman** [comment]
@gaelcolas

Minification is an interesting idea and it is doable. Keeping dev-comments in
sync with sources will be easier. On the other hand, this may add some hassle.
I will keep this idea in mind.

**Comment by glennsarti** [comment]
Hi @nightroman.  Thankyou for continuing to give feedback and help us understand the decisions that were made.

I have a question about the performance aspect.  Do you have any empirical evidence/tests that you have done that shows how much you save using the techniques here.  Your reasoning makes sense in my mind, but do you have any data to back this up?  My thinking is:

Are we prematurely optimising Invoke-Build for speed of 100s of tasks?
How many people/users actually have 100s of tasks? versus total user base?

Thanks again for all your work on this!!  Glenn.

**Comment by nightroman** [comment]
Hi @glennsarti,

You ask interesting and somewhat delicate questions.

IB is used a lot and developed a little. Optimisations do not look premature, at least to me, with my large task batches. Performance tests were performed on making decisions. I did not think of keeping and presenting measurements though. I am making a note for the future performance tests.

For true build scenarios optimisation is not important. Typical build scripts have a few relatively slow tasks. Is this a reason to not optimise? IB is not just for building. It is designed as a general purpose task runner for various scenarios, including numerous relatively fast tasks.

> How many people/users actually have 100s of tasks? versus total user base?

I do not know, maybe it is just me. Is this a reason to not optimise? If I have 100s of tasks then every user can. If large task batches work effectively for me then they are effective for all. In particular, if one decides to code something for IB he may want to run IB tests, too, i.e. some 337 tests for v3+ and 327 for v2.
