### ISSUE TITLE
Importing Tasks & Discussion on Variables

### ISSUE THREAD

**Issue by doesitscript** [nightroman/Invoke-Build#73]
Similar to #47. Adding a few thoughts:

Having to have to dot source the build tasks in the default project build script is cumbersome when sharing build scripts and tasks with others.
Suggest having a folder name and file naming convention that Invoke-Build includes in addition to the default build script when parsing tasks.

Variables are a limiting factor when sharing scripts.
Suggest having a way to declare/describe variables used within a task script. Having a require statement depending on something like BuildHelpers would be a good start. I may be wrong, but having a schema based variable declaration seems to be a better solution because it would allow scripts to know that that their build script that uses variables from "Schema A" to use tasks from another script that use the same "Schema A"

**Comment by nightroman** [comment]
@doesitscript

As confirmed in #47, the ideas make sense. Can you describe your scenario in
details? How do you share tasks now? How do you deal with required variables?
I am collecting use cases for finding patterns. I do not have much yet in order
to start adding features to the tool. But the investigation is in progress.

If you have some examples of the proposed techniques in similar or not tools,
please let me know.

Not for an excuse, just some facts about dot-sourcing. It is a usual technique
in PowerShell. It is a usual technique in MSBuild projects, too. It is called
differently but it is essentially the same.

**Comment by doesitscript** [comment]
Variables:
Currently I use settings file that build oriented variables: source, docs, packages, assets, config, etc
Eventually, I see the need to have schema based json files that can be used as an alternative or to act as a baseline for declared variables in build scripts.  These variables would be imported into the session prior to running the script in the same fashion that dot sourcing build variables form BuildHelpers is done.  Users could then override these variables with settings.ps1 files but at least many different scripts by different authors could begin to consider sharing task scripts having this "contract" of variables. 

Dot Sourcing:
The pain point is sharing work. While dot sourcing is a great way to mimic the ability of making functions from a script available to the current scope, it creates friction to sharing tasks and importing others tasks.  To increase the ability for me to share my tasks with others, it needs to be as simple as the import-module command. Here's a simple example:
I create a semi-generic build script containing tasks: clean, build, publish
A coworker creats a task script that **extracts packages**, **compresses packages**. It has an alias that uses my tasks: task UpdatePackage clean, **extractPackages**, **compressPackage**, publish
Ideally, his tasks would find my tasks in a similar fashsion to exported-functions from a module. I realize that there is a large deal of planning development in powershell in general that would have to be done to get to that point.  I think really what we're seeing here is the beginning of build languages and frameworks PowerShell that exist in other languages (gulp, bower, yoeman, groovy, etc)

In the interum, this is the path I'm suggesting: Create a folder in the projectroot where the build script lives. Save build scripts in this folder.  Prior to parsing the AST of the build script, search the tasks folder for build scripts and automatically include them in the parsing process that Invoke-Build does.

Sharing:
Currently I'm publishing some of my scripts to an internal Artifactory repo. The next moment I have, I'd like create a wrapper function around Publish-Script, Save-Script, Find-Script possibly called Publish-TaskScript, Import-TaskScript (into the current project).  Having the autoparsing of these imported task scripts would take the burden of sharing scripts away from the user by not requiring them to go into their build script and then requiring them to modify their script.

Its a good point that we're used to dot-sourcing but Invoke-Build is not actually dot sourcing the script when it parses the script from what I've seen.  This may seem to simplify the process of importing task scripts but I'm thinking opening up other ways to making tasks available to a build script may increase shareability of build tasks.

**Comment by nightroman** [comment]
@doesitscript

Thank you for the details. I will digest this for a while. Meantime, some
remarks from me to avoid misunderstandings and high expectations, too.

**On variables**

I agree that we need some sort of "requires" helper(s) for build assets, variables
in the first place. I am not sure about "schemes" in the engine itself.

I will probably open another issue for discussing this topic.

**On importing**

> Prior to parsing the AST of the build script ...

AST is not available for the engine while we supports PowerShell v2.
For now we can use v3+ features just in related tools.

> search the tasks folder for build scripts and automatically include them in the parsing process that Invoke-Build does

In some form this is doable, in general. There are some things to think about,
too. With manual dot-sourcing, "cumbersome" or not, you have full control.
With automatic you do not. Sometimes it may not work in a required way.

> Invoke-Build is not actually dot sourcing the script when it parses the script ...

Invoke-Build does not parse. It literally dot-sources builds scripts in its own
script scope, same as the build script scope. Some tokenizing is done just for
getting task synopsis from comments on `Invoke-Build ?`.

And as far as Invoke-Build uses fair dot-sourcing, what you ask for is doable
right now. In your "main" script add:

```powershell
    # import tasks
    foreach($_ in Get-ChildItem ./Tasks/*.tasks.ps1) {. $_}
```

Then drop some *.tasks.ps1* files to *Tasks* and you are done, they are
automatically dot-sourced.

**Comment by nightroman** [comment]
Here is the prototype (temporary branch *requires*):
https://github.com/nightroman/Invoke-Build/tree/requires/Tasks/Import

- it uses the new command `requires` (alias of `Test-BuildAsset`)
- it shows how to import all available task files
- it shows how task files may require their assets
- there are 3 types of assets, 3 imported scripts show them

I think that for now this should be enough in order to resolve this issue.

**Comment by doesitscript** [comment]
This is a great implementation. I'll start using these in some task scripts and close this out. Thank you for the attention and time that you put on this project.

**Comment by nightroman** [comment]
Great! I documented the sample a little bit. I am going to add tests and play with this. Then I will release it in a day or two.

Thank you for opening the issue and your thoughts. Now is the right time for this new feature.

**Comment by nightroman** [comment]
v3.4.0 with the new command `requires` and import samples addresses the issues.
Please take a look and close if everything is fine.

**Comment by nightroman** [comment]
I also added *EXAMPLE 2. Import from a module with tasks* to samples, see
https://github.com/nightroman/Invoke-Build/tree/master/Tasks/Import
The technique is simple but it is not obvious.
