### ISSUE TITLE
Output more details on task processing

### ISSUE THREAD

**Issue by zloeber** [nightroman/Invoke-Build#74]
I may just need to RTFM a bit harder but is there a way to get more descriptive output of the synopsis of a task during the Invoke-Build process? I've put in a helper function that I'm using for something like this that gives a bit more descriptive output as to what the particular task is doing in a project I'm trying to refine  [here](https://github.com/zloeber/ModuleBuild). 

As always, thanks for the great project

**Comment by nightroman** [comment]
Do you mean your function `Write-Description`? If yes, are you suggesting to make something like this built-in? If no, please clarify. Perhaps I am slightly confused by "task synopsis" which means comments like `# Synopsis: ....`, in IB terms.

**Comment by zloeber** [comment]
Sorry for being obtuse. I'm thinking something like the write-description helper I used but built in as an output option when running tasks. It gives a better visual in the console and VS code when running for those not intimately familiar with larger sets of someone else's build tasks. Possibly including the synopsis output from 'Invoke-Build ? | Select Name,Synopsis)' with the build output? I don't know what that looks like though, an additional parameter perhaps?

I'm just floating the idea out there though. IB is a pretty tight script through so the counterargument might be that this kind of superfluous feature may not have a place.

**Comment by nightroman** [comment]
Can you give an example of the suggested output, as you see it?

Is it something like this, perhaps?

The task:

```powershell
    # Synopsis: Do something and something else.
    task Task1 {
        'some output'
    }
```

Output with the task synopsis included:

```
    Build Task1 C:\...\_170613_051456_fr74\.build.ps1
    Task /Task1 : Do something and something else.
    some output
    Done /Task1 00:00:00.0207639
    Build succeeded. 1 tasks, 0 errors, 0 warnings 00:00:00.5391652
```

**Comment by zloeber** [comment]
That is exactly what I was thinking. I imagine that if a task was already run (output is grey) that the description would not be displayed.

**Comment by nightroman** [comment]
This is doable and not so difficult. I do not think the feature is superfluous,
it makes the output easier to analyze and task synopsis useful not just for `ib
?`. I like the idea.

But let me think for some time about the details.

(1) Is it a whole build option or a script option? In any case, is it just a
"switch" or should we have some sort of configurable task header? Tomorrow we
may want to use something instead or in addition to task synopsis, e.g. task
location (file:line), so that you can navigate to a task definition in VSCode
by <kbd>Ctrl+Click</kbd>.

(2) Should it be written on the same like with `task /<path>` or on a separate
line? Note that task paths may be long. In the case of a configurable task
header this is up to a user, then the question is what to use by default.

(3) We can start with something like exposing `Get-BuildSynopsis` which might
be useful in any case. Then

```powershell
    Enter-BuildTask { Write-Build cyan (Get-BuildSynopsis $Task) }
```

will do the trick right now (in some way, maybe not the best, but at least we
will know why it is not the best). It is quite flexible, e.g. you can:

```powershell
    Enter-BuildTask {
        # name and synopsis
        Write-Build Magenta "$($Task.Name) : $(Get-BuildSynopsis $Task)"
        
        # location for Ctrl+Click in VSCode
        Write-Build DarkGray "$($Task.InvocationInfo.ScriptName):$($Task.InvocationInfo.ScriptLineNumber)"
    }
```

**Comment by zloeber** [comment]
I figured that the actual implementation might be somewhat tricky based on what I've been learning about this project. 

I'm just spitballing here but would it possibly make sense to include an InvokeBuild config block that pulls into the current runspace predefined variables related to the InvokeBuild settings and output configuration? That would eliminate extra parameters (which I believe you do try to keep to a minimum) and give you more room to expand features moving forward. perhaps something like:

```
_invokebuildsettings {
    # Any variable defined in this special task will be made global to the entire build process
    # There are several predefined variables that can be used to affect the invoke-build process or output

    # Display task output without synopsis details (default setting = $true)
    $_invokebuild_TerseOutput = $true

    # Display synopsis information on its own line if terse output is disabled (default setting = $true)
    $_invokebuild_VerboseOutputNewLine = $true
}
```
Maybe that would allow you to bake in some of these things with a bit more freedom? I'm sorry but I've not really dug into your scary code enough to be speaking intelligently on this matter though.

**Comment by nightroman** [comment]
I would like to avoid settings and implementing output logic inside IB depending on settings. This is less flexible. I will push the preview of (3), so that `Enter-BuildTask` you can do and output what you want, in particular, output `Get-BuildSynopsis $Task`. No settings are needed for this approach and yet you have full freedom on what and how to output, what colors to use, and etc.

**Comment by nightroman** [comment]
Please, pull the branch `preview` and take a look at two added features, one is
almost final, another is yet questionable.

**Feature 1 (likely to be released), the new function `Get-BuildSynopsis`**

How to use for more details on task processing. In your build script define
`Enter-BuildJob`. Example:

```powershell
    # Print synopsis and location (e.g. for Ctrl+Click in VSCode)
    Enter-BuildJob {
        Write-Build Cyan (Get-BuildSynopsis $Task)
        Write-Build DarkGray "$($Task.InvocationInfo.ScriptName):$($Task.InvocationInfo.ScriptLineNumber)"
    }
    # Synopsis: Some task description 1.
    task Task1 Task2, {'some output 1'}
    # Synopsis: Some task description 2.
    task Task2 {'some output 2'}
```

As a result, the build output looks like

![image](https://user-images.githubusercontent.com/927533/27147996-a29b9e1c-5136-11e7-8f8b-65b0caf195a3.png)

**Comment by nightroman** [comment]
**Feature 2 (is it needed?), the new block `Write-BuildHeader`**

It deals with the automatic variable `$Task` and one argument, the current task
path. If it is not defined in a build script the default is called.
Namely,

```powershell
    {
        param($Path)
        Write-Build Cyan "Task $Path"
    }
```

If it is defined then it writes whatever and how it wants.
For example, for the header with synopsis this block defines:

```powershell
    Write-BuildHeader {
        param($Path)
        Write-Build Cyan "Task $Path : $(Get-BuildSynopsis $Task)"
    }
```

Example script with the above sample:

```powershell
    # Print task path and synopsis
    Write-BuildHeader {
        param($Path)
        Write-Build Cyan "Task $Path : $(Get-BuildSynopsis $Task)"
    }
    # Synopsis: Some task description 1.
    task Task1 Task2, {'some output 1'}
    # Synopsis: Some task description 2.
    task Task2 {'some output 2'}
```

As a result, the build output looks like

![image](https://user-images.githubusercontent.com/927533/27148356-e0af45ae-5137-11e7-848f-28a7c9182ebf.png)

**Comment by nightroman** [comment]
These two features cover the request completely (in my opinion), even though the way of engaging is not like the proposed. What do you think?

The question is: do we really needed the second feature? It adds some more flexibility, yes. How much is it important?

**Comment by nightroman** [comment]
After playing with this I think we need `Write-BuildHeader`. It gives the full
control of task headers. Also, it is called on `-WhatIf`, unlike `Enter-BuildJob`.

I am going to release these new features soon.

P.S. Build parameters or options like `TerseOutput` and `VerboseOutputNewLine`
would be less fiddly, perhaps. But what if some users want custom colors or
task start times or something else? Then we add more (and more) parameters
or answer "Sorry, you cannot". With the new `Write-BuildHeader` they can.

**Comment by nightroman** [comment]
NB: I will use the name `Set-BuildHeader` instead of `Write-BuildHeader`.

**Comment by nightroman** [comment]
Pushed the latest to `preview`. All looks good, a bit later today or tomorrow I will release this.

**Comment by nightroman** [comment]
v3.5.0 supports custom task headers. Let's see how it goes and what else is needed. I can see some possible further development but it is too early.
