### ISSUE TITLE
Wrong MSBUILD selected

### ISSUE THREAD

**Issue by mikecg** [nightroman/Invoke-Build#77]
I started using Invoke-Build about two weeks ago and I am incredibly impressed with how amazing it is. Keep up the amazing work!

I ran into an issue today. One of the developers on my team had VS 2017 Enterprise installed, as well as Team Explorer installed (both installed via the VS 2017 installer). 
Resolve-MSBuild resolves to the MSBuild.exe found in the **C:\Program Files (x86)\Microsoft Visual Studio\2017\Team Explorer** directory instead of the MSBuild.exe found in **C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise** 

When trying to build my csproj using Invoke-Build and the msbuild cmdline tool, there is some Roslyn target that cannot be found in that Team Explorer directory. After uninstalling Team Explorer, Resolve-MSBuild targets the Enterprise msbuild.exe instead, and the csproj builds fine since that Roslyn target exists in that directory.

(Note that I may be wrong about the exact path of Team Explorer MSBuild. I already uninstalled team explorer it and cannot remember)

I think that when both Enterprise and Team Explorer are installed, Resolve-MSBuild should default to the Enterprise MSBuild rather than the Team explorer one.

If this is not enough information, then I can try to reproduce the issue and provide you with more specifics.

**Comment by nightroman** [comment]
I expected that something like this was going to happen. It would be nice to
know the exact name of the Team Explorer installation.

Meanwhile, so far known directories are

- *BuildTools*
- *Community*
- *Enterprise*
- *Professional*
- *Team Explorer* (needs to be confirmed)

I think we should try to choose from available in this order:

- *Enterprise*
- *Professional*
- *Community*
- *BuildTools*
- whatever is left

Presumably, this should work in most cases and solve your problem, too.

**Comment by nightroman** [comment]
Also, do you have the module `VSSetup` installed? (Probably, you do not).

**Comment by nightroman** [comment]
The fix is ready, some extra tests are added and working fine. I will test this (as I can) on my available machines and release in a day or two.

**Comment by nightroman** [comment]
P.S. Thank you for reporting the issue, even though you worked around it. I am very glad that you like the tool. Happy building!

**Comment by mikecg** [comment]
Thanks for the quick fix!

I just started a Team Explorer installation, and the target directory is  **C:\Program Files (x86)\Microsoft Visual Studio\2017\TeamExplorer**. 

I am reluctant to actually reinstall the entire thing because I just don't want to take the chance to destabilize my system, so I have canceled the installation.

I do not have `VSSetup` installed. Would you like me to install it and try something out?

**Comment by nightroman** [comment]
So it is "TeamExplorer", it is good to know.

> Would you like me to install it and try something out?

No, thank you. I hope the plan above should work. Or we will find out what else should be done.
