### ISSUE TITLE
Script block as `File` (new feature)

### ISSUE THREAD

**Issue by nightroman** [nightroman/Invoke-Build#78]
Having to have a build script file is a nuisance in some scenarios. It would be
useful to define, assemble, import, and invoke tasks using just script blocks.

The required change is simple and backward compatible. The parameter `File`
accepts either a script block (new) or a script path (usual).

Example of a script block used as the parameter `File`:

```powershell
    Invoke-Build <tasks> {
        ...
    }
```

The script block either defines the whole build itself or assembles it from
external task scripts. It is possible to alter or redefine tasks, add new
tasks, and set build blocks on the fly.

What are the conventional `$BuildFile` and `$BuildRoot`? `$BuildFile` is
informational and not so important. But `$BuildRoot` is very important,
it is maintained as the current location for build blocks.

One possible convention:

- `$BuildFile` is the calling script.
- `$BuildRoot` is its directory.

Note that `$BuildFile` may be null in cases like jobs, calls from .NET, "run
selection" in some IDE with PowerShell hosting, etc. In such cases we will
just use the current location as the default `$BuildRoot`.

In any case, if the default `$BuildRoot` is not suitable then it may be set to
a required full path explicitly in a build code (documented feature).

**Comment by daviwil** [comment]
This seems really helpful actually, I could include a check for Invoke-Build in my build script and install it from the Gallery before running Invoke-Build with my task definitions, all without needing 2 separate scripts.

**Comment by nightroman** [comment]
@daviwil 
Yes, this is the idea.
[repo/Tasks/Inline](https://github.com/nightroman/Invoke-Build/tree/master/Tasks/Inline) contains some sample use cases.
