### ISSUE TITLE
How to invoke a task multiple times

### ISSUE THREAD

**Issue by mrhockeymonkey** [nightroman/Invoke-Build#79]
It seems as if the default behavior for a build script is to not invoke a task more than once even when it is specified in that order. For example:

```powershell
Task . Clean, Build, Clean

Task Clean {
   #Cleanup code
}

Task Build {
   #Build code
}
```

Is there a way to override this behavior? The use case for me is that I want my CI engine to clean up the environment (if needed), build a fresh power shell module, do some tests and then clean up after itself so as not to leave potentially broken modules sitting around

**Comment by nightroman** [comment]
Hi Scott,

It is not the default behaviour but the concept. A task is an action which is
either invoked once or not invoked. If you need something to be invoked many
times then make it a function and use as:

```powershell
    Task . {Clean}, Build, {Clean}

    function Clean {
       'Cleanup code'
    }

    Task Build {
       'Build code'
    }
```

Output:

```
    Build . C:\tmp\_170703_174144\1.build.ps1
    Task /.
    Cleanup code
    Task /./Build
    Build code
    Done /./Build 00:00:00.0155999
    Task /.
    Cleanup code
    Done /. 00:00:00.0467997
    Build succeeded. 2 tasks, 0 errors, 0 warnings 00:00:00.3119980
```

**Comment by nightroman** [comment]
P.S. And if you need a task *Clean* in addition, too, then define it as

```powershell
    task Clean {Clean}
```

**Comment by mrhockeymonkey** [comment]
I like that a lot! thanks this is really good to know
