### ISSUE TITLE
Add ability to choose which MSBuild architecture to use

### ISSUE THREAD

**Issue by alextercete** [nightroman/Invoke-Build#85]
After #84 was fixed, our automated builds started failing. We're building Visual Studio extensions, which use the VSSDK NuGet package. As part of its build process, a 32-bit process (VSCT.exe) is invoked, which causes [an error](https://stackoverflow.com/questions/27770447/vsct-exe-could-not-load-file-or-assembly) to occur. Ideally, we'd like to be able to force a 32-bit MSBuild process even if we're running on a 64-bit machine.

Would it be possible to add the ability to do something like this?

```powershell
use 15.0:x86 MSBuild
```

The idea being it could be applied to other paths like `VisualStudio\<version>`:

```powershell
use VisualStudio\14.0:x86 MSBuild
```

**Comment by nightroman** [comment]
> Would it be possible to add the ability to do something like this?

For MSBuild, yes, let me investigate and add this feature. The convention `15.0:x86` looks fine, I am just not sure about the colon in it, e.g. psake does not use it. Perhaps we should adopt this existing practice and use `15.0x86`.

**Comment by alextercete** [comment]
Sure, that works for me! The colon was inspired by the way you specify the architecture when [installing packages using apt-get](https://wiki.debian.org/Multiarch/HOWTO#Installing.2Fremoving_packages), but I'm not super attached to that suggestion.

**Comment by nightroman** [comment]
For now, I am going to support only the suffix `x86` which means "ensure 32-bit MSBuild".
In this way, it is going to be consistent across all versions and cover your problem case.
Problem cases with required but not yet supported suffix `x64` are not yet known.

**Comment by alextercete** [comment]
That makes sense.

Let me know if there's anything I can do to help -- I'm happy to have a stab at a pull request if you're not working on it yet.

**Comment by nightroman** [comment]
Thank you. It's all done and being tested. So far so good. I will release this tonight, more likely.

**Comment by nightroman** [comment]
v3.6.4
I knew it was going to happen but was waiting for a problem case. Thank you for your report.
