### ISSUE TITLE
Clean up zip file in Save-NuGetTool.ps1

### ISSUE THREAD

**Issue by JVimes** [nightroman/Invoke-Build#86]
Per [install instructions](https://github.com/nightroman/Invoke-Build#install-as-scripts), I'm using the Invoke-Expression method to get the Invoke-Build scripts:

```posh
Invoke-Expression "& {$((New-Object Net.WebClient).DownloadString('https://github.com/nightroman/PowerShelf/raw/master/Save-NuGetTool.ps1'))} Invoke-Build"
```

That leaves me with a "Invoke-Build" folder, which is what I want. It also leaves Invoke-build.zip, which I do not want.

Suggest deleting the zip file in Save-NuGetTool.ps1 after successful un-zip.

**Comment by nightroman** [comment]
Thank you for your suggestion, I think it's a good idea. Will do shortly.

**Comment by nightroman** [comment]
Done!

**Comment by JVimes** [comment]
Wow, that was fast! 🎉  Thanks @nightroman
