### ISSUE TITLE
Support scripts in Invoke-TaskFromISE.ps1

### ISSUE THREAD

**Issue by JVimes** [nightroman/Invoke-Build#87]
I'm following the [Invoke Task from ISE](https://github.com/nightroman/Invoke-Build/wiki/Invoke-Task-from-ISE) instructions. Does it require that I install Invoke-Build as a module? I'm trying to use the script form of Invoke-Build (scripts in .\Invoke-Build\ folder):

```posh
$null = $psISE.CurrentPowerShellTab.AddOnsMenu.Submenus.Add(
    'Invoke Task in ISE', {Invoke-Build\Invoke-TaskFromISE.ps1}, 'Ctrl+F5')
```

And I get:

> The module 'Invoke-Build' could not be loaded.

A suggestion would be for it to support both module and script forms of Invoke-Build.

Much thanks!

**Comment by nightroman** [comment]
> Does it require that I install Invoke-Build as a module? 

No. Your syntax makes PS think it is a command from a module.

Replace `Invoke-Build\Invoke-TaskFromISE.ps1` with the full path or put `Invoke-TaskFromISE.ps1` somewhere in the path and use just its name (like in the instructions).

**Comment by JVimes** [comment]
Thanks. I now see that Invoke-TaskFromISE.ps1 isn't downloaded with the scripts, so this won't work even with correct syntax.
