### ISSUE TITLE
Chocolatey package installs version subfolder

### ISSUE THREAD

**Issue by cwchapma** [nightroman/Invoke-Build#88]
The chocolatey package appears to be broken.  It installs the module in: "C:\Program Files\WindowsPowerShell\Modules\InvokeBuild\\**3.6.4**\InvokeBuild.psm1"

I believe powershell is looking for the module file in: "C:\Program Files\WindowsPowerShell\Modules\InvokeBuild\InvokeBuild.psm1"

When I call `Import-Module InvokeBuild`, I get

```
PS C:\Users\cchapman> Import-Module Invoke-Build
Import-Module : The specified module 'Invoke-Build' was not loaded because no valid module file was found in any module directory.
At line:1 char:1
+ Import-Module Invoke-Build
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (Invoke-Build:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
```

If I get rid of the version folder, 3.6.4, and move the files up into the InvokeBuild folder, `Import-Module` works.

**Comment by cwchapma** [comment]
I'm using powershell 4.0

**Comment by nightroman** [comment]
Hello, I am not maintaining the choco package and unlikely going to. I welcome the package, though.
Could you please contact the owner of the package?

**Comment by cwchapma** [comment]
I've created a pull request: https://github.com/majkinetor/au-packages/pull/57

**Comment by majkinetor** [comment]
This is merged.

FYI, I also added all supportive scripts in the package, see [notes](https://github.com/majkinetor/au-packages/blob/master/invoke-build/README.md#notes)

**Comment by cwchapma** [comment]
Thank you.  Any chance it will be republished to chocolate.org before the next version of invoke-build?

**Comment by majkinetor** [comment]
Sure: https://chocolatey.org/packages/invoke-build/3.6.5.20170830

**Comment by cwchapma** [comment]
Much appreciated.
