### ISSUE TITLE
Need an idea on implementing incremental job for package manager

### ISSUE THREAD

**Issue by majkinetor** [nightroman/Invoke-Build#91]
On a project I  use `npm install` which takes around 10s each time when there is no new dependency added. The command creates 200MB of locally cached packages. 

Input is obviously both `packages.json` file holding the deps descriptions but also current state of the `node_modules` directory.

Not sure how to determine the output here. 

I think only monitoring changes on `packages.json` would be enough and check node_modules existence.

Any idea on how to speed this up ?

**Comment by majkinetor** [comment]
I see now that I can connect `packages.json` with `package-lock.json`. The docs say:

> package-lock.json is automatically generated for any operations where npm modifies either the node_modules tree, or package.json

This is fortunate case, but I am still not sure what I would do with some other package manager that doesn't have this, such as `dotnet restore` which seems to only put files in `~\.nuget` folder.

**Comment by nightroman** [comment]
In your task X with a package restore tool, with known inputs but no known or well-defined outputs, you can write a dummy output file (sort of log but the content is not important). Then configure your task using this file as outputs:

```powershell
task Restore -Inputs ... -Outputs Restore.log {
	... # do your restore
	Set-Content Restore.log Done
}
```

**Comment by majkinetor** [comment]
That wouldn't work If I manually delete the package from nuget packages directory. But I guess that is upstream problem, to provide the way to know if dependencies are met or no. For example with chocolatey `choco list invoke-build --lo -r` returns version if invoke-build is installed or nothing if not If output is saved to file I can use it as an Input then with the mentioned dummy output.

Thx for the help.
