### ISSUE TITLE
Build modularization

### ISSUE THREAD

**Issue by majkinetor** [nightroman/Invoke-Build#92]
My project contain several services and I would like to make sure each of them has its own build, but mother build also exists that can combine child builds and add new ones.

Do you think the following setup has some hidden surprises and what is your stance on it?

```powershell
parent\
    rest\
        .build.ps1
            $script:name = if ($BuildFile -ne $MyInvocation.MyCommand.Source) { 'rest\' }

            #Synopsis: Build the REST service
            task ${name}build {
                $Task.Name 
            }
    web\
        .build.ps1
             $script:name = if ($BuildFile -ne $MyInvocation.MyCommand.Source) { 'web\' }

             #Synopsis: Build the Web service
             task ${name}build {
                 $Task.Name 
             }
.build.ps1
    . .\rest\.build.ps1
    . .\web\.build.ps1

    #Synopsis: Build all services
    task build {
        $Task.Name
    }, rest\build, web\build
```

This makes it possible to do:

```powershell
parent\> ib ?

Name       Jobs                        Synopsis
----       ----                        --------
rest\build {}                          Build the REST service
web\build  {}                          Build the web service
build      {{}, rest\build, web\build} Build all services

parent\> ib build

Build build parent\.build.ps1
Task /build
    build
Task /build/rest\build
    rest\build
Done /build/rest\build 00:00:00.0009624
Task /build/web\build
    web\build
Done /build/web\build 00:00:00.0010035
Done /build 00:00:00.0039713
Build succeeded. 3 tasks, 0 errors, 0 warnings 00:00:00.0400680

# -------------------------------------------------------------

cd rest;
parent\rest>? ib ?

Name  Jobs Synopsis
----  ---- --------
build {}   Build the REST service

parent\rest> ib build
Build build parent\rest\.build.ps1
Task /build
    build
Done /build 00:00:00.0010032
```

**Comment by majkinetor** [comment]
`$BuildRoot` is definitely problem here tho, but its solvable by using `$PSScriptRoot`

**Comment by nightroman** [comment]
Complex modular build systems with several nested levels is a good idea and IB
was designed for this from the very beginning. Here is the system that works
perfectly for many years: [FarNet family (C++, C#, PowerShell)](https://github.com/nightroman/Invoke-Build/wiki/Build-Scripts-in-Projects#farnet-family-c-c-powershell)
Its build tree consists of 20+ builds scripts with 4+ nested levels.

Thus, what you want is doable. Please learn the details in the above example.

Yet, I do not recommend to dot-source whole build scripts. Not good. It's like
in MSBuild world trying to import a whole .csproj project into another. Project
files are not designed for this.

Instead, MSBuild imports *shared targets*, not whole projects. And Invoke-Build
dot-sources *shared tasks*, not whole build scripts. In the above system such a
file is *FarNet.tasks.ps1*. It is imported by 11 other builds scripts. But it
is not used itself as a build script. It is a task library.

**Comment by majkinetor** [comment]
Will look into it. Thanks.

**Comment by nightroman** [comment]
In other words, parent build scripts *invoke* child build scripts as builds by
`Invoke-Build`, not *dot-source* them as PowerShell scripts. But they all may
dot-source some common tasks as PowerShell scripts.
