### ISSUE TITLE
Parallel Builds that fail don't cancel builds in progress

### ISSUE THREAD

**Issue by JT-Bruch** [nightroman/Invoke-Build#93]
Currently switching from PSake to Invoke-Builds and I'm leveraging the parallel build pipeline to start three independent build pipelines.  I looked in the Invoke-Builds.ps1 but was unable to find a flag or something that allows for the build to exit if any of the builds fail at any time.  

The three build process I have in place vary in time (due to system constraints) and if any of them fail I need the build process to immediately exit so I can report the errors back to the developer?  If I am blind and just missed it, I can help with updating documentation if needed.

```
# These build parameter hashes are not changed (to be tested).
EnsureDirExists ".\logs\"
$build0 = @{File='pipeline1.build.ps1';  Task="pipeline1"; Log='.\logs\pipeline1.log'}
$build1 = @{File='pipeline2.build.ps1'; Task='pipeline2'; Log='.\logs\pipeline2.log'}
$build2 = @{File='pipeline3.build.ps1'; Task='pipeline3'; Log='.\logs\pipeline3.log'}

$ErrorActionPreference = 'Stop'

# But this array items will be replaced with copied and amended hashes:
# File is resolved to its full path, added Result contains build results.
# NOTE: if [hashtable[]] is omitted then the $build is not changed because
# PowerShell converts it to [hashtable[]] and the copy is actually changed.
[hashtable[]]$build = $build0, $build1, $build2

# As far as it is going to fail due to $build1, use try..catch.
# Get the results using the variable name.
$message = ''
try {
	Invoke-Builds -Build $build -Result Result
}
catch {
	$message = "$_"
	"Oh noes: $message"
	throw
}

```

**Comment by nightroman** [comment]
There is no such an option, you are not blind, do not worry. This was not needed so far. But the feature makes sense indeed. Let me think of it and take care (unless you want to do or suggest something yourself, of course).

P.S. Just curious, how was it done with PSake. PS jobs?

**Comment by JT-Bruch** [comment]
I didn't have it implemented via PSake.  However you could hack it via PS Jobs.  However this project is much cleaner than PSake, so I decided to move it here and leverage the Parallel Builds.    

 I'm moving our project to a mono repository and collapsing & optimizing our build pipelines since it can take up to an hour in its current form.  Trying to get my devs workflows a bit faster.  I was looking at Invoke-Builds.ps1 (https://github.com/nightroman/Invoke-Build/blob/master/Invoke-Builds.ps1#L164) and if you had a switch (FailHard) or something along those lines it should be pretty easy to implement.  

Unless you have any other better suggestions?  I'm open to anything :)

**Comment by nightroman** [comment]
Presumably, we need:

- a new switch (`FailHard` sounds good)
- replace `WaitOne` with `WaitAny` and change the logic of the job loop
- on a build failure call `$pool.Close()` (hopefully this works)

It is not a cosmetic change but it is not major either. But let me think a little bit. For some other reasons I am not quite happy with using runspace pools in the first place. Maybe it is a good time to think and redesign.

**Comment by JT-Bruch** [comment]
Okay sounds good, let me know if there is anything I can do to help.  I would be open to modifying the existing loop as a first pass while you are redesigning it.  

I do have a bit of a dependency of moving our source to the new pipeline until this is in place.  :)

**Comment by nightroman** [comment]
Please see the branch https://github.com/nightroman/Invoke-Build/tree/issue93
It will be useful if you try and let me know how it works for you.
You only need the script *Invoke-Builds.ps1* from there.

**Comment by JT-Bruch** [comment]
You sir are a saint.  Thank you.  Will work with it now.
