### ISSUE TITLE
Any way to run a function or task upon error or completion of task(s)?

### ISSUE THREAD

**Issue by EdGrant63** [nightroman/Invoke-Build#94]
Hello,

I am using Invoke-Build and it is working great for the project I am working on, so first of all I would like to say Thanks :). 

What I am trying to accomplish is creating a PowerShell transcript with all of the output that Invoke-Build provides. I am planning on running the build script as a scheduled task, and I would like to get a log file so I can see if anything has gone wrong. Right now I can do a Start-Transcript in the build script, but I was wondering if I could somehow make it so I can call Stop-Transcript when the script completes; either with a successful build or on an error.

Thanks!

**Comment by EdGrant63** [comment]
Actually, never mind, I found a way to do this using native PowerShell. I just wrapped the call to Invoke-Build in a Try-Catch-Finally and this accomplished what I was looking for.

`try {
	& $invokeBuild $args Tasks.ps1
}
catch {
	Write-Verbose "Build has failed with error $_"
	Stop-Transcript
}
finally{
	Stop-Transcript
}`

**Comment by nightroman** [comment]
I think `Stop-Transcript` in `catch` is redundant and perhaps even wrong because it should be always called in `finally`.

**Comment by EdGrant63** [comment]
@nightroman , good point, I'll remove it. Thanks!
