### ISSUE TITLE
`?` can't be used with other tasks

### ISSUE THREAD

**Issue by DavidSimner** [nightroman/Invoke-Build#97]
Given this input:
```
Invoke-Build -Task @('?', '.') -File {
  # Synopsis: Hello...
  task . {
    Write-Output '... World!'
  }
}
```

Version `3.7.1` of `InvokeBuild` outputs:
```
Name Jobs Synopsis
---- ---- --------
.    {}   Hello...
```

Whereas, I would expect both `?` as well as `.` tasks to run, e.g. the output should be:
```
Name Jobs Synopsis
---- ---- --------
.    {}   Hello...

Build . C:\git\project\run-build.ps1
Task /.
... World!
Done /. 00:00:00.0120327
Build succeeded. 1 tasks, 0 errors, 0 warnings 00:00:00.1443542
```

**Comment by nightroman** [comment]
If this is a bug report then this behavior is by design, not a bug.
If this is a feature request then I am not sure why the suggested feature is useful.

**Comment by nightroman** [comment]
Some points:

- `?` is not a task, it is a surrogate with a special meaning and purpose (avoid an extra parameter)
- It is not designed for use in build scenarios, it is like get help info about tasks
- It outputs task info objects, build outputs strings (normally)

**Comment by DavidSimner** [comment]
This is related to #98 as yet another way of surfacing information to help developers reading a build output get more information about the build and about what's happening, but if it's by design that `?` looks like a task, is callable like a task, but isn't actually a task, then I can see that this can't be made to work.

**Comment by nightroman** [comment]
OK, if for some reason you need this task info as task then create such a task explicitly:

```powershell
task test {
    42
}
task help {
    Invoke-Build ? | Out-String
}
```
so that `Invoke-Build -Task help, test` produces:

```
Build help, . C:\Users\rjq\Desktop\_171103_140903\.build.ps1
Task /help
Name Jobs Synopsis
---- ---- --------
test {}
help {}
Done /help 00:00:00.0779995
Task /.
42
Done /. 00:00:00
Build succeeded. 2 tasks, 0 errors, 0 warnings 00:00:00.3587977
```

This will not work for inline scripts (as your example) though,
but for normal scripts this should work just fine.
