### ISSUE TITLE
Log output

### ISSUE THREAD

**Issue by majkinetor** [nightroman/Invoke-Build#99]
I think ib would benefit from option to have entire output saved in log file. Notice that `start-transcript` [doesn't work well for native applications](https://blogs.msdn.microsoft.com/powershell/2010/01/04/workaround-for-start-transcript-on-native-processes/) (workaround doesn't work well too) and other options like `tee`, `*>` etc. all have their own drawbacks. I would like to see everything that is output as in interactive run (or when I use AppVeyor/Gitlab etc..) .

Some options could be related to handling multiple runs - log file per run or appending, rotation on size etc... Option to use [ANSI escape codes](https://gist.github.com/majkinetor/4cebc89c48ba67b6aee621305075f01c) instead of normal colors is useful too, so that `get-content log` will show colors from the run.

**Comment by nightroman** [comment]
Well, I rather do not know how to do this. The problem (or just lack) of rich
logging exists as such in PowerShell and its core tools. Your notes describe
this issue.

To be honest, I am not going to do anything about this. Not because I am lazy,
busy or do not like the idea (I like it). I do not see a reasonable way, so
that "ib would benefit" for real and not in fact get an anti-feature.

If you know reasonable solutions let's discuss them. Otherwise, I will close
the issue. I did think of this already in the past. Nothing changes so far.

Meanwhile, you can output build logs to files using `Out-File`. You lose
colors, yes. It is not a big deal in many cases. Is it a real problem?

**Comment by majkinetor** [comment]
`Out-File` can't be used like that, I need complete log first. The problem is how to get entire output (all streams).

There is one solution that seems to work: invoking stuff in background job, then getting its streams
( for example `$job.ChildJobs[0].Error` but also all 6 are available) and getting the results all the time with `rcjb`.

The only problem I see is that output isn't fluid it happens in batches. The same is true tho with `tee` command.

**Comment by nightroman** [comment]
It sounds like you need your own host with its own implementation of `PSHostUserInterface`. Then you will have full and fluid control over all streams. Then you decide what is written, how, and where.

The task has nothing to do with Invoke-Build, though. Also, I do know how it is going to work with external apps and dozens of other things. I have and use my own host in [FarNet](https://github.com/nightroman/FarNet). I can tell, it was not a picnic to implement it.

**Comment by nightroman** [comment]
So what is the exact suggestion?

**Comment by nightroman** [comment]
I am closing this issue. The idea is good as such. At the same time, it is not clear what should be done. And it is not clear that this effort, features, and overall cost are reasonable. As I mentioned, I already thought about this.

I hope PowerShell logging will improve eventually and all PowerShell tools will win. If this is not true or it takes too long then a generic solution is needed anyway, i.e. not just for Invoke-Build.

Feel free to reopen or open another issue if you have new ideas.

**Comment by majkinetor** [comment]
Fair enough. Lets see how Posh 6 handles this.

**Comment by nightroman** [comment]
Hi @majkinetor 
FYI Having played with various logging methods, I created this summary
https://github.com/nightroman/Invoke-Build/tree/main/Tasks/Logging

Where are you with logging today with somewhat mature PowerShell Core?
What are your preferred methods? If you do not mind, a few words, thank you!
